using System;
using System.Collections.Generic;

namespace VAICOM
{
    namespace Database
    {

        public static partial class Aliases
        {

            public static Dictionary<string, string> airecipients = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
            
                // flight

                { "Flight",                 "flight"                },
                { "Element",                "element"               },
                { "Section",                "element"               },
                { "One",                    "wingman1"              },
                { "1",                      "wingman1"              },
                { "Lead",                   "wingman1"              },
                { "Winger",                 "wingman2"              },
                { "Two",                    "wingman2"              },
                { "2",                      "wingman2"              },
                { "Three",                  "wingman3"              },
                { "3",                      "wingman3"              },
                { "Four",                   "wingman4"              },
                { "4",                      "wingman4"              },

                { "Gopher",                 "wingman2"              },
                { "Pyro",                   "wingman3"              },
                { "Bozo",                   "wingman4"              },

                // JTAC

                { "JTAC",                   "jtac"                  },
                { "Patrol",                 "jtac"                  },
                { "Operator",               "jtac"                  },

                { "Axeman",                 "axeman"                },
                { "Darknight",              "darknight"             },
                { "Eyeball",                "eyeball"               },
                { "Finger",                 "finger"                },
                { "Firefly",                "firefly"               },
                { "Moonbeam",               "moonbeam"              },
                { "Playboy",                "playboy"               },
                { "Pointer",                "pointer"               },
                { "Warrior",                "warrior"               },
                { "Whiplash",               "whiplash"              },

                { "Pinpoint",               "pinpoint"              },
                { "Ferret",                 "ferret"                },
                { "Shaba",                  "shaba"                 },
                { "Hammer",                 "hammer"                },
                { "Jaguar",                 "jaguar"                },
                { "Deathstar",              "deathstar"             },
                { "Anvil",                  "anvil"                 },
                { "Mantis",                 "mantis"                },
                { "Badger",                 "badger"                },

                { "Boar",                   "boar"                  },
                { "Chevy",                  "chevy"                 },
                { "Colt",                   "colt"                  },
                { "Dodge",                  "dodge"                 },
                { "Enfield",                "enfield"               },
                { "Ford",                   "ford"                  },
                { "Hawg",                   "hawg"                  },
                { "Pig",                    "pig"                   },
                { "Pontiac",                "pontiac"               },
                { "Springfield",            "springfield"           },
                { "Tusk",                   "tusk"                  },
                { "Uzi",                    "uzi"                   },

                { "Nearest Patrol",         "nearestjtac"           },

                //ATC

                { "ATC",                    "atc"                   },
                { "Tower",                  "atc"                   },
                { "Traffic",                "atc"                   },
                { "Nearest ATC",            "nearestairfield"       },
                { "Nearest Airfield",       "nearestairfield"       },
                { "Proxy",                  "nearestairfield"       },
                //{ "Alternate",              "alternateatc"          },

                // caucasus

                { "Anapa",                  "Anapa-Vityazevo"       },
                { "Batumi",                 "Batumi"                },
                { "Beslan",                 "Beslan"                },
                { "Gelendzhik",             "Gelendzhik"            },
                { "Gudauta",                "Gudauta"               },
                { "Khanskaya",              "Maykop-Khanskaya"      },
                { "Kobuleti",               "Kobuleti"              },
                { "Kolkhi",                 "Senaki-Kolkhi"         },
                { "Krasnodar",              "Krasnodar-Center"      },
                { "Krymsk",                 "Krymsk"                },
                { "Kutaisi",                "Kutaisi"               },
                { "Lochini",                "Tbilisi-Lochini"       },
                { "Minvody",                "Mineralnye Vody"       },
                { "Mozdok",                 "Mozdok"                },
                { "Nalchik",                "Nalchik"               },
                { "Novorossiysk",           "Novorossiysk"          },
                { "Pashkovsky",             "Krasnodar-Pashkovsky"  },
                { "Senaki",                 "Senaki-Kolkhi"         },
                { "Sochi",                  "Sochi-Adler"           },
                { "Soganlug",               "Soganlug"              },
                { "Sukhumi",                "Sukhumi-Babushara"     },
                { "Tbilisi",                "Tbilisi-Lochini"       },
                { "Vaziani",                "Vaziani"               },
                
                // Marianas

                { "Agana Tower",            "Antonio B. Won Pat Intl"  },
                { "Andersen",               "Andersen AFB"             },
                { "Boonie",                 "Andersen AFB"             },
                { "Guam",                   "Antonio B. Won Pat Intl"  },
                { "Guam Centre",            "Antonio B. Won Pat Intl"  },
                { "Rota",                   "Rota Intl"                },
                { "Saipan",                 "Saipan Intl"              },
                { "Tinian",                 "Tinian Intl"              },

                // Marianas WWII

                { "Agana",                  "Agana"                 },
                { "Agana Field",            "Agana"                 },
                { "Airfield three",         "Airfield 3"            },
                { "Charon Kanoa",           "Charon Kanoa"          },
                { "East Field",             "Kagman"                },
                { "Gurguan Point",          "Gurguan Point"         },
                { "Isley",                  "Isley"                 },
                { "Isley Field",            "Isley"                 },
                { "Kagman",                 "Kagman"                },
                { "Marpi",                  "Marpi"                 },
                { "Marpi Point",            "Marpi"                 },
                { "North Field",            "Ushi"                  },
                { "Orote",                  "Orote"                 },
                { "Orote Field",            "Orote"                 },
                { "Pagan",                  "Pagan"                 },
                { "Rota Field",             "Rota"                  },
                { "Ushi",                   "Ushi"                  },
                { "Ushi Point",             "Ushi"                  },

                // Nevada

                { "Boulder",                "Boulder City"          },
                { "Boulder City",           "Boulder City"          },
                { "Bullhead",               "Laughlin"              },
                { "Creech",                 "Creech"                },
                { "Dreamland",              "Groom Lake"            },
                { "Graceland",              "North Las Vegas"       },
                { "Groom Lake",             "Groom Lake"            },
                { "Henderson",              "Henderson Executive"   },
                { "Indian Springs",         "Creech"                },
                { "Las Vegas",              "McCarran International"},
                { "Laughlin",               "Laughlin"              },
                { "McCarran",               "McCarran International"},
                { "Nellis",                 "Nellis"                },
                { "Nellis Control",         "Nellis"                },
                { "North Las Vegas",        "North Las Vegas"       },
                { "Silverbow",              "Tonopah Test Range"    },
                { "Tonopah",                "Tonopah Test Range"    },

                // Normandy

                { "Azeville",               "Azeville"                      },
                { "Bazenville",             "Bazenville"                    },
                { "Beny",                   "Beny-sur-Mer"                  },
                { "Biniville",              "Biniville"                     },
                { "Brucheville",            "Brucheville"                   },
                { "Cardonville",            "Cardonville"                   },
                { "Chailey",                "Chailey"                       },
                { "Chippelle",              "Chippelle"                     },
                { "Cretteville",            "Cretteville"                   },
                { "Cricqueville",           "Cricqueville-en-Bessin"        },
                { "Deux Jumeaux",           "Deux Jumeaux"                  },
                { "Evreux",                 "Evreux"                        },
                { "Forde",                  "Forde"                         },
                { "Funtington",             "Funtington"                    },
                { "Lantheuil",              "Lantheuil"                     },
                { "Lessay",                 "Lessay"                        },
                { "Longues",                "Longues-sur-Mer"               },
                { "Maupertus",              "Maupertus"                     },
                { "Meautis",                "Meautis"                       },
                { "Molay",                  "Le Molay"                      },
                { "Needs Oar",              "Needs Oar Point"               },
                { "Picauville",             "Picauville"                    },
                { "Saint Laurent",          "Sainte-Laurent-sur-Mer"        },
                { "Saint Pierre",           "Saint Pierre du Mont"          },
                { "Sainte Croix",           "Sainte-Croix-sur-Mer"          },
                { "Sommervieu",             "Sommervieu"                    },
                { "Tangmere",               "Tangmere"                      },

                // Persian Gulf

                { "Abu Dhabi",              "Abu Dhabi Intl"                },
                { "Abu Musa",               "Abu Musa Island"               },
                { "Al Ain International",   "Al Ain Intl"                   },
                { "Al Bateen",              "Al-Bateen"                     },
                { "Al Dhafra",              "Al Dhafra AFB"                 },
                { "Al Maktoum",             "Al Maktoum Intl"               },
                { "Al Minhad",              "Al Minhad AFB"                 },
                { "Al Safran",              "Liwa AFB"                      },
                { "Bandar Abbas",           "Bandar Abbas Intl"             },
                { "Bandar e Jask",          "Bandar-e-Jask"                 },
                { "Bandar Lengeh",          "Bandar Lengeh"                 },
                { "Dubai",                  "Dubai Intl"                    },
                { "DubaiControl",           "Dubai Intl"                    },
                { "Fujairah",               "Fujairah Intl"                 },
                { "Havadarya",              "Havadarya"                     },
                { "Jiroft",                 "Jiroft"                        },
                { "KERMAN",                 "Kerman"                        },
                { "Kerman Airport",         "Kerman"                        },
                { "Khasab",                 "Khasab"                        },
                { "Kish",                   "Kish Intl"                     },
                { "Lar",                    "Lar"                           },
                { "Lar Airbase",            "Lar"                           },
                { "LAV",                    "Lavan Island"                  },
                { "Lavan Island",           "Lavan Island"                  },
                { "Lengeh",                 "Bandar Lengeh"                 },
                { "Liwa Airbase",           "Liwa AFB"                      },
                { "OIJK",                   "Jiroft"                        },
                { "OIKB",                   "Bandar Abbas Intl"             },
                { "OMAA",                   "Abu Dhabi Intl"                },
                { "OMAD",                   "Al-Bateen"                     },
                { "OMAL",                   "Al Ain Intl"                   },
                { "OMAM",                   "Al Dhafra AFB"                 },
                { "OMDM",                   "Al Minhad AFB"                 },
                { "OMDW",                   "Al Maktoum Intl"               },
                { "OMFJ",                   "Fujairah Intl"                 },
                { "OMNK",                   "Sas Al Nakheel"                },
                { "OMSJ",                   "Sharjah Intl"                  },
                { "Qeshm Island",           "Qeshm Island"                  },
                { "Ras Al Khaimah",         "Ras Al Khaimah Intl"           },
                { "Ras Tower",              "Ras Al Khaimah Intl"           },
                { "Sas Al Nakheel",         "Sas Al Nakheel"                },
                { "Sharjah",                "Sharjah Intl"                  },
                { "Shiraz",                 "Shiraz Intl"                   },
                { "Shiraz International",   "Shiraz Intl"                   },
                { "Sir Abu Nuayr",          "Sir Abu Nuayr"                 },
                { "Sirri",                  "Sirri Island"                  },
                { "Sirri Island",           "Sirri Island"                  },

                //Channel map
                
                { "Calonne",                "Merville Calonne"       },
                { "Detling",                "Detling"                },
                { "Drucat",                 "Abbeville Drucat"       },
                { "Dunkirk",                "Dunkirk Mardyck"        },
                { "Hawkinge",               "Hawkinge"               },
                { "High Halden",            "High Halden"            },
                { "Lympne",                 "Lympne"                 },
                { "Manston",                "Manston"                },
                { "Saint Omer",             "Saint Omer Longuenesse" },

                // Syria map

                { "Abu al Duhur",           "Abu al-Duhur"          },
                { "Adana",                  "Adana Sakirpasa"       },
                { "Adiyaman",               "Adiyaman"              },
                { "Akrotiri",               "Akrotiri"              },
                { "Al Qusayr",              "Al Qusayr"             },
                { "Aleppo",                 "Aleppo"                },
                { "An Nasiriyah",           "An Nasiriyah"          },
                { "At Tanf",                "At Tanf"               },
                { "Beirut",                 "Beirut-Rafic Hariri"   },
                { "Chukurova",              "Chukurova"             },
                { "Damascus",               "Damascus"              }, //new additions
                { "Deir ez Zor",            "Deir ez-Zor"           },
                { "Deir ez-Zor",            "Deir ez-Zor"           },
                { "Der Salman",             "Marj as Sultan South"  },
                { "Diyarbakir",             "Diyarbakir"            },
                { "Dumayr",                 "Al-Dumayr"             },
                { "Ercan",                  "Ercan"                 },
                { "Eyn Shemer",             "Eyn Shemer"            },
                { "Gaziantep",              "Gaziantep"             },
                { "Gazipasa",               "Gazipasa"              },
                { "H 3",                    "H3"                    },
                { "H 3 Northwest",          "H3 Northwest"          },
                { "H 3 Southwest",          "H3 Southwest"          },
                { "H 4",                    "H4"                    },
                { "Haifa",                  "Haifa"                 },
                { "Hamat",                  "Wujah Al Hajar"        },
                { "Hariri",                 "Beirut-Rafic Hariri"   },
                { "Hatay",                  "Hatay"                 },
                { "Herzliya",               "Herzliya"              },
                { "Incirlik",               "Incirlik"              },
                { "Jirah",                  "Jirah"                 },
                { "Khalkhalah",             "Khalkhalah"            },
                { "King Abdullah",          "King Abdullah II"      },
                { "King Abdullah II",       "King Abdullah II"      },
                { "King Hussein",           "King Hussein Air College"  },
                { "Kiryat",                 "Kiryat Shmona"         },
                { "Lakatamia",              "Lakatamia"             },
                { "Larnaca",                "Larnaca"               },
                { "Latakia",                "Bassel Al-Assad"       },
                { "Marj as Sultan",         "Marj as Sultan North"  },
                { "Marj Ruhayyil",          "Marj Ruhayyil"         },
                { "Marka",                  "Marka"                 },
                { "Megiddo",                "Megiddo"               },
                { "Mezzeh",                 "Mezzeh"                },
                { "Minakh",                 "Minakh"                },
                //{ "Tel Nof",                "Tel Nof"               }, //Already defined in Sinai
                //{ "Hatzor",                 "Hatzor"                }, //Already defined in Sinai
                //{ "Palmachim",              "Palmachim"             }, //Already defined in Sinai
                //{ "Ben Gurion",             "Ben Gurion"            }, //Already defined in Sinai
                { "Muwaffaq Salti",         "Muwaffaq Salti"        },
                { "Paphos",                 "Paphos"                },
                { "Prince Hassan",          "Prince Hassan"         },
                { "Qabr as Sitt",           "Qabr as Sitt"          },
                { "Ramat David",            "Ramat David"           },
                { "Rasin",                  "Kuweires"              },
                { "Rene Mouawad",           "Rene Mouawad"          },
                { "Riyaq",                  "Rayak"                 },
                { "Shemer",                 "Eyn Shemer"            },
                { "Taftanaz",               "Taftanaz"              },
                { "Thalah",                 "Tha'lah"               },

                // Sinai map

                { "Abu Rudeis",             "Abu Rudeis"            },
                { "Abu Suwayr",             "Abu Suwayr"            },
                { "AbuSultan",              "Difarsuwar Airfield"         },
                { "Al Bahr al Ahmar",                         "Al Bahr al Ahmar"                       },
                { "Al Mansurah",            "Al Mansurah"           },
                { "Al Rahmaniyah",                           "Al Rahmaniyah Air Base"                 },
                { "Al Rahmaniyah Air Base",                  "Al Rahmaniyah Air Base"                 },
                { "AzZaqaziq",              "AzZaqaziq"             },
                { "Baluza",                 "Baluza"                },
                { "Ben Gurion",             "Ben-Gurion"            },
                { "Beni Suef",             "Beni Suef"              },
                { "Bilbeis",                "Bilbeis Air Base"      },
                { "Bilbeis Air Base",       "Bilbeis Air Base"      },
                { "Bir Hasanah",            "Bir Hasanah"           },
                { "Birma",                 "Birma Air Base"         },
                { "Birma Air Base",        "Birma Air Base"         },
                { "Borg El Arab",                            "Borg El Arab International Airport"     },                
                { "Borg El Arab International Airport",      "Borg El Arab International Airport"     },
                { "Cairo",                  "Cairo International Airport"  },
                { "Cairo International Airport", "Cairo International Airport"  },
                { "Cairo West",             "Cairo West"            },
                { "El Arish",               "El Arish"              },
                { "El Gora",                "El Gora"               },
                { "El Minya",              "El Minya"               },
                { "Fayed",                  "Fayed"                 },
                { "Gebel El Basur",                          "Gebel El Basur Air Base"                },
                { "Gebel El Basur Air Base",                 "Gebel El Basur Air Base"                },
                { "Hasanah",                "Bir Hasanah"           },
                { "Hatsor",                 "Hatzor"                },
                { "Hatzerim",               "Hatzerim"              },
                { "Hatzor",                 "Hatzor"                },
                { "Hurghada",                                 "Hurghada International Airport"         },
                { "Hurghada International Airport",           "Hurghada International Airport"         },
                { "Inshas Airbase",         "Inshas Airbase"        },
                { "Ismailiyah",             "Al Ismailiyah"         },
                { "Jandali",                "Wadi al Jandali"             },
                { "Jiyanklis",                               "Jiyanklis Air Base"                     },
                { "Jiyanklis Air Base",                      "Jiyanklis Air Base"                     },
                { "Kedem",                  "Kedem"                 },
                { "Kibrit",                 "Kibrit Air Base"       },
                { "Kibrit Air Base",        "Kibrit Air Base"       },
                { "Kom Awshim",            "St Catherine"           },
                { "Melez",                  "Melez"                 },
                { "Nevatim",                "Nevatim"               },
                { "Ovda",                   "Ovda"                  },
                { "Palmachim",              "Palmachim"             },
                { "Quwaysina",             "Kom Awshim"             },
                { "Ramon",                  "Ramon Airbase"         },
                { "Ramon Airbase",          "Ramon Airbase"         },
                { "Ramon International ",                     "Ramon International Airport"            },
                { "Ramon International Airport",              "Ramon International Airport"            },
                { "Saint Catherine",        "St Catherine"          },
                { "Salihiyah",              "As Salihiyah"          },
                { "Sdee Dov",               "Sde Dov"              },
                { "Sharm El Sheikh",                          "Sharm El Sheikh International Airport"  },
                { "Sharm El Sheikh International Airport",    "Sharm El Sheikh International Airport"  },
                { "Tel Nof",                "Tel Nof"               },
                { "Wadi Abu Rish",          "Wadi Abu Rish"         },

                // South Atlantic map

                { "Aeropuerto de Gobernador Gregores",  "Aeropuerto de Gobernador Gregores"    },
                { "de Gobernador Gregores",   "Aeropuerto de Gobernador Gregores"    },
                { "De Tolhuin",             "Aerodromo De Tolhuin"  },
                { "El Calafate",            "El Calafate"           },
                { "Franco Bianco",          "Franco Bianco"         },
                { "Goose Green",            "Goose Green"           },
                { "Luis Piedrabuena",       "Comandante Luis Piedrabuena"        },
                { "Mount Pleasant",         "Mount Pleasant"        },
                { "O'Higgins",              "Aerodromo O'Higgins"   },
                { "Pampa Guanaco",          "Pampa Guanaco"         },
                { "Port Stanley",           "Port Stanley"          },
                { "Porvenir",               "Porvenir Airfield"     },
                { "Puerto Natales",         "Puerto Natales"        },
                { "Puerto Santa Cruz",      "Puerto Santa Cruz"     },
                { "Puerto Williams",        "Puerto Williams"       },
                { "Punta Arenas",           "Punta Arenas"          },
                { "Rio Chico",              "Rio Chico"             },
                { "Rio Gallegos",           "Rio Gallegos"          },
                { "Rio Grande",             "Rio Grande"            },
                { "Rio Turbio",             "Rio Turbio"            },
                { "San Carlos",             "San Carlos FOB"        },
                { "San Julian",             "San Julian"            },
                { "Ushuaia",                "Ushuaia"               },
                { "Ushuaia Helo Port",      "Ushuaia Helo Port"     },

                // Kola Peninsular map

                { "Alakurtti",              "Alakurtti"             },
                { "Alta",                   "Alta"                  },
                { "Andoya",                 "Andoya"                },
                { "Banak",                  "Banak"                 },
                { "Bardufoss",              "Bardufoss"             },
                { "Bodo",                   "Bodo"                  },
                { "Enontekio",              "Enontekio"             },
                { "Evenes",                 "Evenes"                },
                { "Hosio",                  "Hosio"                 },
                { "Ivalo",                  "Ivalo"                 },
                { "Jokkmokk",               "Jokkmokk"              },
                { "Kalixfors",              "Kalixfors"             },
                { "Kallax",                 "Kallax"                },
                { "Kemi Torino",            "Kemi Torino"           },
                { "Kirkenes",               "Kirkenes"              },
                { "Kiruna",                 "Kiruna"                },
                { "Kittila",                "Kittila"               },
                { "Kuusamo",                "Kuusamo"               },
                { "Monchegorsk",            "Monchegorsk"           },
                { "Murmansk ",              "Murmansk International"},
                { "Murmansk International", "Murmansk International"},
                { "Olenya",                 "Olenya"                },
                { "Rovaniemi",              "Rovaniemi"             },
                { "Severomorsk North",      "Severomorsk-1"         },
                { "Severomorsk One",        "Severomorsk-1"         },
                { "Severomorsk South",      "Severomorsk-3"         },
                { "Severomorsk Three",      "Severomorsk-3"         },
                { "Sodankyla",              "Sodankyla"             },
                { "Vidsel",                 "Vidsel"                },
                { "Vuojarvi",               "Vuojarvi"              },

                // Afghanistan map
                    // South
                { "Bagram",                "Bagram"                 },
                { "Bamyan",                "Bamyan"                 },
                { "Bastion",                "Camp Bastion"          },
                { "Bastion Pads",           "Camp Bastion Heliport" },
                { "Bost",                   "Bost"                  },
                { "Camp Bastion",           "Camp Bastion"          },
                { "Camp Bastion Heliport",  "Camp Bastion Heliport" },
                { "Chaghcharan",            "Chaghcharan"           },
                { "Chapman",               "Khost"                  },
                { "Dwyer",                  "Dwyer"                 },
                { "Farah",                  "Farah"                 },
                { "Gardez",                "Gardez"                 },
                { "Ghazni",                "Ghazni Heliport"        },
                { "Ghazni Heliport",       "Ghazni Heliport"        },
                { "Herat",                  "Herat"                 },
                { "Jalalabad",             "Jalalabad"              },
                { "Kabul",                 "Kabul"                  },
                { "kandahar",               "kandahar"              },
                { "Kandahar Heliport",      "Kandahar Heliport"     },
                { "Kandahar Pads",          "Kandahar Heliport"     },
                     // East
                { "Khost",                 "Khost"                  },
                { "Khost Heliport",        "Khost Heliport"         },
                { "Mary",                  "Mary"                                },
                { "Mary North",            "Mary North"                          },
                { "Maymana",               "Maymana Zahiraddin Faryabi"          },
                { "Maymana Zahiraddin Faryabi", "Maymana Zahiraddin Faryabi"     },
                { "Nimroz",                 "Nimroz"                },
                { "Qala",                   "Qala i Naw"            },
                { "Qala i Naw",             "Qala i Naw"            },
                { "Salerno",               "Khost Heliport"         },
                { "Sharan",                "Sharan"                 },
                { "Sharana",               "Sharan"                 },
                { "Shindand",               "Shindand"              },
                { "Shindand Heliport",      "Shindand Heliport"     },
                { "Shindand Pads",          "Shindand Heliport"     },
                { "Tarinkot",               "Tarinkot"              },
                { "Urgoon Heliport",       "Urgoon Heliport"        },
                { "Urgun",                 "Urgoon Heliport"        },
                { "Yardbird",               "Dwyer"                 },
                
                // Iraq map
                    // North
                { "Al-Asad",                                   "Al-Asad Airbase"                     },
                { "Al-Asad Airbase",                           "Al-Asad Airbase"                     },
                { "Al-Kut",                                    "Al-Kut Airport"                      },
                { "Al-Kut Airport",                            "Al-Kut Airport"                      },
                { "Al-Sahra",                                  "Al-Sahra Airport"                    },
                { "Al-Sahra Airport",                          "Al-Sahra Airport"                    },
                { "Al-Salam",                                  "Al-Salam Airbase"                    },
                { "Al-Salam Airbase",                          "Al-Salam Airbase"                    },
                { "Al-Taji",                                   "Al-Taji Airport"                     },
                { "Al-Taji Airport",                           "Al-Taji Airport"                     },
                { "Al-Taquddum",                               "Al-Taquddum Airport"                 },
                { "Al-Taquddum Airport",                       "Al-Taquddum Airport"                 },
                { "Baghdad ",                                  "Baghdad International Airport"       },
                { "Baghdad International Airport",             "Baghdad International Airport"       },
                { "Balad",                                     "Balad Airbase"                       },
                { "Balad Airbase",                             "Balad Airbase"                       },
                { "Bashur",                                    "Bashur Airport"                      },
                { "Bashur Airport",                            "Bashur Airport"                      },
                { "Erbil",                                     "Erbil International Airport"         },
                { "Erbil International Airport",               "Erbil International Airport"         },
                { "H-2 Airbase",                               "H-2 Airbase"                         },
                { "H-3 Main Airbase",                          "H-3 Main Airbase"                    },
                { "H-3 Northwest Airbase",                     "H-3 Northwest Airbase"               },
                { "H-3 Southwest Airbase",                     "H-3 Southwest Airbase"               },
                { "K1 Base",                                   "K1 Base"                             },
                { "Kay One",                                   "K1 Base"                             },
                { "Kay Rah",                                   "Qayyarah Airfield West"              },
                { "Kirkuk",                                    "Kirkuk International Airport"        },
                { "Kirkuk International Airport",              "Kirkuk International Airport"        },
                { "Mosul",                                     "Mosul International Airport"         },
                { "Mosul International Airport",               "Mosul International Airport"         },
                { "Qayyarah",                                  "Qayyarah Airfield West"              },
                { "Qayyarah Airfield West",                    "Qayyarah Airfield West"              },
                { "Sulaimaniyah",                              "Sulaimaniyah International Airport"  },
                { "Sulaimaniyah International Airport",        "Sulaimaniyah International Airport"  },

                // Germany Cold War
                { "Airracing Frankfurt",                        "Airracing Frankfurt"               }, //TODO Add aliases for US bases
                { "Airracing Koblenz",                          "Airracing Koblenz"                 },
                { "Airracing Lubeck",                           "Airracing Lubeck"                  },
                { "Bad Durkheim",                               "Bad Durkheim"                      },
                { "Bienenfarm",                                 "Bienenfarm"                        },
                { "Dedelow",                                    "Dedelow"                           },
                { "Gardelegen",                                 "Gardelegen"                        },
                { "Gelnhausen",                                 "Gelnhausen"                        },
                { "Glindbruchkippe",                            "Glindbruchkippe"                   },
                { "GrosseWiese",                                "GrosseWiese"                       },
                { "Hasselfelde",                                "Hasselfelde"                       },
                { "Herrenteich",                                "Herrenteich"                       },
                { "Hockenheim",                                 "Hockenheim"                        },
                { "Kammermark",                                 "Kammermark"                        },
                { "Langenselbold",                              "Langenselbold"                     },
                { "Luneburg",                                   "Luneburg"                          },
                { "Albstadt Degerfeld",                         "Albstadt Degerfeld"                },
                { "Ober-Morlen",                                "Ober-Morlen"                       },
                { "Pinnow",                                     "Pinnow"                            },
                { "Pottschutthohe",                             "Pottschutthohe"                    },
                { "Rinteln",                                    "Rinteln"                           },
                { "Uelzen",                                     "Uelzen"                            },
                { "Uetersen",                                   "Uetersen"                          },
                { "Ummern",                                     "Ummern"                            },
                { "Verden-Scharnhorst",                         "Verden-Scharnhorst"                },
                { "Waren_Vielist",                              "Waren_Vielist"                     },
                { "Weser Wumme",                                "Weser Wumme"                       },
                { "Wismar",                                     "Wismar"                            },
                { "Worms",                                      "Worms"                             },
                { "Wadajom",                                    "Wadajom"                           },
                { "Lexija",                                     "Lexija"                            },
                { "Barth",                                      "Barth"                             },
                { "Proima",                                     "Proima"                            },
                { "Bitburg",                                    "Bitburg"                           },
                { "Braunschweig",                               "Braunschweig"                      },
                { "Bremen",                                     "Bremen"                            },
                { "Unrecht",                                    "Unrecht"                           },
                { "Buchel",                                     "Buchel"                            },
                { "Buckeburg",                                  "Buckeburg"                         },
                { "Celle",                                      "Celle"                             },
                { "Sadovij",                                    "Sadovij"                           },
                { "Melodrama",                                  "Melodrama"                         },
                { "Wurzen",                                     "Wurzen"                            },
                { "Fassberg",                                   "Fassberg"                          },
                { "Narsan",                                     "Narsan"                            },
                { "Frankfurt",                                  "Frankfurt"                         },
                { "Fritzlar",                                   "Fritzlar"                          },
                { "Fulda",                                      "Fulda"                             },
                { "Gesetz",                                     "Gesetz"                            },
                { "Gatow",                                      "Gatow"                             },
                { "Giebelstadt",                                "Giebelstadt"                       },
                { "Greif",                                      "Greif"                             },
                { "Gutersloh",                                  "Gutersloh"                         },
                { "Hahn",                                       "Hahn"                              },
                { "Haina",                                      "Haina"                             },
                { "Hamburg",                                    "Hamburg"                           },
                { "Hamburg Finkenwerder",                       "Hamburg Finkenwerder"              },
                { "Hannover",                                   "Hannover"                          },
                { "Hildesheim",                                 "Hildesheim"                        },
                { "Halifax",                                    "Halifax"                           },
                { "Semelni",                                    "Semelni"                           },
                { "Lektorstart",                                "Lektorstart"                       },
                { "Gusar",                                      "Gusar"                             },
                { "Latex",                                      "Latex"                             },
                { "Leipzig Mockau",                             "Leipzig Mockau"                    },
                { "Lubeck",                                     "Lubeck"                            },
                { "Osenniy",                                    "Osenniy"                           },
                { "Sembach",                                    "Sembach"                           },
                { "Mendig",                                     "Mendig"                            },
                { "Muskat",                                     "Muskat"                            },
                { "Defekt",                                     "Defekt"                            },
                { "Gidrostat",                                  "Gidrostat"                         },
                { "Pestrij",                                    "Pestrij"                           },
                { "Klejonka",                                   "Klejonka"                          },
                { "Narcoze",                                    "Narcoze"                           },
                { "Pferdsfeld",                                 "Pferdsfeld"                        },
                { "Ramstein",                                   "Ramstein"                          },
                { "Schonefeld",                                 "Schonefeld"                        },
                { "Schweinfurt",                                "Schweinfurt"                       },
                { "Spangdahlem",                                "Spangdahlem"                       },
                { "Souvenir",                                   "Souvenir"                          },
                { "Kukan",                                      "Kukan"                             },
                { "Tegel",                                      "Tegel"                             },
                { "Tempelhof",                                  "Tempelhof"                         },
                { "Leopard",                                    "Leopard"                           },
                { "Baath",                                      "Baath"                             },
                { "Werneuchen",                                 "Werneuchen"                        },
                { "Wiesbaden",                                  "Wiesbaden"                         },
                { "Gazovij",                                    "Gazovij"                           },
                { "Wunstorf",                                   "Wunstorf"                          },
                { "Zerbst",                                     "Zerbst"                            },
                { "Zweibrucken",                                "Zweibrucken"                       },
                { "Merseburg",                                  "Merseburg"                         },
                { "Leipzig Halle",                              "Leipzig Halle"                     },
                { "Garz",                                       "Garz"                              },

                // farp

                { "Platform",               "platform"              },
                { "FARP",                   "platform"              },
                //{ "Nearest Platform",       "nearestfarp"           },

                // farps (blue)

                { "Berlin",                 "berlin"                },
                { "Dallas",                 "dallas"                },
                { "Dublin",                 "dublin"                },
                { "London",                 "london"                },
                { "Madrid",                 "madrid"                },
                { "Moscow",                 "moscow"                },
                { "Paris",                  "paris"                 },
                { "Perth",                  "perth"                 },
                { "Rome",                   "rome"                  },
                { "Warsaw",                 "warsaw"                },

                // farps (red)

                { "Kaemka",                 "kaemka"                },
                { "Kalitka",                "kalitka"               },
                { "Kapel",                  "kapel"                 },
                { "Otkrytka",               "otkrytka"              },
                { "Podkova",                "podkova"               },
                { "Shpora",                 "shpora"                },
                { "Skala",                  "skala"                 },
                { "Torba",                  "torba"                 },
                { "Vetka",                  "vetka"                 },
                { "Yunga",                  "yunga"                 },

                { "Carrier",                "carrier"                   },
                { "Nearest Carrier",        "nearestcarrier"            },

                { "Admiral Kuznetsov",      "CV 1143.5 Admiral Kuznetsov"   },
                { "Carl Vinson",            "CVN-70 Carl Vinson"            },
                { "Gold Eagle",             "CVN-70 Carl Vinson"            },
                { "Tarawa",                 "LHA-1 Tarawa"                  },
                { "Perry",                  "FFG-7CL Oliver Hazzard Perry"  },
                { "Normandy",               "CG-60 Normandy"                },
                
                // supercarriers
                { "Roosevelt",             "CVN-71 Theodore Roosevelt"      },
                { "Rough Rider",           "CVN-71 Theodore Roosevelt"      },

                { "Lincoln",               "CVN-72 Abraham Lincoln"         },
                { "Union",                 "CVN-72 Abraham Lincoln"         },

                { "Washington",            "CVN-73 George Washington"       },
                { "Warfighter",            "CVN-73 George Washington"       },

                { "Stennis",               "CVN-74 John C. Stennis"         },
                { "Courage",               "CVN-74 John C. Stennis"         },

                { "Truman",                "CVN-75 Harry S. Truman"         },
                { "Lone Warrior",          "CVN-75 Harry S. Truman"         },

                // Non Supercarriers ATC Comms enabled Carriers
                { "Forrestal",             "CV-59 Forrestal"                },
                { "Hand Book",             "CV-59 Forrestal"                },

                //new roles

                { "Cats","nearestcarrier" }, // was ATC
                { "Marshal","nearestcarrier" }, // 
                { "Approach","nearestcarrier" }, // 
                { "LSO", "nearestcarrier" }, //
                { "Paddles", "nearestcarrier" }, //

                // awacs

                { "Awacs",                  "awacs"                 },
                { "Darkstar",               "darkstar"              },
                { "Focus",                  "focus"                 },
                { "Magic",                  "magic"                 },
                { "Overlord",               "overlord"              },
                { "Wizard",                 "wizard"                },
                { "Nearest AWACS",          "nearestawacs"          },

                // tanker

                { "Tanker",                 "tanker"                },
                { "Texaco",                 "texaco"                },
                { "Shell",                  "shell"                 },
                { "Arco",                   "arco"                  },
                { "Ark oh",                 "arco"                  },
                { "Bloodhound",             "Bloodhound"            },
                { "Mauler",                 "Mauler"                },
                { "Navy One",               "Navy One"              },
                { "Nearest Tanker",         "nearesttanker"         },

                // crew

                { "Crew",                   "crew"                   },
                { "Chief",                  "crew"                   },
                { "Sarge",                  "crew"                   },
                { "Ground",                 "crew"                   },
                { "AI Crew",                "aicrew"                 },
                { "AI Crew Page",           "aicrew"                 },

                // AOCS

                { "Crystal Palace",         "aocs"                   },

                // other

                { "Server",                 "aux"                    },
                { "Mystery",                "aux"                    },
                { "Mission",                "aux"                    },
                //{ "Nellis Ground",          "AI_ATC"                 },

                { "Cargo",                  "cargo"                  },
                { "Descent",                "descent"                },

                { "Kneeboard",              "kneeboard"              },
                { "Show Kneeboard",         "kneeboard"              },
            };

        }

    }

}
