
-- Black materials are the same for each MFD
IND_MPD_MATERIAL_BLACK				= "MFD_BLACK"
IND_MPD_1024_MATERIAL_BLACK			= "MFD_1024_BLACK"
IND_MPD_TSD_MATERIAL_BLACK			= "MFD_TSD_BLACK"
IND_MPD_TSD_MATERIAL_BLACK_TR		= "MFD_TSD_BLACK_TRANSPARENT"
IND_MPD_TSD_COMPASS_MATERIAL_BLACK	= "MFD_TSD_COMPASS_BLACK"

-- Non-Black materials are special for each MFD
local MFD_NAMES		= { "PLT_L", "PLT_R", "CPG_L", "CPG_R", "TEDAC" }
local mfd_num		= readParameter("MFD_NUM")
local mat_prefix	= MFD_NAMES[mfd_num + 1]


IND_MPD_MATERIAL_RED				= mat_prefix.."MFD_RED"
IND_MPD_MATERIAL_WHITE				= mat_prefix.."MFD_WHITE"
IND_MPD_MATERIAL_GREEN				= mat_prefix.."MFD_GREEN"
IND_MPD_MATERIAL_DARK_GREEN			= mat_prefix.."MFD_DARK_GREEN"
IND_MPD_MATERIAL_YELLOW				= mat_prefix.."MFD_YELLOW"
IND_MPD_MATERIAL_DARK_YELLOW		= mat_prefix.."MFD_DARK_YELLOW"
IND_MPD_MATERIAL_BLUE				= mat_prefix.."MFD_BLUE"
IND_MPD_MATERIAL_BROWN				= mat_prefix.."MFD_BROWN"

IND_MPD_SOLID_RED					= mat_prefix.."MFD_SOLID_RED"
IND_MPD_SOLID_BLACK					= mat_prefix.."MFD_SOLID_BLACK"
IND_MPD_SOLID_WHITE					= mat_prefix.."MFD_SOLID_WHITE"
IND_MPD_SOLID_GREEN					= mat_prefix.."MFD_SOLID_GREEN"
IND_MPD_SOLID_YELLOW				= mat_prefix.."MFD_SOLID_YELLOW"

IND_MPD_1024_MATERIAL_RED			= mat_prefix.."MFD_1024_RED"
IND_MPD_1024_MATERIAL_WHITE			= mat_prefix.."MFD_1024_WHITE"
IND_MPD_1024_MATERIAL_GREEN			= mat_prefix.."MFD_1024_GREEN"
IND_MPD_1024_MATERIAL_DARK_GREEN	= mat_prefix.."MFD_1024_DARK_GREEN"
IND_MPD_1024_MATERIAL_YELLOW		= mat_prefix.."MFD_1024_YELLOW"
IND_MPD_1024_MATERIAL_BLUE			= mat_prefix.."MFD_1024_BLUE"
IND_MPD_1024_MATERIAL_BROWN			= mat_prefix.."MFD_1024_BROWN"

IND_MPD_WPN_MATERIAL_WHITE			= mat_prefix.."MFD_WPN_WHITE"
IND_MPD_WPN_MATERIAL_GREEN			= mat_prefix.."MFD_WPN_GREEN"
IND_MPD_WPN_MATERIAL_YELLOW			= mat_prefix.."MFD_WPN_YELLOW"
IND_MPD_WPN_MATERIAL_RED			= mat_prefix.."MFD_WPN_RED"

IND_MPD_TSD_SYMBOLS_WHITE			= mat_prefix.."MFD_TSD_WHITE"
IND_MPD_TSD_SYMBOLS_DARK_WHITE		= mat_prefix.."MFD_TSD_DARK_WHITE"
IND_MPD_TSD_SYMBOLS_BLACK_CLR		= mat_prefix.."MFD_TSD_BLACK_CLR"
IND_MPD_TSD_SYMBOLS_YELLOW			= mat_prefix.."MFD_TSD_YELLOW"
IND_MPD_TSD_SYMBOLS_GREEN			= mat_prefix.."MFD_TSD_GREEN"
IND_MPD_TSD_SYMBOLS_CYAN			= mat_prefix.."MFD_TSD_CYAN"
IND_MPD_TSD_COMPASS_GREEN			= mat_prefix.."MFD_TSD_COMPASS_GREEN"
IND_MPD_TSD_COMPASS_RED				= mat_prefix.."MFD_TSD_COMPASS_RED"

IND_MPD_VIDEO_SYMBOLOGY				= mat_prefix.."MFD_VIDEO_SYMBOLOGY"
IND_MPD_VIDEO_SYMBOLOGY_BROWN		= mat_prefix.."MFD_VIDEO_SYMBOLOGY_BROWN"
IND_MPD_VIDEO_SYMBOLOGY_BLUE		= mat_prefix.."MFD_VIDEO_SYMBOLOGY_BLUE"
IND_MPD_VIDEO_SYMBOLOGY_YELLOW		= mat_prefix.."MFD_VIDEO_SYMBOLOGY_YELLOW"
IND_MPD_VIDEO_SYMBOLOGY_WHITE		= mat_prefix.."MFD_VIDEO_SYMBOLOGY_WHITE"	
IND_MPD_VIDEO_SYMBOLOGY_BLACK		= mat_prefix.."MFD_VIDEO_SYMBOLOGY_BLACK"

IND_MPD_FCR_SYMBOLOGY_GREEN		    = mat_prefix.."MFD_TSD_FCR_Symbols_Green"	
IND_MPD_FCR_SYMBOLOGY_YELLOW		= mat_prefix.."MFD_TSD_FCR_Symbols_Yellow"
IND_MPD_FCR_SYMBOLOGY_BLACK		    = mat_prefix.."MFD_TSD_FCR_Symbols_Black"