dofile(LockOn_Options.script_path.."Displays/MFD/indicator/Pages/MISSION/TSD/MPD_TSD_Symbology_defs.lua")
dofile(LockOn_Options.script_path.."Displays/MFD/indicator/MFD_Symbology.lua")


local Menu = {}
Menu = 
{ 
	{ pb.T1, 	"RPT",		nil,							nil},
	{ pb.T2, 	"ASE",		tp_default_border, 				{{"MFD_AsePrevBorder", 0}} },
	{ pb.T4, 	"ABR",		tp_default_border,				nil},
	{ pb.T5, 	"COORD",	nil,							nil},

	{ pb.T6, 	"UTIL",		tp_default_darkgreen_border,	{{"TSD_ABR_Border", 0}}},
	{ pb.T6, 	"UTIL",		nil,							nil},

	{ pb.B1, 	"TSD",		nil,							nil},
	{ pb.B4, 	"BAM",		nil,							nil},
	{ pb.B5, 	"RTE",		nil,							nil},
	
	{ pb.B6, 	"POINT",	tp_default_darkgreen_border,	{{"TSD_ABR_Border", 1}}},
	{ pb.B6, 	"POINT",	nil,							nil},
}

local pos_shift_x = 28
local t4_pocket = pb_props[pb.T4].pos
pb_props[pb.T4].pos[1] = pb_props[pb.T4].pos[1] + pos_shift_x*0.8

createMenu( Menu )

pb_props[pb.T4].pos = t4_pocket


local tp_green						= createTextProperty( 28,  "GREEN",		IND_MPD_MATERIAL_GREEN,		"LeftBottom")
local tp_green_r					= createTextProperty( 28,  "GREEN",		IND_MPD_MATERIAL_GREEN,		"RightBottom")
local tp_yellow						= createTextProperty( 28,  "YELLOW",	IND_MPD_MATERIAL_YELLOW,  	"LeftBottom")
local tp_yellow_r					= createTextProperty( 28,  "YELLOW",	IND_MPD_MATERIAL_YELLOW,  	"RightBottom")
local tp_red						= createTextProperty( 28,  "RED", 		IND_MPD_MATERIAL_RED,  		"LeftBottom")
local tp_red_r						= createTextProperty( 28,  "RED", 		IND_MPD_MATERIAL_RED,  		"RightBottom")
local tp_blue						= createTextProperty( 28,  "BLUE", 		IND_MPD_MATERIAL_BLUE,  	"LeftBottom")
local tp_blue_r						= createTextProperty( 28,  "BLUE", 		IND_MPD_MATERIAL_BLUE,  	"RightBottom")


local tps_wide	= createTextProperty()
local font_size	= tps_wide.height
local group_pos	= {(pb_props[pb.B3].pos[1]+pb_props[pb.B2].pos[1])/2, pb_props[pb.B3].pos[2]+font_size*0.50}
tps_wide.stringdefs = {tps_wide.height*GetScale(),tps_wide.height*GetScale(),tps_wide.height*GetScale()*0.05}	
tps_wide.alignment = "CenterCenter"	

AddRoundCornersWindow("PageName",	{0.0,((pb_props[pb.T1].pos[2]-pb_props[pb.L1].pos[2])/(12/7) + pb_props[pb.L1].pos[2])},
						tp_default.width*15.00, tp_default.height*1.5,
						{
							{"ABBREVIATIONS",		{0.0,	0.0}, tps_wide},			
						},
						tp_default,	IND_MPD_MATERIAL_GREEN,	nil,	nil)

AddPagingGroup("ABR_B2B3", {{"TSD_ABR_Page"}})
						
draw_line( {{0,		368},{0,	-430}},		tp_default.material)
draw_line( {{10,	368},{10,	-430}},		tp_default.material)				
	
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
local Page_1 = addPlaceholder("placeholder_page_1", nil,	nil, {{"TSD_ABR_PageNumber", 0}})

addText( "WAYPOINTS",  				{-450,	 340},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
draw_line( 							{{-450,	 336},	{-450 + tp_green.width*21,	336}},		tp_green.material,									Page_1.name)
addText( "COMM CHECK POINT",  		{-450,	 292},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "LANDING ZONE",  			{-450,	 196},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "PASSAGE POINT",  			{-450,	 100},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "RELEASE POINT",  			{-450,	   4},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "START POINT",  			{-450,	 -92},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "WAYPOINT",  				{-450,	-188},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "HAZARDS",  				{-450,	-284},											tp_yellow,			nil,	nil,	nil,	nil,	Page_1.name)
draw_line( 							{{-450,	-288},	{-450 + tp_yellow.width*21,	-288}},		tp_yellow.material,									Page_1.name)
addText( "TOWER OVER 1000",  		{-450,	-332},											tp_yellow,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "TOWER UNDER 1000",  		{-450, 	-380},											tp_yellow,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "WIRES POWER",  			{40,	 340},											tp_yellow,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "WIRES TELE/ELEC",  		{40,	 292},											tp_yellow,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "GENERAL CTRLM",  			{40,	 196},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
draw_line( 							{{40,	 192},	{40 + tp_green.width*21,	192}},		tp_green.material,									Page_1.name)
addText( "AIR CONTROL POINT",  		{40,	 148},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "AIRFIELD GENERAL",  		{40,	 100},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "AIRFIELD INSTRUM",  		{40,	  52},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "AIRFIELD LIGHTED",  		{40,	   4},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "ARTY FIRE PT 1",  		{40,	 -44},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "ARTY FIRE PT 2",  		{40,	 -92},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "ASSEMBLY AREA",  			{40,	-140},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "BATTALION",  				{40,	-236},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "BATTLE POSITION",  		{40,	-284},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "BRIDGE OR GAP",  			{40,	-332},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "BRIGADE",  				{40,	-380},											tp_green,			nil,	nil,	nil,	nil,	Page_1.name)

addText( "CC",  					{-55,	 292},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "LZ",  					{-55,	 196},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "PP",  					{-55,	 100},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "RP",  					{-55,	   4},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "SP",  					{-55,	 -92},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "WP",  					{-55,	-188},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "TO",  					{-55,	-332},											tp_yellow_r,		nil,	nil,	nil,	nil,	Page_1.name)
addText( "TU",  					{-55, 	-380},											tp_yellow_r,		nil,	nil,	nil,	nil,	Page_1.name)
addText( "WL",  					{435,	 340},											tp_yellow_r,		nil,	nil,	nil,	nil,	Page_1.name)
addText( "WS",  					{435,	 292},											tp_yellow_r,		nil,	nil,	nil,	nil,	Page_1.name)
addText( "AP",  					{435,	 148},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "AG",  					{435,	 100},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "AI",  					{435,	  52},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "AL",  					{435,	   4},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "F1",  					{435,	 -44},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "F2",  					{435,	 -92},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "AA",  					{435,	-140},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "BN",  					{435,	-236},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "BP",  					{435,	-284},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "BR",  					{435,	-332},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)
addText( "BD",  					{435,	-380},											tp_green_r,			nil,	nil,	nil,	nil,	Page_1.name)

-------------------------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
local Page_2 = addPlaceholder("placeholder_page_2", nil,	nil, {{"TSD_ABR_PageNumber", 1}})

addText( "CHECKPOINT",  			{-450,	 340},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "COMPANY",  				{-450,	 292},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "CORPS",  					{-450,	 244},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "DIVISION",  				{-450,	 148},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "FARP FUEL ONLY",  		{-450,	  52},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "FARP AMMO ONLY",  		{-450,	   4},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "FARP FUEL/AMMO",  		{-450,	 -44},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "FORWD ASSEMB AREA",  		{-450,	 -92},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "GRND LITE/SM TOWN",  		{-450,	-188},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "HOLDING AREA",  			{-450,	-284},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "DL SUBSCRIBER",  			{-450, 	-380},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "NBC AREA",  				{40,	 340},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "NDB SYMBOL",  			{40,	 292},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "RAILHEAD POINT",  		{40,	 196},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "REGIMENT/GROUP",  		{40,	 148},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "US ARMY",  				{40,	  52},											tp_green,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "FRIENDLY CTRLM",  		{40,	 -44},											tp_blue,			nil,	nil,	nil,	nil,	Page_2.name)
draw_line( 							{{40,	 -48},	{40 + tp_blue.width*21,	-48}},			tp_blue.material,									Page_2.name)
addText( "ADU FRIENDLY",  			{40,	 -92},											tp_blue,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "AIR ASSAULT FRIEN",  		{40,	-140},											tp_blue,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "AIR CAVALRY FRIEN",  		{40,	-188},											tp_blue,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "AIRBORNE FRIEND",  		{40,	-236},											tp_blue,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "ARMOR FRIEND",  			{40,	-284},											tp_blue,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "ARMOR CAV FRIEND",  		{40,	-332},											tp_blue,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "AV MAINT FRIEND",  		{40,	-380},											tp_blue,			nil,	nil,	nil,	nil,	Page_2.name)

addText( "CP",  					{-55,	 340},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "CO",  					{-55,	 292},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "CR",  					{-55,	 244},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "DI",  					{-55,	 148},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "FF",  					{-55,	  52},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "FM",  					{-55,	   4},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "FC",  					{-55,	 -44},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "FA",  					{-55,	 -92},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "GL",  					{-55,	-188},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "HA",  					{-55,	-284},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "ID",  					{-55, 	-380},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "NB",  					{435,	 340},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "BE",  					{435,	 292},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "RH",  					{435,	 196},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "GP",  					{435,	 148},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "US",  					{435,	  52},											tp_green_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "AD",  					{435,	 -92},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "AS",  					{435,	-140},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "AV",  					{435,	-188},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "AB",  					{435,	-236},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "AM",  					{435,	-284},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "CA",  					{435,	-332},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_2.name)
addText( "MA",  					{435,	-380},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_2.name)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
local Page_3 = addPlaceholder("placeholder_page_3", nil,	nil, {{"TSD_ABR_PageNumber", 2}})

addText( "CHEMICAL FRIEND",  		{-450,	 340},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "DECON FRIEND",  			{-450,	 244},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "ENGINEERS FRIEND",  		{-450,	 148},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "ELEC WAR FRIEND",  		{-450,	 100},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "FIXED WING FRIEND",  		{-450,	   4},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "FIXED ARTY FRIEND",  		{-450,	 -44},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "HELI ATTACK FRIEND",  	{-450,	-140},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "HELI GENRL FRIEND",  		{-450,	-188},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "HOSPITAL FRIEND",  		{-450,	-236},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "INFANTRY FRIEND",  		{-450,	-332},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "MECH INFANTRY FR",  		{40,	 340},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "MEDICAL FRIEND",  		{40,	 292},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "TOC FRIEND",  			{40,	 196},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "UNIT ID FRIEND",  		{40,	 100},											tp_blue,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "ENEMY CTRLM",  			{40,	   4},											tp_red,				nil,	nil,	nil,	nil,	Page_3.name)
draw_line( 							{{40,	   0},	{40 + tp_red.width*21,	0}},			tp_red.material,									Page_3.name)
addText( "AIR ASSAULT ENEMY",  		{40,	 -44},											tp_red,				nil,	nil,	nil,	nil,	Page_3.name)
addText( "AIR CAVALRY ENEMY",  		{40,	 -92},											tp_red,				nil,	nil,	nil,	nil,	Page_3.name)
addText( "AIR DEFENSE ENEMY",  		{40,	-140},											tp_red,				nil,	nil,	nil,	nil,	Page_3.name)
addText( "AIRBORNE ENEMY",  		{40,	-188},											tp_red,				nil,	nil,	nil,	nil,	Page_3.name)
addText( "ARMOR CAV ENEMY",  		{40,	-236},											tp_red,				nil,	nil,	nil,	nil,	Page_3.name)
addText( "ARMOR ENEMY",  			{40,	-284},											tp_red,				nil,	nil,	nil,	nil,	Page_3.name)
addText( "AV MAINT ENEMY",  		{40,	-332},											tp_red,				nil,	nil,	nil,	nil,	Page_3.name)

addText( "CF",  					{-55,	 340},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "DF",  					{-55,	 244},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "EN",  					{-55,	 148},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "FW",  					{-55,	 100},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "WF",  					{-55,	   4},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "FL",  					{-55,	 -44},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "AH",  					{-55,	-140},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "FG",  					{-55,	-188},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "HO",  					{-55,	-236},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "FI",  					{-55,	-332},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "MI",  					{435,	 340},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "MD",  					{435,	 292},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "TF",  					{435,	 196},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "FU",  					{435,	 100},											tp_blue_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "ES",  					{435,	 -44},											tp_red_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "EV",  					{435,	 -92},											tp_red_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "ED",  					{435,	-140},											tp_red_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "EB",  					{435,	-188},											tp_red_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "EC",  					{435,	-236},											tp_red_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "AE",  					{435,	-284},											tp_red_r,			nil,	nil,	nil,	nil,	Page_3.name)
addText( "ME",  					{435,	-332},											tp_red_r,			nil,	nil,	nil,	nil,	Page_3.name)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
local Page_4 = addPlaceholder("placeholder_page_4", nil,	nil, {{"TSD_ABR_PageNumber", 3}})

addText( "CHEMICAL ENEMY",  		{-450,	 340},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "DECON ENEMY",  			{-450,	 244},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "ENGINEERS ENEMY",  		{-450,	 148},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "ELEC WAR ENEMY",  		{-450,	 100},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "FIXED ARTY ENEMY",  		{-450,	   4},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "FIXED WING ENEMY",  		{-450,	 -44},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "HELI ATTACK ENEMY",  		{-450,	-140},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "HELI GENRL ENEMY",  		{-450,	-188},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "HOSPITAL ENEMY",  		{-450,	-236},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "INFANTRY ENEMY",  		{-450,	-332},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "MECH INFANTRY EN",  		{40,	 340},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "MEDICAL ENEMY",  			{40,	 292},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "TOC ENEMY",  				{40,	 196},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "UNIT ID ENEMY", 		 	{40,	 100},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "PREPLANNED TGT/THRT",  	{40,	   4},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
draw_line( 							{{40,	   0},	{40 + tp_red.width*21,	0}},			tp_red.material,									Page_4.name)
addText( "ADU AMX-13",  			{40,	 -44},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "ADU ASPIDE",  			{40,	 -92},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "ADU FRIENDLY",  			{40,	-140},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "ADU GEPARD",  			{40,	-188},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "ADU GROWTH 1",  			{40,	-236},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "ADU GROWTH 2",  			{40,	-284},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "ADU GROWTH 3",  			{40,	-332},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)
addText( "ADU GROWTH 4",  			{40,	-380},											tp_red,				nil,	nil,	nil,	nil,	Page_4.name)

addText( "CE",  					{-55,	 340},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "DE",  					{-55,	 244},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "EE",  					{-55,	 148},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "WR",  					{-55,	 100},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "EF",  					{-55,	   4},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "WE",  					{-55,	 -44},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "EK",  					{-55,	-140},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "HG",  					{-55,	-188},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "EH",  					{-55,	-236},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "EI",  					{-55,	-332},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "EM",  					{435,	 340},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "EX",  					{435,	 292},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "ET",  					{435,	 196},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "EU",  					{435,	 100},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "AX",  					{435,	 -44},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "AS",  					{435,	 -92},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "AD",  					{435,	-140},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "GP",  					{435,	-188},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "G1",  					{435,	-236},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "G2",  					{435,	-284},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "G3",  					{435,	-332},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
addText( "G4",  					{435,	-380},											tp_red_r,			nil,	nil,	nil,	nil,	Page_4.name)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
local Page_5 = addPlaceholder("placeholder_page_5", nil,	nil, {{"TSD_ABR_PageNumber", 4}})

addText( "ADU SPADA",  				{-450,	 340},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "ADU M1983",  				{-450,	 292},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "ADU UNKNOWN",  			{-450,	 244},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "AIR DEF 2S6/SA-19",  		{-450,	 196},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "GUN AIR DEFENSE",  		{-450,	 100},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "GUN GENERIC",  			{-450,	  52},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "GUN MARKSMAN",  			{-450,	   4},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "GUN SABRE",  				{-450,	 -44},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "GUN SELF PROP",  			{-450,	 -92},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "GUN TOWED",  				{-450,	-140},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "GUN ZSU-23",  			{-450,	-188},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "NAVAL SYSTEMS",  			{-450,	-284},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "RADAR BATTL SURV",  		{-450, 	-380},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "RADAR TGT ACQ",  			{40,	 340},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "RBS-70",  				{40,	 292},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "SAM BLOWPIPE",  			{40,	 196},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "SAM BLOODHOUND",  		{40,	 148},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "SAM CHAPPARAL",  			{40,	 100},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "SAM CROTALE",  			{40,	  52},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "SAM CSA-2/1/X",  			{40,	   4},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "SAM HAWK",  				{40,	 -44},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "SAM JAVELIN",  			{40,	 -92},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "SAM PATRIOT",  			{40,	-140},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "SAM REDEYE",  			{40,	-188},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "SAM RAPIER",  			{40,	-236},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "SAM ROLAND",  			{40,	-284},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "SAM SA-1",  				{40,	-332},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)
addText( "SAM SA-2",  				{40,	-380},											tp_red,				nil,	nil,	nil,	nil,	Page_5.name)

addText( "SD",  					{-55,	 340},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "83",  					{-55,	 292},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "U",  						{-55,	 244},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "S6",  					{-55,	 196},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "AA",  					{-55,	 100},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "GU",  					{-55,	  52},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "MK",  					{-55,	   4},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "SB",  					{-55,	 -44},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "GS",  					{-55,	 -92},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "GT",  					{-55,	-140},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "ZU",  					{-55,	-188},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "NV",  					{-55,	-284},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "SR",  					{-55, 	-380},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "TR",  					{435,	 340},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "70",  					{435,	 292},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "BP",  					{435,	 196},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "BH",  					{435,	 148},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "CH",  					{435,	 100},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "CT",  					{435,	  52},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "C2",  					{435,	   4},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "HK",  					{435,	 -44},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "JA",  					{435,	 -92},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "PT",  					{435,	-140},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "RE",  					{435,	-188},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "RA",  					{435,	-236},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "RO",  					{435,	-284},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "1",  						{435,	-332},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
addText( "2",  						{435,	-380},											tp_red_r,			nil,	nil,	nil,	nil,	Page_5.name)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
local Page_6 = addPlaceholder("placeholder_page_6", nil,	nil, {{"TSD_ABR_PageNumber", 5}})

addText( "SAM SA-3",  				{-450,	 340},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-4",  				{-450,	 292},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-5",  				{-450,	 244},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-6",  				{-450,	 196},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-7",  				{-450,	 148},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-8",  				{-450,	 100},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-9",  				{-450,	  52},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-10",  				{-450,	   4},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-11",  				{-450,	 -44},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-12",  				{-450,	 -92},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-13",  				{-450,	-140},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-14",  				{-450,	-188},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-15",  				{-450,	-236},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-16",  				{-450,	-284},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SA-17",  				{-450,	-332},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SAMP",  				{-450, 	-380},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SATCP",  				{40,	 340},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SELF PROP",  			{40,	 292},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM SHAHINE/R440",  		{40,	 244},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM STARSTREAK",  		{40,	 196},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM TIGERCAT",  			{40,	 148},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM STINGER",  			{40,	 100},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM TOWED",  				{40,	  52},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "SAM VULCAN",  			{40,	   4},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "TARGET REF POINT",  		{40,	 -92},											tp_red,				nil,	nil,	nil,	nil,	Page_6.name)
addText( "AIRY",  					{40,	-188},											tp_green,			nil,	nil,	nil,	nil,	Page_6.name)
draw_line( 							{{40,	-192},	{40 + tp_green.width*21,	-192}},		tp_green.material,									Page_6.name)
addText( "ENGLAND SCOTT WALE",  	{40,	-236},											tp_green,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "AUSTRALIAN NATL",  		{40,	-332},											tp_green,			nil,	nil,	nil,	nil,	Page_6.name)
draw_line( 							{{40,	-336},	{40 + tp_green.width*21,	-336}},		tp_green.material,									Page_6.name)
addText( "AUSTRALIAN 66",  			{40,	-380},											tp_green,			nil,	nil,	nil,	nil,	Page_6.name)

addText( "3",  						{-55,	 340},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "4",  						{-55,	 292},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "5",  						{-55,	 244},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "6",  						{-55,	 196},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "7",  						{-55,	 148},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "8",  						{-55,	 100},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "9",  						{-55,	  52},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "10",  					{-55,	   4},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "11",  					{-55,	 -44},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "12",  					{-55,	 -92},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "13",  					{-55,	-140},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "14",  					{-55,	-188},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "15",  					{-55,	-236},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "16",  					{-55,	-284},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "17",  					{-55,	-332},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "SM",  					{-55, 	-380},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "SC",  					{435,	 340},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "SP",  					{435,	 292},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "SH",  					{435,	 244},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "SS",  					{435,	 196},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "TC",  					{435,	 148},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "ST",  					{435,	 100},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "SA",  					{435,	  52},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "VU",  					{435,	   4},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "TG",  					{435,	 -92},											tp_red_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "AIR",  					{435,	-188},											tp_green_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "30",  					{435,	-236},											tp_green_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "AUS",  					{435,	-332},											tp_green_r,			nil,	nil,	nil,	nil,	Page_6.name)
addText( "3",  						{435,	-380},											tp_green_r,			nil,	nil,	nil,	nil,	Page_6.name)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
local Page_7 = addPlaceholder("placeholder_page_7", nil,	nil, {{"TSD_ABR_PageNumber", 6}})

addText( "BESSEL 1841",  			{-450,	 340},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
draw_line( 							{{-450,	 336},	{-450 + tp_green.width*21,	336}},		tp_green.material,									Page_7.name)
addText( "BUKIT RIMPAH INDO",  		{-450,	 292},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "DJARKARTA INDO",  		{-450,	 244},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "GUNUNG SEGARA",  			{-450,	 196},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "TOKYO JAP KOR OKI",  		{-450,	 148},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "TOKYO SPECIAL",  			{-450,	 100},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "CLARK 1880",  			{-450,	   4},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
draw_line( 							{{-450,	   0},	{-450 + tp_green.width*21,	0}},		tp_green.material,									Page_7.name)
addText( "ADINDAN",  				{-450,	 -44},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "ARC 1950",  				{-450,	 -92},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "GHANA",  					{-450,	-140},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "LIBERIA 1964",  			{-450,	-188},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "MERCHICH",  				{-450,	-236},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "MINNA",  					{-450,	-284},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "SIERRA LEONE 1960",  		{-450,	-332},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "CARTHAGE",  				{-450, 	-380},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "CLARK 1866",  			{40,	 340},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
draw_line( 							{{40,	 336},	{40 + tp_green.width*21,	336}},		tp_green.material,									Page_7.name)
addText( "GUAM 1963",  				{40,	 292},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "LUZON",  					{40,	 244},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "NAD 27 CON US",  			{40,	 196},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "NAD 27 ALASKA CAN",  		{40,	 148},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "OID HAWAII MAUI",  		{40,	 100},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "OID HAWAII OAHU",  		{40,	  52},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "OID HAWAII KAUAI",  		{40,	   4},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "LUZON SPECIAL",  			{40,	 -44},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "EVEREST SABAH",  			{40,	-140},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
draw_line( 							{{40,	-144},	{40 + tp_green.width*21,	-144}},		tp_green.material,									Page_7.name)
addText( "TIMBALI E MALAYS",  		{40,	-188},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "EVEREST 1830",  			{40,	-284},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
draw_line( 							{{40,	-288},	{40 + tp_green.width*21,	-288}},		tp_green.material,									Page_7.name)
addText( "INDIAN THAI VIET",  		{40,	-332},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "INDIAN SPECIAL",  		{40,	-380},											tp_green,			nil,	nil,	nil,	nil,	Page_7.name)

addText( "BES",  					{-55,	 340},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "4",  						{-55,	 292},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "6",  						{-55,	 244},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "11",  					{-55,	 196},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "40",  					{-55,	 148},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "44",  					{-55,	 100},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "CL0",  					{-55,	   4},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "1",  						{-55,	 -44},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "2",  						{-55,	 -92},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "9",  						{-55,	-140},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "19",  					{-55,	-188},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "22",  					{-55,	-236},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "24",  					{-55,	-284},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "32",  					{-55,	-332},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "41",  					{-55, 	-380},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "CL6",  					{435,	 340},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "10",  					{435,	 292},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "21",  					{435,	 244},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "25",  					{435,	 196},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "26",  					{435,	 148},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "27",  					{435,	 100},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "28",  					{435,	  52},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "29",  					{435,	   4},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "43",  					{435,	 -44},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "EVB",  					{435,	-140},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "39",  					{435,	-188},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "EVE",  					{435,	-284},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "16",  					{435,	-332},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
addText( "42",  					{435,	-380},											tp_green_r,			nil,	nil,	nil,	nil,	Page_7.name)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
local Page_8 = addPlaceholder("placeholder_page_8", nil,	nil, {{"TSD_ABR_PageNumber", 7}})

addText( "INTERNATIONAL1924",  		{-450,	 340},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
draw_line( 							{{-450,	 336},	{-450 + tp_green.width*21,	 336}},		tp_green.material,									Page_8.name)
addText( "CAMP AREA ASTRO",  		{-450,	 292},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "EUROPEAN 1950",  			{-450,	 244},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "GEODETIC DAT 1949",  		{-450,	 196},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "HERAT NORTH",  			{-450,	 148},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "HJORSEY",  				{-450,	 100},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "HU-TZU-SHAN",  			{-450,	  52},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "QORNOQ",  				{-450,	   4},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "CAMPO I ARGENTINA",  		{-450,	 -44},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "CHUA A PARAGUAY",  		{-450,	 -92},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "CORREGO A BRAZIL",  		{-450,	-140},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "PROV 1956 S AMER",  		{-450,	-188},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "YACARE URAGUAY",  		{-450,	-236},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "TANANARIVE OBSERV",  		{-450,	-284},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "MODIFIED AIRY",  			{40,	 340},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
draw_line( 							{{40,	 336},	{40 + tp_green.width*21,	336}},		tp_green.material,									Page_8.name)
addText( "IRELAND 1965",  			{40,	 292},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "EVEREST 1948",  			{40,	 196},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
draw_line( 							{{40,	 192},	{40 + tp_green.width*21,	192}},		tp_green.material,									Page_8.name)
addText( "KERTAU W MALAYSIA",  		{40,	 148},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "WORLD GEO SYS 72",  		{40,	  52},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
draw_line( 							{{40,	  48},	{40 + tp_green.width*21,	48}},		tp_green.material,									Page_8.name)
addText( "WGS72 SINO-SOVIET",  		{40,	   4},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "WORLD GEO SYS 84",  		{40,	 -92},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
draw_line( 							{{40,	 -96},	{40 + tp_green.width*21,	-96}},		tp_green.material,									Page_8.name)
addText( "GUNUNG SERINDUNG",  		{40,	-140},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "LOCAL ASTRO",  			{40,	-188},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "MONTJONG LOW INDO", 	 	{40,	-236},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "WGS 84 SPECIAL",  		{40,	-284},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "WGS 84 DEFAULT",  		{40,	-332},											tp_green,			nil,	nil,	nil,	nil,	Page_8.name)

addText( "INT",  					{-55,	 340},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "5",  						{-55,	 292},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "7",  						{-55,	 244},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "8",  						{-55,	 196},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "13",  					{-55,	 148},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "14",  					{-55,	 100},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "15",  					{-55,	  52},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "31",  					{-55,	   4},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "33",  					{-55,	 -44},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "34",  					{-55,	 -92},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "35",  					{-55,	-140},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "36",  					{-55,	-188},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "37",  					{-55,	-236},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "38",  					{-55,	-284},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "MAI",  					{435,	 340},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "17",  					{435,	 292},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "MEV",  					{435,	 196},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "18",  					{435,	 148},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "W72",  					{435,	  52},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "46",  					{435,	   4},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "W84",  					{435,	 -92},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "12",  					{435,	-140},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "20",  					{435,	-188},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "23",  					{435,	-236},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "45",  					{435,	-284},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
addText( "47",  					{435,	-332},											tp_green_r,			nil,	nil,	nil,	nil,	Page_8.name)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
