cdata =
{
	AH64D						= _('AH-64D'),
	PEDALS_TRIMMING_METHOD		= _('PEDALS TRIMMER MODE'),
	CYCLIC_TRIMMING_METHOD		= _('CYCLIC TRIMMER MODE'),
	TRIMMING_METHOD_DESCR		= _('Instant Trim (FFB Friendly) - trim sets instantly, suitable option for all joysticks, including FFB\n\nCentral Position Trimmer Mode - trim sets only after joystick axes are returned to center, not suitable for FFB joysticks\n\nJoystick without Springs and FFB - trim sets only new neutral position for autopilot or SAS, no joystick axes neutral effect happens.\nIntended for modified joysticks without springs and FFB'),
	LOCKOUT_DETENT				= _('LOCKOUT DETENT'),
	COCKPIT_SHAKE				= _('COCKPIT CAMERA SHAKE'),
	CPDICT						= _('CUSTOMIZED COCKPIT'),
	default						= _('Default_liv'),
	default_glass_dirt			= _('Default_glass_dirt_liv'),
	ihadss_monocle_visible		= _('IHADSS monocle visible'),
	HMD_EYE						= _('IHADSS render eye'),
	AUTO_HANDOVER				= _('GEORGE AI AUTO HANDOVER'),
	BALACLAVA_PLT				= _('PILOT IN FLAME RESISTANT BALACLAVA'),
	BALACLAVA_CPG				= _('COPILOT/GUNNER IN FLAME RESISTANT BALACLAVA'),
	TRIGGER_GUARD_ENABLE		= _('WEAPONS TRIGGER GUARD ENABLE'),
	AI_IFF_COLOR_SCHEME			= _('AI IFF COLOR SCHEME'),
	AI_INTERFACE_COLOR_SCHEME	= _('AI INTERFACE COLOR SCHEME'),
	AI_SUBTITLES				= _('AI SUBTITLES'),
	MAN_TRK_RAMP_UP_SPEED		= _('MAN TRK "Ramp-Up" Speed'),
	VRS_OPTIONS_LABEL			= _('Game notification about the phenomenon "Vortex ring state" for Main rotor'),
	VRS_OPTION_AUDIO			= _('Audio notification'),
	VRS_OPTION_VISUAL			= _('Visual notification (on controls indicator)'),
}
