PrestonSounds = 
{
	path_pref = "Speech/ENG/AH-64D/",	
	path_pilot = "George_Pilot/",
	path_cpg = "George_CPG/",
	extension = ".ogg",
	
	pilot_sounds = 
	{
		"P_180",
		"P_Aligining",
		"P_Break_Left",
		"P_Break_Right",
		"P_CMWS_Armed",
		"P_CMWS_Auto",
		"P_CMWS_Bypass",
		"P_CMWS_Safed",
		"P_Decreasing_Alt",
		"P_Direct",
		"P_Increase_Alt",
		"P_Left",
		"P_Location",
		"P_Move_Back",
		"P_Move_Forward",
		"P_Right",
		"P_Slide_Left",
		"P_Slide_Right",
		"P_Slow_Down",
		"P_Speed_Up",
		"P_Stopping",
		"P_Coming_Up",
		"P_Coming_Down",
		"P_At_Speed",
		"P_At_Alt",
		"P_At_Course",
		"P_At_Course_Slow",
		"P_No_Takeoff",
		"P_Heavy_Takeoff",
		"P_Heavy_Climb_IGE",
		"P_Heavy_Climb_OGE",
		"P_Speed_VSSE",
		"P_Speed_OGE",
		"P_Landed",
		"P_Cant_Do_That",
		"P_Roger",
		"P_Battery_On",
		"P_Battery_Off",
		"P_Fire_Test_1",
		"P_Fire_Test_2",
		"P_APU_On",
		"P_APU_Off",
		"P_Helmet_Boresight",
		"P_PNVS_Power",
		"P_FCR_Power",
		"P_FCR_Ready",
		"P_RLWR_Power",
		"P_CMWS_Power",
		"P_CMWS_Off",
		"P_Engine_Start_Ready",
		"P_Engine_Start_1",
		"P_Engine_Start_2",
		"P_Engine_Power_FLY",
		"P_Engine_Power_IDLE",
		"P_Engine_Power_OFF",
		"P_Wheelbrakes_On",
		"P_Wheelbrakes_Off",
		"P_Rotorbrake_On",
		"P_Rotorbrake_Off",
		"P_Shutdown",
		"P_Ready_Takeoff",
		"P_Lights_Shutdown",
		"P_Lights_Off",
		"P_Lights_Bright",
		"P_Lights_Dim",
		"P_LIghts_Formation",
	},
	
	cpg_sounds = 
	{
		"burst_10",
		"burst_20",
		"burst_50",
		"burst_100",
		"burst_all",
		"cease_fire",
		"c_range_neg",
		"c_range_closer",
		"deslaving",
		"direct",
		"engaging",
		"good_effects",
		"high",
		"low",
		"m151",
		"m156",
		"m229",
		"m255",
		"m257",
		"m262",
		"m274",
		"m278",
		"m282",
		"quant_1",
		"quant_2",
		"quant_4",
		"quant_8",
		"quant_12",
		"quant_24",
		"quant_all",
		"slaving",
		"target_destroyed",
		"target_stored",
		"was_gun",
		"was_hellfire",
		"was_rockets",
		"lobl",
		"loal",
		"laser_on",
		"laser_off",
		"tracking_target",
		"target_lost",
		"target_in_range",
		"in_range_ready_launch",
		"in_range_ready_shoot",
		"match_and_shoot",
		"de_wased",
		"armed",
		"safed",
		"searching",
		"cant_see",
		"in_sight",
		"copy_roger",
		"cant_do_that",
		"waiting_fcr",
		"taking_tads",
		"next_target",
		"got_target",
		"targets_detected",
		"aircraft_detected",
		"fast_mover_detected",
		"helicopter_detected",
		"ground_detected",
		"naval_detected",
		"tads_power",
		"helmet_boresight",
		"fcr_power",
		"rlwr_power",
		"startup_complete",
		"fcr_ready",
		"shutdown_begin",
		"shutdown_complete",
		"tads_unavailable",
		"cant_engage",
		"standby",
		"constraints",
	},
	
	pilot_files =
	{
		P_180				=	{"P-180"},
		P_Aligining			=	{"P-Aligning"},
		P_Break_Left		=	{"P-Break-Left"},
		P_Break_Right		=	{"P-Break-Right"},
		P_CMWS_Armed		=	{"P-CMWS-Armed"},
		P_CMWS_Auto			=	{"P-CMWS-Auto"},
		P_CMWS_Bypass		=	{"P-CMWS-Bypass"},
		P_CMWS_Safed		=	{"P-CMWS-Safed"},
		P_Decreasing_Alt	=	{"P-Decreasing-Alt"},
		P_Direct			=	{"P-Direct"},
		P_Increase_Alt		=	{"P-Increase-Alt"},
		P_Left				=	{"P-Left"},
		P_Location			=	{"P-Location"},
		P_Move_Back			=	{"P-Move-Back"},
		P_Move_Forward		=	{"P-Move-Forward"},
		P_Right				=	{"P-Right"},
		P_Slide_Left		=	{"P-Slide-Left"},
		P_Slide_Right		=	{"P-Slide-Right"},
		P_Slow_Down			=	{"P-Slow-Down"},
		P_Speed_Up			=	{"P-Speed-Up"},
		P_Stopping			=	{"P-Stopping"},
		P_Coming_Up			=	{"P-Coming-Up"},
		P_Coming_Down		=	{"P-Coming-Down"},
		P_At_Speed			=	{"At requested speed-1", "At requested speed-2", "At requested speed-3"},
		P_At_Alt			=	{"At requested altitude-1", "At requested altitude-2", "At requested altitude-3"},
		P_At_Course			=	{"At requested heading-1", "At requested heading-2", "At requested heading-3", "At requested heading-4"},
		P_At_Course_Slow	= 	{"At requested heading-1", "At requested heading slow-1", "At requested heading slow-2", "At requested heading slow-3"},
		P_No_Takeoff		= 	{"P-no takeoff-1", "P-no takeoff-2", "P-no takeoff-3"},
		P_Heavy_Takeoff		= 	{"P-heavy takeoff-1", "P-heavy takeoff-2", "P-heavy takeoff-3", "P-heavy takeoff-4"},
		P_Heavy_Climb_IGE	= 	{"P-heavy climb IGE-1", "P-heavy climb IGE-2", "P-heavy climb IGE-3", "P-heavy climb IGE-4"},
		P_Heavy_Climb_OGE	= 	{"P-heavy climb OGE-1", "P-heavy climb OGE-2", "P-heavy climb OGE-3", "P-heavy climb OGE-4"},
		P_Speed_VSSE		= 	{"P-speed VSSE-1", "P-speed VSSE-2", "P-speed VSSE-3", "P-speed VSSE-4"},
		P_Speed_OGE			=	{"P-speed OGE-1", "P-speed OGE-2", "P-speed OGE-3", "P-speed OGE-4"},
		P_Landed			= 	{"P-landed-1", "P-landed-2", "P-landed-3", "P-landed-4"},
		P_Cant_Do_That		= 	{"P-cant do that-1", "P-cant do that-2", "P-unable-1", "P-unable-2"},
		P_Roger				=	{"P-copy", "P-roger", "P-wilco"},
		P_Battery_On		=	{"startup/P-battery on-1", "startup/P-battery on-2", "startup/P-battery on-3"},
		P_Battery_Off		=	{"startup/P-battery off-1", "startup/P-battery off-2", "startup/P-battery off-3"},
		P_Fire_Test_1		=	{"startup/P-first fire test-1", "startup/P-first fire test-2", "startup/P-first fire test-3"},
		P_Fire_Test_2		=	{"startup/P-second fire test-1", "startup/P-second fire test-2", "startup/P-second fire test-3"},
		P_APU_On			=	{"startup/P-APU start-1", "startup/P-APU start-2", "startup/P-APU start-3", "startup/P-APU start-4"},
		P_APU_Off			=	{"startup/P-APU off-1", "startup/P-APU off-2", "startup/P-APU off-3"},
		P_Helmet_Boresight	=	{"startup/P-helmet boresight-1", "startup/P-helmet boresight-2", "startup/P-helmet boresight-3", "startup/P-helmet boresight-4"},
		P_PNVS_Power		=	{"startup/P-PNVS power-1", "startup/P-PNVS power-2", "startup/P-PNVS power-3", "startup/P-PNVS power-4"},
		P_FCR_Power			=	{"startup/P-FCR power-1", "startup/P-FCR power-2", "startup/P-FCR power-3", "startup/P-FCR power-4"},
		P_FCR_Ready			=	{"startup/P-FCR ready-1", "startup/P-FCR ready-2", "startup/P-FCR ready-3"},
		P_RLWR_Power		=	{"startup/P-RLWR power-1", "startup/P-RLWR power-2", "startup/P-RLWR power-3", "startup/P-RLWR power-4"},
		P_CMWS_Power		=	{"startup/P-CMWS power-1", "startup/P-CMWS power-2", "startup/P-CMWS power-3", "startup/P-CMWS power-4"},
		P_CMWS_Off			=	{"startup/P-CMWS off"},
		P_Engine_Start_Ready=	{"startup/P-ready engine start-1", "startup/P-ready engine start-2", "startup/P-ready engine start-3"},
		P_Engine_Start_1	=	{"startup/P-first engine start-1", "startup/P-first engine start-2", "startup/P-first engine start-2"},
		P_Engine_Start_2	=	{"startup/P-second engine start-1", "startup/P-second engine start-2", "startup/P-second engine start-3"},
		P_Engine_Power_FLY	=	{"startup/P-engines fly-1", "startup/P-engines fly-2", "startup/P-engines fly-3"},
		P_Engine_Power_IDLE	=	{"startup/P-engines idle-1", "startup/P-engines idle-2", "startup/P-engines idle-3"},
		P_Engine_Power_OFF	=	{"startup/P-engines off-1", "startup/P-engines off-2", "startup/P-engines off-3"},
		P_Wheelbrakes_On	=	{"startup/P-park brake on-1", "startup/P-park brake on-2", "startup/P-park brake on-3"},
		P_Wheelbrakes_Off	=	{"startup/P-park brake off-1", "startup/P-park brake off-2", "startup/P-park brake off-3"},
		P_Rotorbrake_On		=	{"startup/P-rotor brake on-1", "startup/P-rotor brake on-2", "startup/P-rotor brake on-3"},
		P_Rotorbrake_Off	=	{"startup/P-rotor brake off-1", "startup/P-rotor brake off-2", "startup/P-rotor brake off-3"},
		P_Shutdown			=	{"startup/P-shutdown complete-1", "startup/P-shutdown complete-2"},
		P_Ready_Takeoff		=	{"startup/P-ready takeoff-1", "startup/P-ready takeoff-2", "startup/P-ready takeoff-3"},
		P_Lights_Shutdown	=	{"lights/P-lights shutdown-1", "lights/P-lights shutdown-2", "lights/P-lights shutdown-3"},
		P_Lights_Off		=	{"lights/P-lights off-1", "lights/P-lights off-2", "lights/P-lights off-3", "lights/P-lights off-4"},
		P_Lights_Bright		=	{"lights/P-lights bright-1", "lights/P-lights bright-2", "lights/P-lights bright-3"},
		P_Lights_Dim		=	{"lights/P-lights dim-1", "lights/P-lights dim-2", "lights/P-lights dim-3"},
		P_LIghts_Formation	=	{"lights/P-lights formation-1", "lights/P-lights formation-2", "lights/P-lights formation-3"},
	},
	
	cpg_files =
	{
		burst_10				=	{"burst-10", "burst-10-2"},
		burst_20				=	{"burst-20", "burst-20-2"},
		burst_50				=	{"burst-50", "burst-50-2"},
		burst_100				=	{"burst-100", "burst-100-2"},
		burst_all				=	{"burst-all", "burst-all-2"},
		cease_fire				=	{"cease-fire", "cease-fire-2", "cease-fire-3"},
		c_range_neg				=	{"C-Range-1", "C-Range-3"},
		c_range_closer			=	{"C-Range-2"},
		deslaving				=	{"deSlaving", "deSlaving-2", "deSlaving-3"},
		direct					=	{"direct", "direct-2", "direct-3"},
		engaging				=	{"engaging", "engaging-2", "engaging-3", "engaging-4"},
		good_effects			=	{"target-destroyed", "target-destroyed-2", "good-effects", "good-effects-2", "good-effects-3"},
		high					=	{"high", "high-2", "high-3"},
		low						=	{"low", "low-2", "low-3"},
		m151					=	{"m151", "m151-2"},
		m156					=	{"m156", "m156-2"},
		m229					=	{"m229", "m229-2"},
		m255					=	{"m255", "m255-2"},
		m257					=	{"m257"},
		m262					=	{"m262"},
		m274					=	{"m274"},
		m278					=	{"m278"},
		m282					=	{"m282"},
		quant_1					=	{"quant-1", "quant-1-2", "quant-1-2-3"},
		quant_2					=	{"quant-2", "quant-2-2"},
		quant_4					=	{"quant-4", "quant-4-2"},
		quant_8					=	{"quant-8", "quant-8-2"},
		quant_12				=	{"quant-12", "quant-12-2"},
		quant_24				=	{"quant-24", "quant-24-2"},
		quant_all				=	{"quant-all", "quant-all-2"},
		slaving					=	{"Slaving", "Slaving-2", "Slaving-3"},
		target_destroyed		=	{"target-destroyed", "target-destroyed-2", --[["good-effects", "good-effects-2", "good-effects-3"]]},
		target_stored			=	{"Target-Stored", "Target-Stored-2", "Target-Stored-3"},
		was_gun					=	{"WAS-Gun", "WAS-Gun-2"},
		was_hellfire			=	{"WAS-Hellfire", "WAS-Hellfire-2"},
		was_rockets				=	{"WAS-Rockets", "WAS-Rockets-2"},
		lobl					=	{"LOBL", "LOBL-2"},
		loal					=	{"LOAL", "LOAL-2"},
		laser_on				=	{"Laser-on", "Laser-on-2"},
		laser_off				=	{"Laser-off"},
		tracking_target			=	{"acquired", "tracking target"},
		target_lost				=	{"lost", "lost sight", "idk where"},
		target_in_range			=	{"in range", "tgt in range"},
		in_range_ready_launch	=	{"in range ready to launch"},
		in_range_ready_shoot	=	{"in range ready to fire"},
		match_and_shoot			=	{"match and shoot", "match and shoot 2"},
		de_wased				=	{"dewased"},
		armed					=	{"acft armed"},
		safed					=	{"acft safed", "aaaand safed"},
		searching				=	{"scanning with TADS", "scanning", "searching for targets", "searching"},
		cant_see				=	{"no intervisibility", "cant see target"},
		in_sight				=	{"in sight", "i got the target"},
		copy_roger				=	{"copy", "roger"},
		cant_do_that			=	{"unable-1", "unable-2", "cant do that-1", "cant do that-2"},
		waiting_fcr				=	{"waiting FCR scan-1", "waiting FCR scan-2", "waiting FCR scan-3", "waiting FCR scan-4", "waiting FCR scan-5"},
		taking_tads				=	{"i got the TADS", "I have TADS", "taking TADS"},
		next_target				=	{"moving to next", "next tgt", "slewing to next"},
		got_target				=	{"acquired", "i got the target", "in sight"},
		targets_detected		=	{"targets/targets detected-1", "targets/targets detected-2", "targets/targets detected-3", "targets/targets detected-4"},
		aircraft_detected		=	{"targets/aircraft detected-1", "targets/aircraft detected-2", "targets/aircraft detected-3", "targets/aircraft detected-4", "targets/aircraft detected-5"},
		fast_mover_detected		=	{"targets/fast mover detected-1", "targets/fast mover detected-2", "targets/fast mover detected-3", "targets/fast mover detected-4"},
		helicopter_detected		=	{"targets/helicopter detected-1", "targets/helicopter detected-2", "targets/helicopter detected-3", "targets/helicopter detected-4", "targets/helicopter detected-5"},
		ground_detected			=	{"targets/ground detected-1", "targets/ground detected-2", "targets/ground detected-3", "targets/ground detected-4", "targets/ground detected-5"},
		naval_detected			=	{"targets/naval detected-1", "targets/naval detected-2", "targets/naval detected-3", "targets/naval detected-4", "targets/naval detected-5"},
		tads_power				=	{"startup/TADS power-1", "startup/TADS power-2", "startup/TADS power-3", "startup/TADS power-4"},
		helmet_boresight		=	{"startup/helmet boresight-1", "startup/helmet boresight-2", "startup/helmet boresight-3", "startup/helmet boresight-4"},
		fcr_power				=	{"startup/FCR power-1", "startup/FCR power-2", "startup/FCR power-3", "startup/FCR power-4"},
		rlwr_power				=	{"startup/RLWR power-1", "startup/RLWR power-2", "startup/RLWR power-3", "startup/RLWR power-4"},
		startup_complete		=	{"startup/start-up complete"},
		fcr_ready				=	{"startup/FCR ready-1", "startup/FCR ready-2", "startup/FCR ready-3"},
		shutdown_begin			=	{"startup/shutdown begin-1", "startup/shutdown begin-2"},
		shutdown_complete		=	{"startup/shutdown complete-1", "startup/shutdown complete-2"},
		tads_unavailable		=	{"TADS unavailable-1", "TADS unavailable-2", "TADS unavailable-3"},
		cant_engage				=	{"cant engage yet-1", "cant engage yet-2", "cant engage yet-3"},
		standby					=	{"standby"},
		constraints				=	{"constraints-1", "constraints-2", "constraints-3", "constraints-4"},
	},
	
}