-- VAICOM ICAO override table
--
-- Purpose:
--   Provide per-terrain ATC name/callsign -> ICAO designator mappings for ATC unit and METAR output.
--
-- Runtime location expected by DCS Lua:
--   Saved Games\DCS\Scripts\VAICOMPRO\ICAOOverrides.lua
--   (or Saved Games\DCS.openbeta\Scripts\VAICOMPRO\ICAOOverrides.lua)
--
-- Key normalization in runtime lookup:
--   - Uppercase
--   - '_' '-' '/' '.' ',' '(' ')' => spaces
--   - repeated spaces collapsed
--
-- Example:
--   ["caucasus"] = {
--     ["KUTAISI"] = "UGKO",
--     ["SOGD"] = "UGKS",
--   }
--
-- Notes:
--   - Entry values can be either:
--       "ICAO" (legacy)
--       { icao = "ICAO", type = "MIL|CIV|JOINT" }
--   - Only strict 4-letter ICAO values are used.
--   - Invalid/empty values are ignored and fallback logic is used to display a generated ICAO code.
--   - This table may be edited and expanded by users to add missing or correct ICAO codes for their DCS terrains. Although I am good, I may have some wrong codes!

return {
  -- Optional global fallback mappings used for all terrains.
  default = {
    -- ["RAMSTEIN"] = "ETAR",
  },

  -- Germany Cold War terrain
  -- These are historical 1980s identifiers as best as my research can identify.
  germanycw = {
    ["AIRRACING FRANKFURT"] = "EDDF",
    ["AIRRACING KOBLENZ"] = "EDRK",
    ["AIRRACING LUBECK"] = "EDHL",
    ["BAD DURKHEIM"] = "EDRF",
    ["BIENENFARM"] = "EDOI",
    ["DEDELOW"] = "",
    ["GARDELEGEN"] = "EDOC",
    ["GELNHAUSEN"] = "EDFG",
    ["GLINDBRUCHKIPPE"] = "",
    ["GROSSEWIESE"] = "",
    ["HASSELFELDE"] = "",
    ["HERRENTEICH"] = "",
    ["HOCKENHEIM"] = "EDFX",
    ["KAMMERMARK"] = "",
    ["LANGENSELBOLD"] = "",
    ["LUNEBURG"] = "EDHG",
    ["ALBSTADT DEGERFELD"] = "EDSA",
    ["OBER MORLEN"] = "EDFO",
    ["PINNOW"] = "EDCP",
    ["POTTSCHUTTHOHE"] = "",
    ["RINTELN"] = "EDVR",
    ["UELZEN"] = "EDVU",
    ["UETERSEN"] = "EDHE",
    ["UMMERN"] = "",
    ["VERDEN SCHARNHORST"] = "EDWV",
    ["WAREN VIELIST"] = "EDOW",
    ["WESER WUMME"] = "",
    ["WISMAR"] = "EDCW",
    ["WORMS"] = "EDFV",
    ["WADAJOM"] = "",
    ["LEXIJA"] = "",
    ["BARTH"] = "EDBH",
    ["PROIMA"] = "",
    ["BITBURG"] = "EDRB",
    ["BRAUNSCHWEIG"] = "EDVE",
    ["BREMEN"] = "EDDW",
    ["UNRECHT"] = "",
    ["BUCHEL"] = "ETSB",
    ["BUCKEBURG"] = "ETHB",
    ["CELLE"] = "ETHC",
    ["SADOVIJ"] = "",
    ["MELODRAMA"] = "",
    ["WURZEN"] = "",
    ["FASSBERG"] = "ETHS",
    ["NARSAN"] = "",
    ["FRANKFURT"] = "EDDF",
    ["FRITZLAR"] = "ETHF",
    ["FULDA"] = "EDFJ",
    ["GESETZ"] = "",
    ["GATOW"] = "EDBG",
    ["GIEBELSTADT"] = "ETEU",
    ["GREIF"] = "",
    ["GUTERSLOH"] = "ETUO",
    ["HAHN"] = "EDFH",
    ["HAINA"] = "",
    ["HAMBURG"] = "EDDH",
    ["HAMBURG FINKENWERDER"] = "EDHI",
    ["HANNOVER"] = "EDDV",
    ["HILDESHEIM"] = "EDVM",
    ["HALIFAX"] = "",
    ["SEMELNI"] = "",
    ["LEKTORSTART"] = "",
    ["GUSAR"] = "",
    ["LATEX"] = "",
    ["LEIPZIG MOCKAU"] = "",
    ["LUBECK"] = "EDHL",
    ["OSENNIY"] = "",
    ["SEMBACH"] = "ETSE",
    ["MENDIG"] = "EDRE",
    ["MUSKAT"] = "",
    ["DEFEKT"] = "",
    ["GIDROSTAT"] = "",
    ["PESTRIJ"] = "",
    ["KLEJONKA"] = "",
    ["NARCOZE"] = "",
    ["PFERDSFELD"] = "EDRP",
    ["RAMSTEIN"] = "ETAR",
    ["SCHONEFELD"] = "EDDB",
    ["SCHWEINFURT"] = "EDFB",
    ["SPANGDAHLEM"] = "ETAD",
    ["SOUVENIR"] = "",
    ["KUKAN"] = "",
    ["TEGEL"] = "EDDT",
    ["TEMPELHOF"] = "EDDI",
    ["LEOPARD"] = "",
    ["BAATH"] = "",
    ["WERNEUCHEN"] = "EDBW",
    ["WIESBADEN"] = "ETOU",
    ["GAZOVIJ"] = "",
    ["WUNSTORF"] = "ETNW",
    ["ZERBST"] = "EDUZ",
    ["ZWEIBRUCKEN"] = "EDRZ",
    ["MERSEBURG"] = "EDBM",
    ["LEIPZIG HALLE"] = "EDDP",
    ["GARZ"] = "EDCG",
  },

  -- Other terrains are modern day ICAO identifiers.
  caucasus = {
    ["ANAPA VITYAZEVO"] = "URKA",
    ["BATUMI"] = "UGSB",
    ["BESLAN"] = "URMO",
    ["GELENDZHIK"] = "URKG",
    ["GUDAUTA"] = "",
    ["MAYKOP KHANSKAYA"] = "URKH",
    ["KOBULETI"] = "",
    ["SENAKI KOLKHI"] = "",
    ["KRASNODAR CENTER"] = "",
    ["KRYMSK"] = "URKW",
    ["KUTAISI"] = "UGKO",
    ["TBILISI LOCHINI"] = "UGTB",
    ["MINERALNYE VODY"] = "URMM",
    ["MOZDOK"] = "",
    ["NALCHIK"] = "URMN",
    ["NOVOROSSIYSK"] = "",
    ["KRASNODAR PASHKOVSKY"] = "URKK",
    ["SOCHI ADLER"] = "URSS",
    ["SOGANLUG"] = "",
    ["SUKHUMI BABUSHARA"] = "UGSS",
    ["VAZIANI"] = "",
  },
  persiangulf = {
    ["AL MAKTOUM INTL"] = "OMDW",
    ["AL MINHAD AFB"] = "OMDM",
    ["DUBAI INTL"] = "OMDB",
    ["SHARJAH INTL"] = "OMSJ",
    ["ABU MUSA ISLAND"] = "OIBA",
    ["SIRRI ISLAND"] = "OIBS",
    ["FUJAIRAH INTL"] = "OMFJ",
    ["BANDAR LENGEH"] = "OIBL",
    ["KHASAB"] = "OOKS",
    ["QESHM ISLAND"] = "OIKQ",
    ["HAVADARYA"] = "",
    ["BANDAR ABBAS INTL"] = "OIKB",
    ["LAR"] = "OISL",
    ["KERMAN"] = "OIKK",
    ["SHIRAZ INTL"] = "OISS",
    ["AL DHAFRA AFB"] = "OMAM",
    ["AL BATEEN"] = "OMAD",
    ["KISH INTL"] = "OIBK",
    ["LAVAN ISLAND"] = "OIBV",
    ["AL AIN INTL"] = "OMAL",
    ["BANDAR E JASK"] = "",
    ["ABU DHABI INTL"] = "OMAA",
    ["SAS AL NAKHEEL"] = "",
    ["JIROFT"] = "OIKJ",
    ["LIWA AFB"] = "OMLW",
    ["RAS AL KHAIMAH INTL"] = "OMRK",
    ["SIR ABU NUAYR"] = "",
  },
  syria = {
    ["BEIRUT RAFIC HARIRI"] = { icao = "OLBA", type = "CIV" },
    ["RAYAK"] = { icao = "OLRA", type = "MIL" },
    ["WUJAH AL HAJAR"] = "",
    ["KIRYAT SHMONA"] = { icao = "LLKS", type = "CIV" },
    ["MEZZEH"] = "",
    ["QABR AS SITT"] = "",
    ["RENE MOUAWAD"] = { icao = "OLKA", type = "CIV" },
    ["MARJ AS SULTAN NORTH"] = "",
    ["MARJ AS SULTAN SOUTH"] = "",
    ["MARJ RUHAYYIL"] = "",
    ["AL DUMAYR"] = "",
    ["HAIFA"] = { icao = "LLHA", type = "CIV" },
    ["AN NASIRIYAH"] = "",
    ["AL QUSAYR"] = "",
    ["KHALKHALAH"] = "",
    ["RAMAT DAVID"] = { icao = "LLRD", type = "MIL" },
    ["MEGIDDO"] = { icao = "LLMG", type = "CIV" },
    ["EYN SHEMER"] = { icao = "LLXS", type = "CIV" },
    ["BASSEL AL ASSAD"] = { icao = "OSLK", type = "CIV" },
    ["ABU AL DUHUR"] = "",
    ["TAFTANAZ"] = "",
    ["HATAY"] = { icao = "LTDA", type = "CIV" },
    ["KUWEIRES"] = "",
    ["MINAKH"] = "",
    ["JIRAH"] = "",
    ["ADANA SAKIRPASA"] = { icao = "LTAF", type = "CIV" },
    ["INCIRLIK"] = { icao = "LTAG", type = "MIL" },
    ["DAMASCUS"] = { icao = "OSDI", type = "CIV" },
    ["THA LAH"] = "",
    ["LARNACA"] = { icao = "LCLK", type = "CIV" },
    ["AKROTIRI"] = { icao = "LCRA", type = "MIL" },
    ["KING HUSSEIN AIR COLLEGE"] = { icao = "OJMF", type = "MIL" },
    ["AT TANF"] = "",
    ["H3"] = "",
    ["H3 NORTHWEST"] = "",
    ["H3 SOUTHWEST"] = "",
    ["H4"] = "",
    ["PAPHOS"] = { icao = "LCPH", type = "CIV" },
    ["LAKATAMIA"] = { icao = "LCLM", type = "CIV" },
    ["ERCAN"] = { icao = "LCEN", type = "CIV" },
    ["MUWAFFAQ SALTI"] = { icao = "OJMS", type = "MIL" },
    ["KING ABDULLAH II"] = { icao = "OJMF", type = "MIL" },
    ["MARKA"] = { icao = "OJAM", type = "CIV" },
    ["HERZLIYA"] = { icao = "LLHZ", type = "CIV" },
    ["PRINCE HASSAN"] = { icao = "OJHF", type = "MIL" },
  },
  nevada = {
    ["CREECH"] = { icao = "KINS", type = "MIL" },
    ["HENDERSON EXECUTIVE"] = { icao = "KHND", type = "CIV" },
    ["MCCARRAN INTERNATIONAL"] = { icao = "KLAS", type = "CIV" },
    ["LAUGHLIN"] = { icao = "KIFP", type = "CIV" },
    ["NORTH LAS VEGAS"] = { icao = "KVGT", type = "CIV" },
    ["TONOPAH TEST RANGE"] = { icao = "KTNX", type = "MIL" },
    ["GROOM LAKE"] = { icao = "KXTA", type = "MIL" },
    ["NELLIS"] = { icao = "KLSV", type = "MIL" },
    ["BOULDER CITY"] = { icao = "KBVU", type = "CIV" },
  },
  marianas = {
    ["ANDERSEN AFB"] = "PGUA",
    ["ANTONIO B WON PAT INTL"] = "PGUM",
    ["ROTA INTL"] = "PGRO",
    ["TINIAN INTL"] = "PGTT",
    ["SAIPAN INTL"] = "PGSN",
    ["PAGAN"] = { icao = "TT01", type = "CIV" },
    ["MARPI"] = "",
    ["KAGMAN"] = "",
    ["CHARON KANOA"] = "",
    ["ISLEY"] = "",
    ["USHI"] = "",
    ["AIRFIELD 3"] = "",
    ["GURGUAN POINT"] = "",
    ["ROTA"] = "PGRO",
    ["AGANA"] = "PGUM",
    ["OROTE"] = "",
  },
  thechannel = {
    ["DUNKIRK MARDYCK"] = "",
    ["HAWKINGE"] = "EGHK",
    ["SAINT OMER LONGUENESSE"] = "LFQN",
    ["MERVILLE CALONNE"] = "LFQT",
    ["HIGH HALDEN"] = "",
    ["DETLING"] = "",
    ["ABBEVILLE DRUCAT"] = "LFOI",
    ["LYMPNE"] = "",
    ["MANSTON"] = "EGMH",
  },
  normandy = {
    ["BENY SUR MER"] = "",
    ["SAINTE CROIX SUR MER"] = "",
    ["LANTHEUIL"] = "",
    ["BAZENVILLE"] = "",
    ["SOMMERVIEU"] = "",
    ["LONGUES SUR MER"] = "",
    ["LE MOLAY"] = "",
    ["SAINTE LAURENT SUR MER"] = "",
    ["SAINT PIERRE DU MONT"] = "",
    ["DEUX JUMEAUX"] = "",
    ["CHIPPELLE"] = "",
    ["CRICQUEVILLE EN BESSIN"] = "",
    ["CARDONVILLE"] = "",
    ["BRUCHEVILLE"] = "",
    ["MEAUTIS"] = "",
    ["AZEVILLE"] = "",
    ["CRETTEVILLE"] = "",
    ["PICAUVILLE"] = "",
    ["BINIVILLE"] = "",
    ["LESSAY"] = "",
    ["MAUPERTUS"] = "LFRC",
    ["EVREUX"] = "LFOE",
    ["FORDE"] = "",
    ["TANGMERE"] = "",
    ["FUNTINGTON"] = "",
    ["CHAILEY"] = "",
    ["NEEDS OAR POINT"] = "",
  },
  sinai = {
    ["AL MANSURAH"] = "",
    ["AZZAQAZIQ"] = "",
    ["AS SALIHIYAH"] = "",
    ["BILBEIS AIR BASE"] = "",
    ["INSHAS AIRBASE"] = "",
    ["ABU SUWAYR"] = "",
    ["AL ISMAILIYAH"] = "",
    ["CAIRO INTERNATIONAL AIRPORT"] = { icao = "HECA", type = "CIV" },
    ["DIFARSUWAR AIRFIELD"] = "",
    ["WADI AL JANDALI"] = "",
    ["FAYED"] = "",
    ["BALUZA"] = "",
    ["CAIRO WEST"] = { icao = "HECW", type = "MIL" },
    ["KIBRIT AIR BASE"] = "",
    ["MELEZ"] = "",
    ["BIR HASANAH"] = "",
    ["EL ARISH"] = { icao = "HEAR", type = "CIV" },
    ["EL GORA"] = { icao = "HEGR", type = "MIL" },
    ["ABU RUDEIS"] = "",
    ["KEDEM"] = "",
    ["RAMON AIRBASE"] = { icao = "LLRM", type = "MIL" },
    ["HATZERIM"] = { icao = "LLHB", type = "MIL" },
    ["HATZOR"] = { icao = "LLHS", type = "MIL" },
    ["PALMACHIM"] = { icao = "LLRM", type = "MIL" },
    ["TEL NOF"] = { icao = "LLRN", type = "MIL" },
    ["NEVATIM"] = { icao = "LLNV", type = "MIL" },
    ["SDE DOV"] = { icao = "LLSD", type = "CIV" },
    ["BEN GURION"] = { icao = "LLBG", type = "CIV" },
    ["OVDA"] = { icao = "LLOV", type = "CIV" },
    ["ST CATHERINE"] = { icao = "HESC", type = "CIV" },
    ["WADI ABU RISH"] = "",
    ["RAMON INTERNATIONAL AIRPORT"] = { icao = "LLER", type = "CIV" },
    ["SHARM EL SHEIKH INTERNATIONAL AIRPORT"] = { icao = "HESH", type = "CIV" },
    ["HURGHADA INTERNATIONAL AIRPORT"] = { icao = "HEGN", type = "CIV" },
    ["AL BAHR AL AHMAR"] = "",
    ["EL MINYA"] = "",
    ["BENI SUEF"] = { icao = "HEBS", type = "MIL" },
    ["KOM AWSHIM"] = "",
    ["QUWAYSINA"] = "",
    ["BIRMA AIR BASE"] = { icao = "HE16", type = "MIL" },
    ["GEBEL EL BASUR AIR BASE"] = "",
    ["AL RAHMANIYAH AIR BASE"] = "",
    ["JIYANKLIS AIR BASE"] = { icao = "HEGS", type = "MIL" },
    ["BORJ EL ARAB INTERNATIONAL AIRPORT"] = { icao = "HEBR", type = "CIV" },
  },
  southatlantic = {
    ["MOUNT PLEASANT"] = { icao = "EGYP", type = "CIV" },
    ["GOOSE GREEN"] = "",
    ["SAN CARLOS FOB"] = "",
    ["PORT STANLEY"] = { icao = "SFAL", type = "CIV" },
    ["AERODROMO DE TOLHUIN"] = { icao = "SAWL", type = "CIV" },
    ["RIO GRANDE"] = { icao = "SAWE", type = "CIV" },
    ["PUERTO WILLIAMS"] = { icao = "SCGZ", type = "CIV" },
    ["SAN JULIAN"] = { icao = "SAWS", type = "CIV" },
    ["USHUAIA HELO PORT"] = "",
    ["USHUAIA"] = { icao = "SAWH", type = "CIV" },
    ["PAMPA GUANACO"] = "",
    ["PUERTO SANTA CRUZ"] = { icao = "SAWU", type = "CIV" },
    ["RIO CHICO"] = "",
    ["RIO GALLEGOS"] = { icao = "SAWG", type = "CIV" },
    ["FRANCO BIANCO"] = "",
    ["COMANDANTE LUIS PIEDRABUENA"] = { icao = "SAWJ", type = "CIV" },
    ["PORVENIR AIRFIELD"] = "",
    ["PUNTA ARENAS"] = { icao = "SCCI", type = "CIV" },
    ["AEROPUERTO DE GOBERNADOR GREGORES"] = { icao = "SAWR", type = "CIV" },
    ["RIO TURBIO"] = "",
    ["EL CALAFATE"] = { icao = "SAWC", type = "CIV" },
    ["PUERTO NATALES"] = { icao = "SCNT", type = "CIV" },
    ["AERODROMO O HIGGINS"] = "",
  },
  kola = {
    ["ANDOYA"] = { icao = "ENAN", type = "CIV" },
    ["BODO"] = { icao = "ENBO", type = "CIV" },
    ["BARDUFOSS"] = { icao = "ENDU", type = "CIV" },
    ["EVENES"] = { icao = "ENEV", type = "CIV" },
    ["ALTA"] = { icao = "ENAT", type = "CIV" },
    ["BANAK"] = { icao = "ENNA", type = "CIV" },
    ["ENONTEKIO"] = { icao = "EFET", type = "CIV" },
    ["KIRUNA"] = { icao = "ESNQ", type = "CIV" },
    ["KALIXFORS"] = { icao = "ESUK", type = "CIV" },
    ["JOKKMOKK"] = { icao = "ESNJ", type = "CIV" },
    ["VIDSEL"] = { icao = "ESPE", type = "MIL" },
    ["KALLAX"] = { icao = "ESPA", type = "CIV" },
    ["KEMI TORINO"] = { icao = "EFKM", type = "CIV" },
    ["HOSIO"] = "",
    ["ROVANIEMI"] = { icao = "EFRO", type = "CIV" },
    ["VUOJARVI"] = "",
    ["SODANKYLA"] = { icao = "EFSO", type = "CIV" },
    ["KITTILA"] = { icao = "EFKT", type = "CIV" },
    ["IVALO"] = { icao = "EFIV", type = "CIV" },
    ["KIRKENES"] = { icao = "ENKR", type = "CIV" },
    ["SEVEROMORSK 1"] = { icao = "ULAK", type = "MIL" },
    ["SEVEROMORSK 3"] = { icao = "XLMV", type = "MIL" },
    ["MURMANSK INTERNATIONAL"] = { icao = "ULMM", type = "CIV" },
    ["OLENYA"] = { icao = "ULOR", type = "MIL" },
    ["MONCHEGORSK"] = { icao = "ULMB", type = "MIL" },
    ["ALAKURTTI"] = "",
    ["KUUSAMO"] = { icao = "EFKS", type = "CIV" },
  },
  afghanistan = {
    ["TARINKOT"] = "OATN",
    ["KANDAHAR"] = "OAKN",
    ["KANDAHAR HELIPORT"] = "",
    ["CHAGHCHARAN"] = "OACC",
    ["BOST"] = { icao = "OABT", type = "CIV" },
    ["DWYER"] = "",
    ["CAMP BASTION"] = { icao = "OAZI", type = "MIL" },
    ["CAMP BASTION HELIPORT"] = "",
    ["QALA I NAW"] = "OAQN",
    ["HERAT"] = "OAHR",
    ["SHINDAND"] = "OAHN",
    ["SHINDAND HELIPORT"] = "",
    ["FARAH"] = "OAFR",
    ["NIMROZ"] = "",
    ["BAGRAM"] = "OAIX",
    ["BAMYAN"] = "OABN",
    ["GHAZNI HELIPORT"] = "",
    ["GARDEZ"] = "",
    ["JALALABAD"] = "OAJL",
    ["KABUL"] = "OAKB",
    ["KHOST"] = "OAKS",
    ["KHOST HELIPORT"] = "",
    ["SHARAN"] = { icao = "OASA", type = "CIV" },
    ["URGOON HELIPORT"] = "",
    ["MAYMANA ZAHIRADDIN FARYABI"] = "OAMN",
    ["MARY"] = "",
    ["MARY NORTH"] = "",
  },
  iraq = {
    ["AL ASAD AIRBASE"] = { icao = "ORAA", type = "MIL" },
    ["AL SAHRA AIRPORT"] = { icao = "ORSH", type = "MIL" },
    ["AL SALAM AIRBASE"] = "",
    ["AL TAJI AIRPORT"] = { icao = "ORTI", type = "MIL" },
    ["AL TAQUDDUM AIRPORT"] = { icao = "ORAT", type = "MIL" },
    ["BAGHDAD INTERNATIONAL AIRPORT"] = "ORBI",
    ["BALAD AIRBASE"] = { icao = "ORBD", type = "MIL" },
    ["BASHUR AIRPORT"] = { icao = "ORBR", type = "MIL" },
    ["ERBIL INTERNATIONAL AIRPORT"] = "ORER",
    ["K1 BASE"] = "",
    ["KIRKUK INTERNATIONAL AIRPORT"] = "ORKK",
    ["QAYYARAH AIRFIELD WEST"] = "ORQW",
    ["SULAIMANIYAH INTERNATIONAL AIRPORT"] = "ORSU",
  },
}
