-- VAICOM ICAO override table
--
-- Purpose:
--   Provide per-terrain ATC name/callsign -> ICAO designator mappings for ATC unit and METAR output.
--
-- Runtime location expected by DCS Lua:
--   Saved Games\DCS\Scripts\VAICOMPRO\ICAOOverrides.lua
--   (or Saved Games\DCS.openbeta\Scripts\VAICOMPRO\ICAOOverrides.lua)
--
-- Key normalization in runtime lookup:
--   - Uppercase
--   - '_' '-' '/' '.' ',' '(' ')' => spaces
--   - repeated spaces collapsed
--
-- Example:
--   ["caucasus"] = {
--     ["KUTAISI"] = "UGKO",
--     ["SOGD"] = "UGKS",
--   }
--
-- Notes:
--   - Entry values can be either:
--       "ICAO" or "IATA" (legacy)
--       { icao = "ICAO", iata = "IATA", type = "MIL|CIV|JOINT" }
--   - Strict 4-character ICAO-like values (A-Z / 0-9) are preferred.
--   - If no ICAO is available, strict 3-letter IATA values can be used.
--   - Invalid/empty values are ignored and fallback logic is used to display a generated ICAO code.
--   - This table may be edited and expanded by users to add missing or correct ICAO codes for their DCS terrains. Although I am good, I may have some wrong codes!

return {
  -- Optional global fallback mappings used for all terrains.
  default = {
    -- ["RAMSTEIN"] = "ETAR",
  },

  -- Germany Cold War terrain
  -- These are historical 1980s identifiers as best as my research can identify.
  germanycw = {
    ["AIRRACING FRANKFURT"] = { icao = "EDDF" },
    ["AIRRACING KOBLENZ"] = { icao = "EDRK" },
    ["AIRRACING LUBECK"] = { icao = "EDHL" },
    ["BAD DURKHEIM"] = { icao = "EDRF" },
    ["BIENENFARM"] = { icao = "EDOI" },
    ["DEDELOW"] = { icao = "", iata = "", type = "" },
    ["GARDELEGEN"] = { icao = "EDOC" },
    ["GELNHAUSEN"] = { icao = "EDFG" },
    ["GLINDBRUCHKIPPE"] = { icao = "", iata = "", type = "" },
    ["GROSSEWIESE"] = { icao = "", iata = "", type = "" },
    ["HASSELFELDE"] = { icao = "", iata = "", type = "" },
    ["HERRENTEICH"] = { icao = "", iata = "", type = "" },
    ["HOCKENHEIM"] = { icao = "EDFX" },
    ["KAMMERMARK"] = { icao = "", iata = "", type = "" },
    ["LANGENSELBOLD"] = { icao = "", iata = "", type = "" },
    ["LUNEBURG"] = { icao = "EDHG" },
    ["ALBSTADT DEGERFELD"] = { icao = "EDSA" },
    ["OBER MORLEN"] = { icao = "EDFO" },
    ["PINNOW"] = { icao = "EDCP" },
    ["POTTSCHUTTHOHE"] = { icao = "", iata = "", type = "" },
    ["RINTELN"] = { icao = "EDVR" },
    ["UELZEN"] = { icao = "EDVU" },
    ["UETERSEN"] = { icao = "EDHE" },
    ["UMMERN"] = { icao = "", iata = "", type = "" },
    ["VERDEN SCHARNHORST"] = { icao = "EDWV" },
    ["WAREN VIELIST"] = { icao = "EDOW" },
    ["WESER WUMME"] = { icao = "", iata = "", type = "" },
    ["WISMAR"] = { icao = "EDCW" },
    ["WORMS"] = { icao = "EDFV" },
    ["WADAJOM"] = { icao = "", iata = "", type = "" },
    ["LEXIJA"] = { icao = "", iata = "", type = "" },
    ["BARTH"] = { icao = "EDBH" },
    ["PROIMA"] = { icao = "", iata = "", type = "" },
    ["BITBURG"] = { icao = "EDRB", iata = "", type = "MIL" },
    ["BRAUNSCHWEIG"] = { icao = "EDVE" },
    ["BREMEN"] = { icao = "EDDW" },
    ["UNRECHT"] = { icao = "", iata = "", type = "" },
    ["BUCHEL"] = { icao = "ETSB", iata = "", type = "MIL" },
    ["BUCKEBURG"] = { icao = "ETHB", iata = "", type = "MIL" },
    ["CELLE"] = { icao = "ETHC", iata = "", type = "MIL" },
    ["SADOVIJ"] = { icao = "", iata = "", type = "" },
    ["MELODRAMA"] = { icao = "", iata = "", type = "" },
    ["WURZEN"] = { icao = "", iata = "", type = "" },
    ["FASSBERG"] = { icao = "ETHS", iata = "", type = "MIL" },
    ["NARSAN"] = { icao = "", iata = "", type = "" },
    ["FRANKFURT"] = { icao = "EDDF" },
    ["FRITZLAR"] = { icao = "ETHF", iata = "", type = "MIL" },
    ["FULDA"] = { icao = "EDFJ" },
    ["GESETZ"] = { icao = "", iata = "", type = "" },
    ["GATOW"] = { icao = "EDBG", iata = "", type = "MIL" },
    ["GIEBELSTADT"] = { icao = "ETEU", iata = "", type = "MIL" },
    ["GREIF"] = { icao = "", iata = "", type = "" },
    ["GUTERSLOH"] = { icao = "ETUO", iata = "", type = "MIL" },
    ["HAHN"] = { icao = "EDFH" },
    ["HAINA"] = { icao = "", iata = "", type = "" },
    ["HAMBURG"] = { icao = "EDDH" },
    ["HAMBURG FINKENWERDER"] = { icao = "EDHI" },
    ["HANNOVER"] = { icao = "EDDV" },
    ["HILDESHEIM"] = { icao = "EDVM" },
    ["HALIFAX"] = { icao = "", iata = "", type = "" },
    ["SEMELNI"] = { icao = "", iata = "", type = "" },
    ["LEKTORSTART"] = { icao = "", iata = "", type = "" },
    ["GUSAR"] = { icao = "", iata = "", type = "" },
    ["LATEX"] = { icao = "", iata = "", type = "" },
    ["LEIPZIG MOCKAU"] = { icao = "", iata = "", type = "" },
    ["LUBECK"] = { icao = "EDHL" },
    ["OSENNIY"] = { icao = "", iata = "", type = "" },
    ["SEMBACH"] = { icao = "ETSE", iata = "", type = "MIL" },
    ["MENDIG"] = { icao = "EDRE" },
    ["MUSKAT"] = { icao = "", iata = "", type = "" },
    ["DEFEKT"] = { icao = "", iata = "", type = "" },
    ["GIDROSTAT"] = { icao = "", iata = "", type = "" },
    ["PESTRIJ"] = { icao = "", iata = "", type = "" },
    ["KLEJONKA"] = { icao = "", iata = "", type = "" },
    ["NARCOZE"] = { icao = "", iata = "", type = "" },
    ["PFERDSFELD"] = { icao = "EDRP", iata = "", type = "MIL" },
    ["RAMSTEIN"] = { icao = "ETAR", iata = "", type = "MIL" },
    ["SCHONEFELD"] = { icao = "EDDB" },
    ["SCHWEINFURT"] = { icao = "EDFB" },
    ["SPANGDAHLEM"] = { icao = "ETAD", iata = "", type = "MIL" },
    ["SOUVENIR"] = { icao = "", iata = "", type = "" },
    ["KUKAN"] = { icao = "", iata = "", type = "" },
    ["TEGEL"] = { icao = "EDDT" },
    ["TEMPELHOF"] = { icao = "EDDI" },
    ["LEOPARD"] = { icao = "", iata = "", type = "" },
    ["BAATH"] = { icao = "", iata = "", type = "" },
    ["WERNEUCHEN"] = { icao = "EDBW" },
    ["WIESBADEN"] = { icao = "ETOU", iata = "", type = "MIL" },
    ["GAZOVIJ"] = { icao = "", iata = "", type = "" },
    ["WUNSTORF"] = { icao = "ETNW", iata = "", type = "MIL" },
    ["ZERBST"] = { icao = "EDUZ" },
    ["ZWEIBRUCKEN"] = { icao = "EDRZ" },
    ["MERSEBURG"] = { icao = "EDBM" },
    ["LEIPZIG HALLE"] = { icao = "EDDP" },
    ["GARZ"] = { icao = "EDCG" },
  },

  -- Other terrains are modern day ICAO identifiers.
  caucasus = {
    ["ANAPA VITYAZEVO"] = { icao = "URKA", iata = "AAQ", type = "CIV" },
    ["BATUMI"] = { icao = "UGSB", iata = "BUS", type = "CIV" },
    ["BESLAN"] = { icao = "URMO", iata = "OGZ", type = "CIV" },
    ["GELENDZHIK"] = { icao = "URKG", iata = "GDZ", type = "CIV" },
    ["GUDAUTA"] = { icao = "UGSG", iata = "", type = "MIL" },
    ["MAYKOP KHANSKAYA"] = { icao = "URKH", iata = "", type = "MIL" },
    ["KOBULETI"] = { icao = "", iata = "", type = "" },
    ["SENAKI KOLKHI"] = { icao = "", iata = "", type = "" },
    ["KRASNODAR CENTER"] = { icao = "", iata = "", type = "" },
    ["KRYMSK"] = { icao = "URKW", iata = "", type = "MIL" },
    ["KUTAISI"] = { icao = "UGKO", iata = "KUT", type = "CIV" },
    ["TBILISI LOCHINI"] = { icao = "UGTB", iata = "TBS", type = "CIV" },
    ["MINERALNYE VODY"] = { icao = "URMM", iata = "MRV", type = "CIV" },
    ["MOZDOK"] = { icao = "", iata = "", type = "" },
    ["NALCHIK"] = { icao = "URMN", iata = "NAL", type = "CIV" },
    ["NOVOROSSIYSK"] = { icao = "", iata = "NOI", type = "CIV" },
    ["KRASNODAR PASHKOVSKY"] = { icao = "URKK", iata = "KRR", type = "CIV" },
    ["SOCHI ADLER"] = { icao = "URSS", iata = "AER", type = "CIV" },
    ["SOGANLUG"] = { icao = "UG24", iata = "", type = "MIL" },
    ["SUKHUMI BABUSHARA"] = { icao = "UGSS", iata = "SUI", type = "CIV" },
    ["VAZIANI"] = { icao = "UG27", iata = "", type = "MIL" },
  },
  persiangulf = {
    ["AL MAKTOUM INTL"] = { icao = "OMDW", iata = "DWC", type = "CIV" },
    ["AL MINHAD AFB"] = { icao = "OMDM", iata = "NHD", type = "MIL" },
    ["DUBAI INTL"] = { icao = "OMDB", iata = "DXB", type = "CIV" },
    ["SHARJAH INTL"] = { icao = "OMSJ", iata = "SHJ", type = "CIV" },
    ["ABU MUSA ISLAND"] = { icao = "OIBA", iata = "AEU", type = "CIV" },
    ["SIRRI ISLAND"] = { icao = "OIBS", iata = "SXI", type = "CIV" },
    ["FUJAIRAH INTL"] = { icao = "OMFJ", iata = "FJR", type = "CIV" },
    ["BANDAR LENGEH"] = { icao = "OIBL", iata = "BDH", type = "CIV" },
    ["KHASAB"] = { icao = "OOKS", iata = "KHS", type = "CIV" },
    ["QESHM ISLAND"] = { icao = "OIKQ", iata = "GSM", type = "CIV" },
    ["HAVADARYA"] = { icao = "OIKP", iata = "HDR", type = "CIV" },
    ["BANDAR ABBAS INTL"] = { icao = "OIKB", iata = "BND", type = "CIV" },
    ["LAR"] = { icao = "OISL", iata = "LRR", type = "CIV" },
    ["KERMAN"] = { icao = "OIKK", iata = "KER", type = "CIV" },
    ["SHIRAZ INTL"] = { icao = "OISS", iata = "SYZ", type = "CIV" },
    ["AL DHAFRA AFB"] = { icao = "OMAM", iata = "DHF", type = "MIL" },
    ["AL BATEEN"] = { icao = "OMAD", iata = "AZI", type = "CIV" },
    ["KISH INTL"] = { icao = "OIBK", iata = "KIH", type = "CIV" },
    ["LAVAN ISLAND"] = { icao = "OIBV", iata = "LVP", type = "CIV" },
    ["AL AIN INTL"] = { icao = "OMAL", iata = "AAN", type = "CIV" },
    ["BANDAR E JASK"] = { icao = "OIZJ", iata = "", type = "CIV" },
    ["ABU DHABI INTL"] = { icao = "OMAA", iata = "AUH", type = "CIV" },
    ["SAS AL NAKHEEL"] = { icao = "OMNK", iata = "", type = "MIL" },
    ["JIROFT"] = { icao = "OIKJ", iata = "JYR", type = "CIV" },
    ["LIWA AFB"] = { icao = "OMLW", iata = "", type = "MIL" },
    ["RAS AL KHAIMAH INTL"] = { icao = "OMRK", iata = "RKT", type = "CIV" },
    ["SIR ABU NUAYR"] = { icao = "OMSN", iata = "", type = "CIV" },
  },
  syria = {
    ["BEIRUT RAFIC HARIRI"] = { icao = "OLBA", iata = "BEY", type = "CIV" },
    ["RAYAK"] = { icao = "OLRA", iata = "", type = "MIL" },
    ["WUJAH AL HAJAR"] = { icao = "Z19O", iata = "", type = "MIL" },
    ["KIRYAT SHMONA"] = { icao = "LLKS", iata = "", type = "CIV" },
    ["MEZZEH"] = { icao = "OS67", iata = "", type = "MIL" },
    ["QABR AS SITT"] = { icao = "", iata = "", type = "" },
    ["RENE MOUAWAD"] = { icao = "OLKA", iata = "KYE", type = "CIV" },
    ["MARJ AS SULTAN NORTH"] = { icao = "", iata = "", type = "" },
    ["MARJ AS SULTAN SOUTH"] = { icao = "", iata = "", type = "" },
    ["MARJ RUHAYYIL"] = { icao = "OS63", iata = "", type = "MIL" },
    ["AL DUMAYR"] = { icao = "OS61", iata = "", type = "MIL" },
    ["HAIFA"] = { icao = "LLHA", iata = "HFA", type = "CIV" },
    ["AN NASIRIYAH"] = { icao = "OS64", iata = "", type = "MIL" },
    ["AL QUSAYR"] = { icao = "OS70", iata = "", type = "MIL" },
    ["KHALKHALAH"] = { icao = "OS69", iata = "", type = "MIL" },
    ["RAMAT DAVID"] = { icao = "LLRD", iata = "", type = "MIL" },
    ["MEGIDDO"] = { icao = "LLMG", iata = "", type = "CIV" },
    ["EYN SHEMER"] = { icao = "LLXS", iata = "", type = "CIV" },
    ["BASSEL AL ASSAD"] = { icao = "OSLK", iata = "LTK", type = "CIV" },
    ["ABU AL DUHUR"] = { icao = "OS57", iata = "", type = "MIL" },
    ["TAFTANAZ"] = { icao = "", iata = "", type = "" },
    ["HATAY"] = { icao = "LTDA", iata = "HTY", type = "CIV" },
    ["KUWEIRES"] = { icao = "OS66", iata = "", type = "MIL" },
    ["MINAKH"] = { icao = "", iata = "", type = "" },
    ["JIRAH"] = { icao = "OS62", iata = "", type = "MIL" },
    ["ADANA SAKIRPASA"] = { icao = "LTAF", iata = "ADA", type = "CIV" },
    ["INCIRLIK"] = { icao = "LTAG", iata = "", type = "MIL" },
    ["DAMASCUS"] = { icao = "OSDI", iata = "DAM", type = "CIV" },
    ["THA LAH"] = { icao = "", iata = "", type = "" },
    ["LARNACA"] = { icao = "LCLK", iata = "LCA", type = "CIV" },
    ["AKROTIRI"] = { icao = "LCRA", iata = "", type = "MIL" },
    ["KING HUSSEIN AIR COLLEGE"] = { icao = "OJMF", iata = "", type = "MIL" },
    ["AT TANF"] = { icao = "", iata = "", type = "" },
    ["H3"] = { icao = "", iata = "", type = "" },
    ["H3 NORTHWEST"] = { icao = "", iata = "", type = "" },
    ["H3 SOUTHWEST"] = { icao = "", iata = "", type = "" },
    ["H4"] = { icao = "OJHR", iata = "", type = "MIL" },
    ["PAPHOS"] = { icao = "LCPH", iata = "PFO", type = "CIV" },
    ["LAKATAMIA"] = { icao = "LCLM", iata = "", type = "CIV" },
    ["ERCAN"] = { icao = "LCEN", iata = "ECN", type = "CIV" },
    ["MUWAFFAQ SALTI"] = { icao = "OJMS", iata = "", type = "MIL" },
    ["KING ABDULLAH II"] = { icao = "OJMF", iata = "", type = "MIL" },
    ["MARKA"] = { icao = "OJAM", iata = "ADJ", type = "CIV" },
    ["HERZLIYA"] = { icao = "LLHZ", iata = "", type = "CIV" },
    ["PRINCE HASSAN"] = { icao = "OJHF", iata = "", type = "MIL" },
  },
  nevada = {
    ["CREECH"] = { icao = "KINS", iata = "INS", type = "MIL" },
    ["HENDERSON EXECUTIVE"] = { icao = "KHND", iata = "HSH", type = "CIV" },
    ["MCCARRAN INTERNATIONAL"] = { icao = "KLAS", iata = "LAS", type = "CIV" },
    ["LAUGHLIN"] = { icao = "KIFP", iata = "IFP", type = "CIV" },
    ["NORTH LAS VEGAS"] = { icao = "KVGT", iata = "VGT", type = "CIV" },
    ["TONOPAH TEST RANGE"] = { icao = "KTNX", iata = "", type = "MIL" },
    ["GROOM LAKE"] = { icao = "KXTA", iata = "", type = "MIL" },
    ["NELLIS"] = { icao = "KLSV", iata = "", type = "MIL" },
    ["BOULDER CITY"] = { icao = "KBVU", iata = "BLD", type = "CIV" },
  },
  marianas = {
    ["ANDERSEN AFB"] = { icao = "PGUA", iata = "UAM", type = "MIL" },
    ["ANTONIO B WON PAT INTL"] = { icao = "PGUM", iata = "GUM", type = "CIV" },
    ["ROTA INTL"] = { icao = "PGRO", iata = "ROP", type = "CIV" },
    ["TINIAN INTL"] = { icao = "PGTT", iata = "TIQ", type = "CIV" },
    ["SAIPAN INTL"] = { icao = "PGSN", iata = "SPN", type = "CIV" },
    ["PAGAN"] = { icao = "TT01", iata = "", type = "CIV" },
    ["MARPI"] = { icao = "", iata = "", type = "" },
    ["KAGMAN"] = { icao = "", iata = "", type = "" },
    ["CHARON KANOA"] = { icao = "", iata = "", type = "" },
    ["ISLEY"] = { icao = "", iata = "", type = "" },
    ["USHI"] = { icao = "", iata = "", type = "" },
    ["AIRFIELD 3"] = { icao = "", iata = "", type = "" },
    ["GURGUAN POINT"] = { icao = "", iata = "", type = "" },
    ["ROTA"] = { icao = "PGRO", iata = "ROP", type = "CIV" },
    ["AGANA"] = { icao = "PGUM", iata = "GUM", type = "CIV" },
    ["OROTE"] = { icao = "", iata = "", type = "" },
  },
  thechannel = {
    ["DUNKIRK MARDYCK"] = { icao = "", iata = "", type = "" },
    ["HAWKINGE"] = { icao = "EGHK", iata = "", type = "MIL" },
    ["SAINT OMER LONGUENESSE"] = { icao = "LFQN", iata = "", type = "MIL" },
    ["MERVILLE CALONNE"] = { icao = "LFQT", iata = "HZB", type = "MIL" },
    ["HIGH HALDEN"] = { icao = "", iata = "", type = "" },
    ["DETLING"] = { icao = "", iata = "", type = "" },
    ["ABBEVILLE DRUCAT"] = { icao = "LFOI", iata = "", type = "MIL" },
    ["LYMPNE"] = { icao = "EGMK", iata = "LYM", type = "MIL" },
    ["MANSTON"] = { icao = "EGMH", iata = "MSE", type = "MIL" },
  },
  normandy = {
    ["BENY SUR MER"] = { icao = "", iata = "", type = "" },
    ["SAINTE CROIX SUR MER"] = { icao = "", iata = "", type = "" },
    ["LANTHEUIL"] = { icao = "", iata = "", type = "" },
    ["BAZENVILLE"] = { icao = "", iata = "", type = "" },
    ["SOMMERVIEU"] = { icao = "", iata = "", type = "" },
    ["LONGUES SUR MER"] = { icao = "", iata = "", type = "" },
    ["LE MOLAY"] = { icao = "", iata = "", type = "" },
    ["SAINTE LAURENT SUR MER"] = { icao = "", iata = "", type = "" },
    ["SAINT PIERRE DU MONT"] = { icao = "", iata = "", type = "" },
    ["DEUX JUMEAUX"] = { icao = "", iata = "", type = "" },
    ["CHIPPELLE"] = { icao = "", iata = "", type = "" },
    ["CRICQUEVILLE EN BESSIN"] = { icao = "", iata = "", type = "" },
    ["CARDONVILLE"] = { icao = "", iata = "", type = "" },
    ["BRUCHEVILLE"] = { icao = "", iata = "", type = "" },
    ["MEAUTIS"] = { icao = "", iata = "", type = "" },
    ["AZEVILLE"] = { icao = "", iata = "", type = "" },
    ["CRETTEVILLE"] = { icao = "", iata = "", type = "" },
    ["PICAUVILLE"] = { icao = "", iata = "", type = "" },
    ["BINIVILLE"] = { icao = "", iata = "", type = "" },
    ["LESSAY"] = { icao = "", iata = "", type = "" },
    ["MAUPERTUS"] = { icao = "LFRC", iata = "CER", type = "CIV" },
    ["EVREUX"] = { icao = "LFOE", iata = "EVX", type = "MIL" },
    ["FORDE"] = { icao = "", iata = "", type = "" },
    ["TANGMERE"] = { icao = "EGUT", iata = "", type = "MIL" },
    ["FUNTINGTON"] = { icao = "", iata = "", type = "" },
    ["CHAILEY"] = { icao = "", iata = "", type = "" },
    ["NEEDS OAR POINT"] = { icao = "", iata = "", type = "" },
  },
  sinai = {
    ["AL MANSURAH"] = { icao = "HE32", iata = "", type = "MIL" },
    ["AZZAQAZIQ"] = { icao = "", iata = "", type = "" },
    ["AS SALIHIYAH"] = { icao = "HE39", iata = "", type = "MIL" },
    ["BILBEIS AIR BASE"] = { icao = "HE37", iata = "", type = "MIL" },
    ["INSHAS AIRBASE"] = { icao = "HE12", iata = "", type = "MIL" },
    ["ABU SUWAYR"] = { icao = "HE35", iata = "", type = "MIL" },
    ["AL ISMAILIYAH"] = { icao = "HEIS", iata = "ISM", type = "MIL" },
    ["CAIRO INTERNATIONAL AIRPORT"] = { icao = "HECA", iata = "CAI", type = "CIV" },
    ["DIFARSUWAR AIRFIELD"] = { icao = "", iata = "", type = "" },
    ["WADI AL JANDALI"] = { icao = "", iata = "TFR", type = "CIV" },
    ["FAYED"] = { icao = "", iata = "", type = "" },
    ["BALUZA"] = { icao = "HE22", iata = "", type = "MIL" },
    ["CAIRO WEST"] = { icao = "HECW", iata = "", type = "MIL" },
    ["KIBRIT AIR BASE"] = { icao = "HE34", iata = "", type = "MIL" },
    ["MELEZ"] = { icao = "", iata = "", type = "" },
    ["BIR HASANAH"] = { icao = "", iata = "", type = "" },
    ["EL ARISH"] = { icao = "HEAR", iata = "AAC", type = "CIV" },
    ["EL GORA"] = { icao = "HEGR", iata = "", type = "MIL" },
    ["ABU RUDEIS"] = { icao = "", iata = "AUE", type = "CIV" },
    ["KEDEM"] = { icao = "", iata = "", type = "" },
    ["RAMON AIRBASE"] = { icao = "LLRM", iata = "", type = "MIL" },
    ["HATZERIM"] = { icao = "LLHB", iata = "", type = "MIL" },
    ["HATZOR"] = { icao = "LLHS", iata = "", type = "MIL" },
    ["PALMACHIM"] = { icao = "LLRM", iata = "", type = "MIL" },
    ["TEL NOF"] = { icao = "LLRN", iata = "", type = "MIL" },
    ["NEVATIM"] = { icao = "LLNV", iata = "", type = "MIL" },
    ["SDE DOV"] = { icao = "LLSD", iata = "SDV", type = "CIV" },
    ["BEN GURION"] = { icao = "LLBG", iata = "TLV", type = "CIV" },
    ["OVDA"] = { icao = "LLOV", iata = "VDA", type = "CIV" },
    ["ST CATHERINE"] = { icao = "HESC", iata = "SKV", type = "CIV" },
    ["WADI ABU RISH"] = { icao = "", iata = "", type = "" },
    ["RAMON INTERNATIONAL AIRPORT"] = { icao = "LLER", iata = "ETM", type = "CIV" },
    ["SHARM EL SHEIKH INTERNATIONAL AIRPORT"] = { icao = "HESH", iata = "SSH", type = "CIV" },
    ["HURGHADA INTERNATIONAL AIRPORT"] = { icao = "HEGN", iata = "HRG", type = "CIV" },
    ["AL BAHR AL AHMAR"] = { icao = "", iata = "", type = "" },
    ["EL MINYA"] = { icao = "HE25", iata = "EMY", type = "CIV" },
    ["BENI SUEF"] = { icao = "HEBS", iata = "", type = "MIL" },
    ["KOM AWSHIM"] = { icao = "HE30", iata = "", type = "CIV" },
    ["QUWAYSINA"] = { icao = "", iata = "", type = "" },
    ["BIRMA AIR BASE"] = { icao = "HE16", iata = "", type = "MIL" },
    ["GEBEL EL BASUR AIR BASE"] = { icao = "HE28", iata = "", type = "MIL" },
    ["AL RAHMANIYAH AIR BASE"] = { icao = "HE0P", iata = "", type = "MIL" },
    ["JIYANKLIS AIR BASE"] = { icao = "HEGS", iata = "", type = "MIL" },
    ["BORJ EL ARAB INTERNATIONAL AIRPORT"] = { icao = "HEBR", iata = "HBE", type = "CIV" },
  },
  southatlantic = {
    ["MOUNT PLEASANT"] = { icao = "EGYP", iata = "MPN", type = "CIV" },
    ["GOOSE GREEN"] = { icao = "", iata = "", type = "" },
    ["SAN CARLOS FOB"] = { icao = "", iata = "", type = "" },
    ["PORT STANLEY"] = { icao = "SFAL", iata = "PSY", type = "CIV" },
    ["AERODROMO DE TOLHUIN"] = { icao = "SAWL", iata = "", type = "CIV" },
    ["RIO GRANDE"] = { icao = "SAWE", iata = "", type = "CIV" },
    ["PUERTO WILLIAMS"] = { icao = "SCGZ", iata = "", type = "CIV" },
    ["SAN JULIAN"] = { icao = "SAWS", iata = "", type = "CIV" },
    ["USHUAIA HELO PORT"] = { icao = "", iata = "", type = "" },
    ["USHUAIA"] = { icao = "SAWH", iata = "", type = "CIV" },
    ["PAMPA GUANACO"] = { icao = "SCBI", iata = "", type = "CIV" },
    ["PUERTO SANTA CRUZ"] = { icao = "SAWU", iata = "", type = "CIV" },
    ["RIO CHICO"] = { icao = "", iata = "RGR", type = "CIV" },
    ["RIO GALLEGOS"] = { icao = "SAWG", iata = "RGL", type = "CIV" },
    ["FRANCO BIANCO"] = { icao = "SCSB", iata = "SMB", type = "CIV" },
    ["COMANDANTE LUIS PIEDRABUENA"] = { icao = "SAWJ", iata = "", type = "CIV" },
    ["PORVENIR AIRFIELD"] = { icao = "SCFM", iata = "WPR", type = "CIV" },
    ["PUNTA ARENAS"] = { icao = "SCCI", iata = "PUQ", type = "CIV" },
    ["AEROPUERTO DE GOBERNADOR GREGORES"] = { icao = "SAWR", iata = "GGS", type = "CIV" },
    ["RIO TURBIO"] = { icao = "SAWT", iata = "RYO", type = "CIV" },
    ["EL CALAFATE"] = { icao = "SAWC", iata = "FTE", type = "CIV" },
    ["PUERTO NATALES"] = { icao = "SCNT", iata = "PNT", type = "CIV" },
    ["AERODROMO O HIGGINS"] = { icao = "", iata = "", type = "" },
  },
  kola = {
    ["ANDOYA"] = { icao = "ENAN", iata = "ANX", type = "CIV" },
    ["BODO"] = { icao = "ENBO", iata = "BOO", type = "CIV" },
    ["BARDUFOSS"] = { icao = "ENDU", iata = "BDU", type = "CIV" },
    ["EVENES"] = { icao = "ENEV", iata = "EVE", type = "CIV" },
    ["ALTA"] = { icao = "ENAT", iata = "ALF", type = "CIV" },
    ["BANAK"] = { icao = "ENNA", iata = "LKL", type = "CIV" },
    ["ENONTEKIO"] = { icao = "EFET", iata = "ENF", type = "CIV" },
    ["KIRUNA"] = { icao = "ESNQ", iata = "KRN", type = "CIV" },
    ["KALIXFORS"] = { icao = "ESUK", iata = "", type = "CIV" },
    ["JOKKMOKK"] = { icao = "ESNJ", iata = "", type = "CIV" },
    ["VIDSEL"] = { icao = "ESPE", iata = "", type = "MIL" },
    ["KALLAX"] = { icao = "ESPA", iata = "LLA", type = "CIV" },
    ["KEMI TORINO"] = { icao = "EFKM", iata = "KEM", type = "CIV" },
    ["HOSIO"] = { icao = "", iata = "", type = "" },
    ["ROVANIEMI"] = { icao = "EFRO", iata = "RVN", type = "CIV" },
    ["VUOJARVI"] = { icao = "", iata = "", type = "" },
    ["SODANKYLA"] = { icao = "EFSO", iata = "", type = "CIV" },
    ["KITTILA"] = { icao = "EFKT", iata = "KTT", type = "CIV" },
    ["IVALO"] = { icao = "EFIV", iata = "IVL", type = "CIV" },
    ["KIRKENES"] = { icao = "ENKR", iata = "KKN", type = "CIV" },
    ["SEVEROMORSK 1"] = { icao = "ULAK", iata = "", type = "MIL" },
    ["SEVEROMORSK 3"] = { icao = "XLMV", iata = "", type = "MIL" },
    ["MURMANSK INTERNATIONAL"] = { icao = "ULMM", iata = "MMK", type = "CIV" },
    ["OLENYA"] = { icao = "ULOR", iata = "", type = "MIL" },
    ["MONCHEGORSK"] = { icao = "ULMB", iata = "", type = "MIL" },
    ["ALAKURTTI"] = { icao = "XLMA", iata = "", type = "MIL" },
    ["KUUSAMO"] = { icao = "EFKS", iata = "KAO", type = "CIV" },
  },
  afghanistan = {
    ["TARINKOT"] = { icao = "OATN", iata = "TII", type = "CIV" },
    ["KANDAHAR"] = { icao = "OAKN", iata = "KDH", type = "CIV" },
    ["KANDAHAR HELIPORT"] = { icao = "", iata = "", type = "" },
    ["CHAGHCHARAN"] = { icao = "OACC", iata = "CCN", type = "CIV" },
    ["BOST"] = { icao = "OABT", iata = "", type = "CIV" },
    ["DWYER"] = { icao = "OADY", iata = "", type = "MIL" },
    ["CAMP BASTION"] = { icao = "OAZI", iata = "", type = "MIL" },
    ["CAMP BASTION HELIPORT"] = { icao = "", iata = "", type = "" },
    ["QALA I NAW"] = { icao = "OAQN", iata = "LQN", type = "CIV" },
    ["HERAT"] = { icao = "OAHR", iata = "HEA", type = "CIV" },
    ["SHINDAND"] = { icao = "OAHN", iata = "OAH", type = "MIL" },
    ["SHINDAND HELIPORT"] = { icao = "", iata = "", type = "" },
    ["FARAH"] = { icao = "OAFR", iata = "FAH", type = "CIV" },
    ["NIMROZ"] = { icao = "OANZ", iata = "", type = "CIV" },
    ["BAGRAM"] = { icao = "OAIX", iata = "OAI", type = "MIL" },
    ["BAMYAN"] = { icao = "OABN", iata = "BIN", type = "CIV" },
    ["GHAZNI HELIPORT"] = { icao = "", iata = "", type = "" },
    ["GARDEZ"] = { icao = "OAGZ", iata = "", type = "CIV" },
    ["JALALABAD"] = { icao = "OAJL", iata = "JAA", type = "CIV" },
    ["KABUL"] = { icao = "OAKB", iata = "KBL", type = "CIV" },
    ["KHOST"] = { icao = "OAKS", iata = "KHT", type = "CIV" },
    ["KHOST HELIPORT"] = { icao = "", iata = "", type = "" },
    ["SHARAN"] = { icao = "OASA", iata = "", type = "CIV" },
    ["URGOON HELIPORT"] = { icao = "", iata = "", type = "" },
    ["MAYMANA ZAHIRADDIN FARYABI"] = { icao = "OAMN", iata = "MMZ", type = "CIV" },
    ["MARY"] = { icao = "UTAM", iata = "", type = "CIV" },
    ["MARY NORTH"] = { icao = "UT52", iata = "", type = "CIV" },
  },
  iraq = {
    ["AL ASAD AIRBASE"] = { icao = "ORAA", iata = "", type = "MIL" },
    ["AL KUT AIRPORT"] = { icao = "", iata = "", type = "" },
    ["AL SAHRA AIRPORT"] = { icao = "ORSH", iata = "", type = "MIL" },
    ["AL SALAM AIRBASE"] = { icao = "", iata = "", type = "" },
    ["AL TAJI AIRPORT"] = { icao = "ORTI", iata = "", type = "MIL" },
    ["AL TAQUDDUM AIRPORT"] = { icao = "ORAT", iata = "", type = "MIL" },
    ["BAGHDAD INTERNATIONAL AIRPORT"] = { icao = "ORBI", iata = "BGW", type = "CIV" },
    ["BALAD AIRBASE"] = { icao = "ORBD", iata = "", type = "MIL" },
    ["BASHUR AIRPORT"] = { icao = "ORBR", iata = "", type = "MIL" },
    ["ERBIL INTERNATIONAL AIRPORT"] = { icao = "ORER", iata = "EBL", type = "CIV" },
    ["H 2 AIRBASE"] = { icao = "", iata = "", type = "" },
    ["H 3 MAIN AIRBASE"] = { icao = "", iata = "", type = "" },
    ["H 3 NORTHWEST AIRBASE"] = { icao = "", iata = "", type = "" },
    ["H 3 SOUTHWEST AIRBASE"] = { icao = "", iata = "", type = "" },
    ["K1 BASE"] = { icao = "", iata = "", type = "" },
    ["KIRKUK INTERNATIONAL AIRPORT"] = { icao = "ORKK", iata = "KIK", type = "CIV" },
    ["MOSUL INTERNATIONAL AIRPORT"] = { icao = "ORBM", iata = "OSM", type = "CIV" },
    ["QAYYARAH AIRFIELD WEST"] = { icao = "ORQW", iata = "RQW", type = "MIL" },
    ["SULAIMANIYAH INTERNATIONAL AIRPORT"] = { icao = "ORSU", iata = "ISU", type = "CIV" },
  },
}
