using System.Collections.Generic;

namespace VAICOM.WSO
{
    public static class WSOCommandMappings
    {
        // Map WSO commands to their proxy API calls
        public static readonly Dictionary<string, (string category, string action, string value)> CommandMap = new Dictionary<string, (string, string, string)>
        {
            // Example commands
            { "wMsgWSO_ReportSpeed", ("jester", "report_speed", "") },
            { "wMsgWSO_ToggleRadar", ("jester", "toggle_radar", "") },
            { "wMsgWSO_SetChaffMode", ("jester", "set_chaff_mode", "MULT") },
            { "wMsgWSO_Lantirn_Designate", ("jester", "lantirn_designate", "") },
            { "wMsgWSO_Lantirn_Undesignate", ("jester", "lantirn_undesignate", "") },
            { "wMsgWSO_Radar_GoSilent", ("jester", "radar_go_silent", "") },
            { "wMsgWSO_Radar_GoActive", ("jester", "radar_go_active", "") },
            { "wMsgWSO_Radio_SetManualFrequency", ("radio", "radio_manual_freq_text", "") },
            { "wMsgWSO_Radio_SelectCommChannel", ("radio", "radio_comm_chan", "") },
            { "wMsgWSO_Radio_SelectAuxChannel", ("radio", "radio_aux_chan", "") },
            { "wMsgWSO_Radio_TuneATC", ("radio", "radio_tune_atc_thinking", "") },
            { "wMsgWSO_Radio_TuneAssets", ("radio", "radio_tune_asset_thinking", "") },
            { "wMsgWSO_Radio_SelectMode", ("radio", "radio_mode", "") },
            { "wMsgWSO_Radar_Operation_Active", ("radar", "radar_op", "active") },
            { "wMsgWSO_Radar_Operation_Standby", ("radar", "radar_op", "standby") },
            { "wMsgWSO_Radar_AutoFocus_On", ("radar", "radar_auto_focus", "on") },
            { "wMsgWSO_Radar_AutoFocus_Off", ("radar", "radar_auto_focus", "off") },
            { "wMsgWSO_Radar_IFF_Both", ("radar", "radar_iff", "both") },
            { "wMsgWSO_Radar_IFF_APX76", ("radar", "radar_iff", "apx_76") },
            { "wMsgWSO_Radar_Boresight_EnterBST", ("radar", "radar_enter_bst", "") },
            { "wMsgWSO_Radar_Boresight_Wide", ("radar", "radar_bst_aspect", "wide") },
            { "wMsgWSO_Radar_Boresight_Nose", ("radar", "radar_bst_aspect", "nose") },
            { "wMsgWSO_Radar_Boresight_Forward", ("radar", "radar_bst_aspect", "fwd") },
            { "wMsgWSO_Radar_Boresight_Aft", ("radar", "radar_bst_aspect", "aft") },
            { "wMsgWSO_Radar_Boresight_Tail", ("radar", "radar_bst_aspect", "tail") },
            { "wMsgWSO_Radar_ScanElevation_Center", ("radar", "radar_scan_zone", "30;0;relative") },
            { "wMsgWSO_Radar_ScanElevation_Low", ("radar", "radar_scan_zone", "30;-3.5;relative") },
            { "wMsgWSO_Radar_ScanElevation_MidLow", ("radar", "radar_scan_zone", "30;-5;relative") },
            { "wMsgWSO_Radar_ScanElevation_FarLow", ("radar", "radar_scan_zone", "30;-7.5;relative") },
            { "wMsgWSO_Radar_ScanElevation_CloseHigh", ("radar", "radar_scan_zone", "30;3.5;relative") },
            { "wMsgWSO_Radar_ScanElevation_MidHigh", ("radar", "radar_scan_zone", "30;5;relative") },
            { "wMsgWSO_Radar_ScanElevation_FarHigh", ("radar", "radar_scan_zone", "30;7.5;relative") },
            { "wMsgWSO_Radar_ScanType_25Wide", ("radar", "radar_display_range", "nm_25;wide") },
            { "wMsgWSO_Radar_ScanType_25Narrow", ("radar", "radar_display_range", "nm_25;narrow") },
            { "wMsgWSO_Radar_ScanType_50Wide", ("radar", "radar_display_range", "nm_50;wide") },
            { "wMsgWSO_Radar_ScanType_50Narrow", ("radar", "radar_display_range", "nm_50;narrow") },
            { "wMsgWSO_Radar_FocusTarget", ("radar", "radar_focus_targets_thinking", "") },
            { "wMsgWSO_Radar_LockTarget", ("radar", "radar_lock_targets_thinking", "") },
            { "wMsgWSO_A2G_TVWeapons", ("a2g", "a2g_tv_feed", "weapons") },
            { "wMsgWSO_A2G_TVPaveSpike", ("a2g", "a2g_tv_feed", "pave_spike") },
            { "wMsgWSO_Navigation_GoToResume", ("nav", "goto_resume_thinking", "") },
            { "wMsgWSO_Navigation_Holding_CurrentTurnPoint", ("nav", "hold_curr_wpt", "") },
            { "wMsgWSO_Navigation_Divert_LatLong", ("nav", "nav_enter_tgt_1_lat_long_text", "") },
            { "wMsgWSO_Navigation_TACAN_SelectMode_Off", ("nav", "nav_tacan_mode", "off") },
            { "wMsgWSO_Navigation_TACAN_SelectMode_R", ("nav", "nav_tacan_mode", "r") },
            { "wMsgWSO_Navigation_TACAN_SelectMode_TR", ("nav", "nav_tacan_mode", "tr") },
            { "wMsgWSO_Navigation_TACAN_SelectMode_AAR", ("nav", "nav_tacan_mode", "aar") },
            { "wMsgWSO_Navigation_TACAN_SelectMode_AATR", ("nav", "nav_tacan_mode", "aatr") },
            { "wMsgWSO_Systems_ChaffMode_Off", ("systems", "systems_chaff", "off") },
            { "wMsgWSO_Systems_ChaffMode_Single", ("systems", "systems_chaff", "single") },
            { "wMsgWSO_Systems_ChaffMode_Multiple", ("systems", "systems_chaff", "multiple") },
            { "wMsgWSO_Systems_ChaffMode_Program", ("systems", "systems_chaff", "program") },
            { "wMsgWSO_Systems_FlareMode_Off", ("systems", "systems_flare", "off") },
            { "wMsgWSO_Systems_FlareMode_Single", ("systems", "systems_flare", "single") },
            { "wMsgWSO_Systems_FlareMode_Program", ("systems", "systems_flare", "program") },
            { "wMsgWSO_Systems_Jammer_Standby", ("systems", "systems_jammer", "standby") },
            { "wMsgWSO_Systems_Jammer_Transmit", ("systems", "systems_jammer", "xmit") },
            { "wMsgWSO_Systems_AVTR_Record", ("systems", "systems_avtr_recorder", "record") },
            { "wMsgWSO_Systems_AVTR_Standby", ("systems", "systems_avtr_recorder", "standby") },
            { "wMsgWSO_Systems_AVTR_Off", ("systems", "systems_avtr_recorder", "off") },
            { "wMsgWSO_Crew_Presence_Auto", ("crew", "crew_presence", "auto") },
            { "wMsgWSO_Crew_Presence_Force", ("crew", "crew_presence", "enabled") },
            { "wMsgWSO_Crew_Presence_Disable", ("crew", "crew_presence", "disabled") },
            { "wMsgWSO_Crew_Talking_Talk", ("crew", "crew_talking", "talk") },
            { "wMsgWSO_Crew_Talking_Silence", ("crew", "crew_talking", "silence") },
            { "wMsgWSO_Crew_Ejection_WSO", ("crew", "crew_ejection", "wso") },
            { "wMsgWSO_Crew_Ejection_Both", ("crew", "crew_ejection", "both") },
            { "wMsgWSO_Crew_Countermeasures_Manual", ("crew", "crew_countermeasures", "manual") },
            { "wMsgWSO_Crew_Countermeasures_Jester", ("crew", "crew_countermeasures", "jester") },
        };
    }
}