using System;
using System.Collections.Generic;
using VAICOM.Shared;

namespace VAICOM.Extensions.WSO
{
    public static class Commands //Adds WSO commands to the command database
    {
        // WSO commands: 24000 - 24999 (1000 slots reserved for WSO commands)
        public static Dictionary<string, CommandInfo> all = new Dictionary<string, CommandInfo>(StringComparer.OrdinalIgnoreCase)
        {
            { "wMsgWSOCmndsNull", new CommandInfo { uniqueid = 24000, category = CommandCategories.WSO, name = "wMsgWSOCmndsNull", displayname = "WSO Commands Null", enabled = true } },
            { "Jester.ReportSpeed", new CommandInfo { uniqueid = 24001, category = CommandCategories.WSO, name = "Jester.ReportSpeed", displayname = "Jester.Report.Speed", enabled = true } },
            { "Jester.ToggleRadar", new CommandInfo { uniqueid = 24002, category = CommandCategories.WSO, name = "Jester.ToggleRadar", displayname = "Jester.Toggle.Radar", enabled = true } },
            { "Jester.SetChaffMode", new CommandInfo { uniqueid = 24003, category = CommandCategories.WSO, name = "Jester.SetChaffMode", displayname = "Jester.Set.Chaff.Mode", enabled = true } },
            { "Jester.Lantirn.Designate", new CommandInfo { uniqueid = 24004, category = CommandCategories.WSO, name = "Jester.Lantirn.Designate", displayname = "Jester.Lantirn.Designate", enabled = true } },
            { "Jester.Lantirn.Undesignate", new CommandInfo { uniqueid = 24005, category = CommandCategories.WSO, name = "Jester.Lantirn.Undesignate", displayname = "Jester.Lantirn.Undesignate", enabled = true } },
            { "Jester.Radar.GoSilent", new CommandInfo { uniqueid = 24006, category = CommandCategories.WSO, name = "Jester.Radar.GoSilent", displayname = "Jester.Radar.GoSilent", enabled = true } },
            { "Jester.Radar.GoActive", new CommandInfo { uniqueid = 24007, category = CommandCategories.WSO, name = "Jester.Radar.GoActive", displayname = "Jester.Radar.GoActive", enabled = true } },
            { "Jester.Radio.SetManualFrequency", new CommandInfo { uniqueid = 24008, category = CommandCategories.WSO, name = "Jester.Radio.SetManualFrequency", displayname = "Jester.Radio.SetManualFrequency", enabled = true } },
            { "Jester.Radio.SelectCommChannel", new CommandInfo { uniqueid = 24009, category = CommandCategories.WSO, name = "Jester.Radio.SelectCommChannel", displayname = "Jester.Radio.SelectCommChannel", enabled = true } },
            { "Jester.Radio.SelectAuxChannel", new CommandInfo { uniqueid = 24010, category = CommandCategories.WSO, name = "Jester.Radio.SelectAuxChannel", displayname = "Jester.Radio.SelectAuxChannel", enabled = true } },
            { "Jester.Radio.TuneATC", new CommandInfo { uniqueid = 24011, category = CommandCategories.WSO, name = "Jester.Radio.TuneATC", displayname = "Jester.Radio.TuneATC", enabled = true } },
            { "Jester.Radio.TuneAssets", new CommandInfo { uniqueid = 24012, category = CommandCategories.WSO, name = "Jester.Radio.TuneAssets", displayname = "Jester.Radio.TuneAssets", enabled = true } },
            { "Jester.Radio.SelectMode", new CommandInfo { uniqueid = 24013, category = CommandCategories.WSO, name = "Jester.Radio.SelectMode", displayname = "Jester.Radio.SelectMode", enabled = true } },
            { "Jester.Radar.Operation.Active", new CommandInfo { uniqueid = 24014, category = CommandCategories.WSO, name = "Jester.Radar.Operation.Active", displayname = "Jester.Radar.Operation.Active", enabled = true } },
            { "Jester.Radar.Operation.Standby", new CommandInfo { uniqueid = 24015, category = CommandCategories.WSO, name = "Jester.Radar.Operation.Standby", displayname = "Jester.Radar.Operation.Standby", enabled = true } },
            { "Jester.Radar.AutoFocus.On", new CommandInfo { uniqueid = 24016, category = CommandCategories.WSO, name = "Jester.Radar.AutoFocus.On", displayname = "Jester.Radar.AutoFocus.On", enabled = true } },
            { "Jester.Radar.AutoFocus.Off", new CommandInfo { uniqueid = 24017, category = CommandCategories.WSO, name = "Jester.Radar.AutoFocus.Off", displayname = "Jester.Radar.AutoFocus.Off", enabled = true } },
            { "Jester.Radar.IFF.Both", new CommandInfo { uniqueid = 24018, category = CommandCategories.WSO, name = "Jester.Radar.IFF.Both", displayname = "Jester.Radar.IFF.Both", enabled = true } },
            { "Jester.Radar.IFF.APX76", new CommandInfo { uniqueid = 24019, category = CommandCategories.WSO, name = "Jester.Radar.IFF.APX76", displayname = "Jester.Radar.IFF.APX76", enabled = true } },
            { "Jester.Radar.Boresight.EnterBST", new CommandInfo { uniqueid = 24020, category = CommandCategories.WSO, name = "Jester.Radar.Boresight.EnterBST", displayname = "Jester.Radar.Boresight.EnterBST", enabled = true } },
            { "Jester.Radar.Boresight.Wide", new CommandInfo { uniqueid = 24021, category = CommandCategories.WSO, name = "Jester.Radar.Boresight.Wide", displayname = "Jester.Radar.Boresight.Wide", enabled = true } },
            { "Jester.Radar.Boresight.Nose", new CommandInfo { uniqueid = 24022, category = CommandCategories.WSO, name = "Jester.Radar.Boresight.Nose", displayname = "Jester.Radar.Boresight.Nose", enabled = true } },
            { "Jester.Radar.Boresight.Forward", new CommandInfo { uniqueid = 24023, category = CommandCategories.WSO, name = "Jester.Radar.Boresight.Forward", displayname = "Jester.Radar.Boresight.Forward", enabled = true } },
            { "Jester.Radar.Boresight.Aft", new CommandInfo { uniqueid = 24024, category = CommandCategories.WSO, name = "Jester.Radar.Boresight.Aft", displayname = "Jester.Radar.Boresight.Aft", enabled = true } },
            { "Jester.Radar.Boresight.Tail", new CommandInfo { uniqueid = 24025, category = CommandCategories.WSO, name = "Jester.Radar.Boresight.Tail", displayname = "Jester.Radar.Boresight.Tail", enabled = true } },
            { "Jester.Radar.ScanElevation.Center", new CommandInfo { uniqueid = 24026, category = CommandCategories.WSO, name = "Jester.Radar.ScanElevation.Center", displayname = "Jester.Radar.ScanElevation.Center", enabled = true } },
            { "Jester.Radar.ScanElevation.Low", new CommandInfo { uniqueid = 24027, category = CommandCategories.WSO, name = "Jester.Radar.ScanElevation.Low", displayname = "Jester.Radar.ScanElevation.Low", enabled = true } },
            { "Jester.Radar.ScanElevation.MidLow", new CommandInfo { uniqueid = 24028, category = CommandCategories.WSO, name = "Jester.Radar.ScanElevation.MidLow", displayname = "Jester.Radar.ScanElevation.MidLow", enabled = true } },
            { "Jester.Radar.ScanElevation.FarLow", new CommandInfo { uniqueid = 24029, category = CommandCategories.WSO, name = "Jester.Radar.ScanElevation.FarLow", displayname = "Jester.Radar.ScanElevation.FarLow", enabled = true } },
            { "Jester.Radar.ScanElevation.CloseHigh", new CommandInfo { uniqueid = 24030, category = CommandCategories.WSO, name = "Jester.Radar.ScanElevation.CloseHigh", displayname = "Jester.Radar.ScanElevation.CloseHigh", enabled = true } },
            { "Jester.Radar.ScanElevation.MidHigh", new CommandInfo { uniqueid = 24031, category = CommandCategories.WSO, name = "Jester.Radar.ScanElevation.MidHigh", displayname = "Jester.Radar.ScanElevation.MidHigh", enabled = true } },
            { "Jester.Radar.ScanElevation.FarHigh", new CommandInfo { uniqueid = 24032, category = CommandCategories.WSO, name = "Jester.Radar.ScanElevation.FarHigh", displayname = "Jester.Radar.ScanElevation.FarHigh", enabled = true } },
            { "Jester.Radar.ScanType.25Wide", new CommandInfo { uniqueid = 24033, category = CommandCategories.WSO, name = "Jester.Radar.ScanType.25Wide", displayname = "Jester.Radar.ScanType.25Wide", enabled = true } },
            { "Jester.Radar.ScanType.25Narrow", new CommandInfo { uniqueid = 24034, category = CommandCategories.WSO, name = "Jester.Radar.ScanType.25Narrow", displayname = "Jester.Radar.ScanType.25Narrow", enabled = true } },
            { "Jester.Radar.ScanType.50Wide", new CommandInfo { uniqueid = 24035, category = CommandCategories.WSO, name = "Jester.Radar.ScanType.50Wide", displayname = "Jester.Radar.ScanType.50Wide", enabled = true } },
            { "Jester.Radar.ScanType.50Narrow", new CommandInfo { uniqueid = 24036, category = CommandCategories.WSO, name = "Jester.Radar.ScanType.50Narrow", displayname = "Jester.Radar.ScanType.50Narrow", enabled = true } },
            { "Jester.Radar.FocusTarget", new CommandInfo { uniqueid = 24037, category = CommandCategories.WSO, name = "Jester.Radar.FocusTarget", displayname = "Jester.Radar.FocusTarget", enabled = true } },
            { "Jester.Radar.LockTarget", new CommandInfo { uniqueid = 24038, category = CommandCategories.WSO, name = "Jester.Radar.LockTarget", displayname = "Jester.Radar.LockTarget", enabled = true } },
            { "Jester.A2G.TVWeapons", new CommandInfo { uniqueid = 24039, category = CommandCategories.WSO, name = "Jester.A2G.TVWeapons", displayname = "Jester.A2G.TVWeapons", enabled = true } },
            { "Jester.A2G.TVPaveSpike", new CommandInfo { uniqueid = 24040, category = CommandCategories.WSO, name = "Jester.A2G.TVPaveSpike", displayname = "Jester.A2G.TVPaveSpike", enabled = true } },
            { "Jester.Navigation.GoToResume", new CommandInfo { uniqueid = 24041, category = CommandCategories.WSO, name = "Jester.Navigation.GoToResume", displayname = "Jester.Navigation.GoToResume", enabled = true } },
            { "Jester.Navigation.Holding.CurrentTurnPoint", new CommandInfo { uniqueid = 24042, category = CommandCategories.WSO, name = "Jester.Navigation.Holding.CurrentTurnPoint", displayname = "Jester.Navigation.Holding.CurrentTurnPoint", enabled = true } },
            { "Jester.Navigation.Divert.LatLong", new CommandInfo { uniqueid = 24043, category = CommandCategories.WSO, name = "Jester.Navigation.Divert.LatLong", displayname = "Jester.Navigation.Divert.LatLong", enabled = true } },
            { "Jester.Navigation.TACAN.SelectMode.Off", new CommandInfo { uniqueid = 24044, category = CommandCategories.WSO, name = "Jester.Navigation.TACAN.SelectMode.Off", displayname = "Jester.Navigation.TACAN.SelectMode.Off", enabled = true } },
            { "Jester.Navigation.TACAN.SelectMode.R", new CommandInfo { uniqueid = 24045, category = CommandCategories.WSO, name = "Jester.Navigation.TACAN.SelectMode.R", displayname = "Jester.Navigation.TACAN.SelectMode.R", enabled = true } },
            { "Jester.Navigation.TACAN.SelectMode.TR", new CommandInfo { uniqueid = 24046, category = CommandCategories.WSO, name = "Jester.Navigation.TACAN.SelectMode.TR", displayname = "Jester.Navigation.TACAN.SelectMode.TR", enabled = true } },
            { "Jester.Navigation.TACAN.SelectMode.AAR", new CommandInfo { uniqueid = 24047, category = CommandCategories.WSO, name = "Jester.Navigation.TACAN.SelectMode.AAR", displayname = "Jester.Navigation.TACAN.SelectMode.AAR", enabled = true } },
            { "Jester.Navigation.TACAN.SelectMode.AATR", new CommandInfo { uniqueid = 24048, category = CommandCategories.WSO, name = "Jester.Navigation.TACAN.SelectMode.AATR", displayname = "Jester.Navigation.TACAN.SelectMode.AATR", enabled = true } },
            { "Jester.Systems.ChaffMode.Off", new CommandInfo { uniqueid = 24049, category = CommandCategories.WSO, name = "Jester.Systems.ChaffMode.Off", displayname = "Jester.Systems.ChaffMode.Off", enabled = true } },
            { "Jester.Systems.ChaffMode.Single", new CommandInfo { uniqueid = 24050, category = CommandCategories.WSO, name = "Jester.Systems.ChaffMode.Single", displayname = "Jester.Systems.ChaffMode.Single", enabled = true } },
            { "Jester.Systems.ChaffMode.Multiple", new CommandInfo { uniqueid = 24051, category = CommandCategories.WSO, name = "Jester.Systems.ChaffMode.Multiple", displayname = "Jester.Systems.ChaffMode.Multiple", enabled = true } },
            { "Jester.Systems.ChaffMode.Program", new CommandInfo { uniqueid = 24052, category = CommandCategories.WSO, name = "Jester.Systems.ChaffMode.Program", displayname = "Jester.Systems.ChaffMode.Program", enabled = true } },
            { "Jester.Systems.FlareMode.Off", new CommandInfo { uniqueid = 24053, category = CommandCategories.WSO, name = "Jester.Systems.FlareMode.Off", displayname = "Jester.Systems.FlareMode.Off", enabled = true } },
            { "Jester.Systems.FlareMode.Single", new CommandInfo { uniqueid = 24054, category = CommandCategories.WSO, name = "Jester.Systems.FlareMode.Single", displayname = "Jester.Systems.FlareMode.Single", enabled = true } },
            { "Jester.Systems.FlareMode.Program", new CommandInfo { uniqueid = 24055, category = CommandCategories.WSO, name = "Jester.Systems.FlareMode.Program", displayname = "Jester.Systems.FlareMode.Program", enabled = true } },
            { "Jester.Systems.Jammer.Standby", new CommandInfo { uniqueid = 24056, category = CommandCategories.WSO, name = "Jester.Systems.Jammer.Standby", displayname = "Jester.Systems.Jammer.Standby", enabled = true } },
            { "Jester.Systems.Jammer.Transmit", new CommandInfo { uniqueid = 24057, category = CommandCategories.WSO, name = "Jester.Systems.Jammer.Transmit", displayname = "Jester.Systems.Jammer.Transmit", enabled = true } },
            { "Jester.Systems.AVTR.Record", new CommandInfo { uniqueid = 24058, category = CommandCategories.WSO, name = "Jester.Systems.AVTR.Record", displayname = "Jester.Systems.AVTR.Record", enabled = true } },
            { "Jester.Systems.AVTR.Standby", new CommandInfo { uniqueid = 24059, category = CommandCategories.WSO, name = "Jester.Systems.AVTR.Standby", displayname = "Jester.Systems.AVTR.Standby", enabled = true } },
            { "Jester.Systems.AVTR.Off", new CommandInfo { uniqueid = 24060, category = CommandCategories.WSO, name = "Jester.Systems.AVTR.Off", displayname = "Jester.Systems.AVTR.Off", enabled = true } },
            { "Jester.Crew.Presence.Auto", new CommandInfo { uniqueid = 24061, category = CommandCategories.WSO, name = "Jester.Crew.Presence.Auto", displayname = "Jester.Crew.Presence.Auto", enabled = true } },
            { "Jester.Crew.Presence.Force", new CommandInfo { uniqueid = 24062, category = CommandCategories.WSO, name = "Jester.Crew.Presence.Force", displayname = "Jester.Crew.Presence.Force", enabled = true } },
            { "Jester.Crew.Presence.Disable", new CommandInfo { uniqueid = 24063, category = CommandCategories.WSO, name = "Jester.Crew.Presence.Disable", displayname = "Jester.Crew.Presence.Disable", enabled = true } },
            { "Jester.Crew.Talking.Talk", new CommandInfo { uniqueid = 24064, category = CommandCategories.WSO, name = "Jester.Crew.Talking.Talk", displayname = "Jester.Crew.Talking.Talk", enabled = true } },
            { "Jester.Crew.Talking.Silence", new CommandInfo { uniqueid = 24065, category = CommandCategories.WSO, name = "Jester.Crew.Talking.Silence", displayname = "Jester.Crew.Talking.Silence", enabled = true } },
            { "Jester.Crew.Ejection.WSO", new CommandInfo { uniqueid = 24066, category = CommandCategories.WSO, name = "Jester.Crew.Ejection.WSO", displayname = "Jester.Crew.Ejection.WSO", enabled = true } },
            { "Jester.Crew.Ejection.Both", new CommandInfo { uniqueid = 24067, category = CommandCategories.WSO, name = "Jester.Crew.Ejection.Both", displayname = "Jester.Crew.Ejection.Both", enabled = true } },
            { "Jester.Crew.Countermeasures.Manual", new CommandInfo { uniqueid = 24068, category = CommandCategories.WSO, name = "Jester.Crew.Countermeasures.Manual", displayname = "Jester.Crew.Countermeasures.Manual", enabled = true } },
            { "Jester.Crew.Countermeasures.Jester", new CommandInfo { uniqueid = 24069, category = CommandCategories.WSO, name = "Jester.Crew.Countermeasures.Jester", displayname = "Jester.Crew.Countermeasures.Jester", enabled = true } },
            // Additional WSO commands can be added here within the reserved range (24000 - 24998)
            { "wMsgWSOCmndsMaximum", new CommandInfo { uniqueid = 24999, name = "wMsgWSOCmndsMaximum", displayname = "WSO Commands Max", enabled = true } },
         };

    }    
}
