using System.Collections.Generic;

namespace VAICOM.WSO
{
    public static class WSOCommandMappings
    {
        // Map WSO commands to their proxy API calls
        public static readonly Dictionary<string, (string category, string action, string value, bool valueRequired)> CommandMap = new Dictionary<string, (string, string, string, bool)>
        {
            { "wMsgWSO_ReportSpeed", ("select", "report_speed", "", false) },
            { "wMsgWSO_ToggleRadar", ("select", "toggle_radar", "", false) },
            { "wMsgWSO_SetChaffMode", ("select", "set_chaff_mode", "MULT", true) },
            { "wMsgWSO_Lantirn_Designate", ("select", "lantirn_designate", "", false) },
            { "wMsgWSO_Lantirn_Undesignate", ("select", "lantirn_undesignate", "", false) },
            { "wMsgWSO_Radar_GoSilent", ("select", "radar_go_silent", "", false) },
            { "wMsgWSO_Radar_GoActive", ("select", "radar_go_active", "", false) },
            { "wMsgWSO_Radio_SetManualFrequency", ("select", "radio_manual_freq_text", "", true) },
            { "wMsgWSO_Radio_SelectCommChannel", ("select", "radio_comm_chan", "", true) },
            { "wMsgWSO_Radio_SelectAuxChannel", ("select", "radio_aux_chan", "", true) },
            { "wMsgWSO_Radio_TuneATC", ("select", "radio_tune_atc", "", true) },
            { "wMsgWSO_Radio_SelectMode", ("select", "radio_mode", "", true) },
            { "wMsgWSO_Radar_Operation_Active", ("select", "radar_op", "active", true) },
            { "wMsgWSO_Radar_Operation_Standby", ("select", "radar_op", "standby", true) },
            { "wMsgWSO_Radar_AutoFocus_On", ("select", "radar_auto_focus", "on", true) },
            { "wMsgWSO_Radar_AutoFocus_Off", ("select", "radar_auto_focus", "off", true) },
            { "wMsgWSO_Radar_IFF_Both", ("select", "radar_iff", "both", true) },
            { "wMsgWSO_Radar_IFF_APX76", ("select", "radar_iff", "apx_76", true) },
            { "wMsgWSO_Radar_Boresight_EnterBST", ("select", "radar_enter_bst", "", false) },
            { "wMsgWSO_Radar_Boresight_Wide", ("select", "radar_bst_aspect", "wide", true) },
            { "wMsgWSO_Radar_Boresight_Nose", ("select", "radar_bst_aspect", "nose", true) },
            { "wMsgWSO_Radar_Boresight_Forward", ("select", "radar_bst_aspect", "fwd", true) },
            { "wMsgWSO_Radar_Boresight_Aft", ("select", "radar_bst_aspect", "aft", true) },
            { "wMsgWSO_Radar_Boresight_Tail", ("select", "radar_bst_aspect", "tail", true) },
            { "wMsgWSO_Radar_ScanElevation_Center", ("select", "radar_scan_zone", "30;0;relative", true) },
            { "wMsgWSO_Radar_ScanElevation_Low", ("select", "radar_scan_zone", "30;-3.5;relative", true) },
            { "wMsgWSO_Radar_ScanElevation_MidLow", ("select", "radar_scan_zone", "30;-5;relative", true) },
            { "wMsgWSO_Radar_ScanElevation_FarLow", ("select", "radar_scan_zone", "30;-7.5;relative", true) },
            { "wMsgWSO_Radar_ScanElevation_CloseHigh", ("select", "radar_scan_zone", "30;3.5;relative", true) },
            { "wMsgWSO_Radar_ScanElevation_MidHigh", ("select", "radar_scan_zone", "30;5;relative", true) },
            { "wMsgWSO_Radar_ScanElevation_FarHigh", ("select", "radar_scan_zone", "30;7.5;relative", true) },
            { "wMsgWSO_Radar_ScanType_25Wide", ("select", "radar_display_range", "nm_25;wide", true) },
            { "wMsgWSO_Radar_ScanType_25Narrow", ("select", "radar_display_range", "nm_25;narrow", true) },
            { "wMsgWSO_Radar_ScanType_50Wide", ("select", "radar_display_range", "nm_50;wide", true) },
            { "wMsgWSO_Radar_ScanType_50Narrow", ("select", "radar_display_range", "nm_50;narrow", true) },
            { "wMsgWSO_Radar_FocusTarget", ("select", "radar_focus_targets_thinking", "", false) },
            { "wMsgWSO_Radar_LockTarget", ("select", "radar_lock_targets_thinking", "", false) },
            { "wMsgWSO_A2G_TVWeapons", ("select", "a2g_tv_feed", "weapons", true) },
            { "wMsgWSO_A2G_TVPaveSpike", ("select", "a2g_tv_feed", "pave_spike", true) },
            { "wMsgWSO_Navigation_GoToResume", ("select", "resume_flightplan_1", "", false) },
            { "wMsgWSO_Navigation_ResumeFlightPlan1Waypoint", ("select", "resume_flightplan_1", "", true) },
            { "wMsgWSO_Navigation_ResumeFlightPlan2Waypoint", ("select", "resume_flightplan_2", "", true) },
            { "wMsgWSO_Navigation_ResumeNextWaypoint", ("select", "resume_next_wpt", "", false) },
            { "wMsgWSO_Navigation_Holding_ActivateCurrentTurnPoint", ("select", "hold_curr_wpt", "", false) },
            { "wMsgWSO_Navigation_Holding_DeactivateCurrentTurnPoint", ("select", "hold_curr_wpt", "", false) },
            { "wMsgWSO_Navigation_Holding_ActivateFlightPlan1TurnPoint", ("select", "hold_flightplan_1", "", true) },
            { "wMsgWSO_Navigation_Holding_DeactivateFlightPlan1TurnPoint", ("select", "deactivate_hold_fp1", "", true) },
            { "wMsgWSO_Navigation_Holding_ActivateFlightPlan2TurnPoint", ("select", "hold_flightplan_2", "", true) },
            { "wMsgWSO_Navigation_Holding_DeactivateFlightPlan2TurnPoint", ("select", "deactivate_hold_fp2", "", true) },
            { "wMsgWSO_Navigation_Divert_Airfield", ("select", "divert_tgt1_lat_lon", "", true) },
            { "wMsgWSO_Navigation_Divert_Asset", ("select", "divert_tgt1_lat_lon", "", true) },
            { "wMsgWSO_Navigation_Divert_LatLong", ("select", "divert_tgt1_lat_lon", "", true) },
            { "wMsgWSO_Navigation_Designate_Waypoint", ("select", "designate_wpt", "", true) },
            { "wMsgWSO_Navigation_TACAN_SelectMode_Off", ("select", "nav_tacan_mode", "off", true) },
            { "wMsgWSO_Navigation_TACAN_SelectMode_R", ("select", "nav_tacan_mode", "r", true) },
            { "wMsgWSO_Navigation_TACAN_SelectMode_TR", ("select", "nav_tacan_mode", "tr", true) },
            { "wMsgWSO_Navigation_TACAN_SelectMode_AAR", ("select", "nav_tacan_mode", "aar", true) },
            { "wMsgWSO_Navigation_TACAN_SelectMode_AATR", ("select", "nav_tacan_mode", "aatr", true) },
            { "wMsgWSO_Navigation_TACAN_SelectChannel", ("select", "nav_tacan_chan_band", "", true) },
            { "wMsgWSO_Navigation_TACAN_TuneAsset", ("select", "nav_tacan_tr", "", true) },
            { "wMsgWSO_Navigation_TACAN_TuneStation", ("select", "nav_tacan_tr", "", true) },
            { "wMsgWSO_Navigation_RestartAlignment", ("select", "jester_realign_quick", "restart", true) },
            { "wMsgWSO_Systems_ChaffMode_Off", ("select", "systems_chaff", "off", true) },
            { "wMsgWSO_Systems_ChaffMode_Single", ("select", "systems_chaff", "single", true) },
            { "wMsgWSO_Systems_ChaffMode_Multiple", ("select", "systems_chaff", "multiple", true) },
            { "wMsgWSO_Systems_ChaffMode_Program", ("select", "systems_chaff", "program", true) },
            { "wMsgWSO_Systems_FlareMode_Off", ("select", "systems_flare", "off", true) },
            { "wMsgWSO_Systems_FlareMode_Single", ("select", "systems_flare", "single", true) },
            { "wMsgWSO_Systems_FlareMode_Program", ("select", "systems_flare", "program", true) },
            { "wMsgWSO_Systems_Jammer_Standby", ("select", "systems_jammer", "standby", true) },
            { "wMsgWSO_Systems_Jammer_Transmit", ("select", "systems_jammer", "xmit", true) },
            { "wMsgWSO_Systems_AVTR_Record", ("select", "systems_avtr_recorder", "record", true) },
            { "wMsgWSO_Systems_AVTR_Standby", ("select", "systems_avtr_recorder", "standby", true) },
            { "wMsgWSO_Systems_AVTR_Off", ("select", "systems_avtr_recorder", "off", true) },
            { "wMsgWSO_Crew_Presence_Auto", ("select", "crew_presence", "auto", true) },
            { "wMsgWSO_Crew_Presence_Force", ("select", "crew_presence", "enabled", true) },
            { "wMsgWSO_Crew_Presence_Disable", ("select", "crew_presence", "disabled", true) },
            { "wMsgWSO_Crew_Talking_Talk", ("select", "crew_talking", "talk", true) },
            { "wMsgWSO_Crew_Talking_Silence", ("select", "crew_talking", "silence", true) },
            { "wMsgWSO_Crew_Ejection_WSO", ("select", "crew_ejection", "wso", true) },
            { "wMsgWSO_Crew_Ejection_Both", ("select", "crew_ejection", "both", true) },
            { "wMsgWSO_Crew_Countermeasures_Manual", ("select", "crew_countermeasures", "manual", true) },
            { "wMsgWSO_Crew_Countermeasures_Jester", ("select", "crew_countermeasures", "jester", true) },            
            { "wMsgWSO_Systems_FlaresJettison", ("select", "systems_flares_jettison", "", false) },
            { "wMsgWSO_Systems_Countermeasures_Quantity", ("select", "systems_countermeasures_quantity", "", false) },
            { "wMsgWSO_Radar_FocusTarget_Direct", ("select", "radar_focus_target", "", false) },
            { "wMsgWSO_Radar_LockTarget_Direct", ("select", "radar_lock_target", "", false) },
            { "wMsgWSO_Radar_UnlockTarget", ("select", "radar_unlock_tgt", "", false) },
            { "wMsgWSO_A2G_PaveSpike_Ready", ("select", "pave_spike_op", "ready", true) },
            { "wMsgWSO_A2G_PaveSpike_Standby", ("select", "pave_spike_op", "standby", true) },
            { "wMsgWSO_A2G_PaveSpike_LockUnlockTargetAhead", ("select", "pave_spike_lock_unlock_tgt_ahead", "", false) },
            { "wMsgWSO_A2G_PaveSpike_LaserCode", ("select", "pave_spike_laser_code", "", true) },
            { "wMsgWSO_A2G_PaveSpike_LaserCode_Silent", ("select", "pave_spike_laser_code_silent", "", false) },

            // Ground Crew commands
            { "wMsgWSO_Ground_WheelChocks_Place", ("select", "wheel_chocks_place", "", false) },
            { "wMsgWSO_Ground_WheelChocks_Remove", ("select", "wheel_chocks_remove", "", false) },
            { "wMsgWSO_Ground_Power_Connect", ("select", "power_connect", "", false) },
            { "wMsgWSO_Ground_Power_Disconnect", ("select", "power_disconnect", "", false) },
            { "wMsgWSO_Ground_Air_ConnectRight", ("select", "air_connect_right", "", false) },
            { "wMsgWSO_Ground_Air_ConnectLeft", ("select", "air_connect_left", "", false) },
            { "wMsgWSO_Ground_Air_StartAirflow", ("select", "air_start_airflow", "", false) },
            { "wMsgWSO_Ground_Air_StopAirflow", ("select", "air_stop_airflow", "", false) },
            { "wMsgWSO_Ground_Air_Disconnect", ("select", "air_disconnect", "", false) },
            { "wMsgWSO_Ground_EngineStartCartridges_Load", ("select", "engine_start_cartridges_load", "", false) },
            { "wMsgWSO_Ground_EngineStartCartridges_Remove", ("select", "engine_start_cartridges_remove", "", false) },
            { "wMsgWSO_Ground_Ladder_Place", ("select", "ladder_place", "", false) },
            { "wMsgWSO_Ground_Ladder_Remove", ("select", "ladder_remove", "", false) },
            { "wMsgWSO_Ground_Steps_Extend", ("select", "steps_extend", "", false) },
            { "wMsgWSO_Ground_Steps_Retract", ("select", "steps_retract", "", false) },
            { "wMsgWSO_Ground_CommsCheck", ("select", "comms_check", "", false) },
            { "wMsgWSO_Ground_PitotCheck", ("select", "pitot_check", "", false) },
            { "wMsgWSO_Ground_SpoilerActuatorCheck", ("select", "spoiler_actuator_check", "", false) },
            { "wMsgWSO_Ground_FlightControlsCheck", ("select", "flight_controls_check", "", false) },
            { "wMsgWSO_Ground_AriCheck", ("select", "ari_check", "", false) },
            { "wMsgWSO_Ground_StabAugCheck", ("select", "stab_aug_check", "", false) },
            { "wMsgWSO_Ground_TrimCheck", ("select", "trim_check", "", false) },
            { "wMsgWSO_Ground_Cancel", ("select", "cancel", "", false) },

            // Jester startup INS alignment
            { "wMsgWSO_INSAlignment_StartAlignment", ("select", "jester_start_alignment", "start", true) },
            { "wMsgWSO_INSAlignment_FullAlignment", ("select", "full_alignment", "", false) },
            { "wMsgWSO_INSAlignment_BathAlignment", ("select", "bath_alignment", "", false) },
            { "wMsgWSO_INSAlignment_StoredAlignment", ("select", "stored_alignment", "", false) },
            { "wMsgWSO_INSAlignment_Yes", ("select", "yes", "", false) },
            { "wMsgWSO_INSAlignment_No", ("select", "no", "", false) },
            { "wMsgWSO_INSAlignment_LetYouKnow", ("select", "let_you_know", "", false) },
            

            // Jester Contextual Menu response commands
            { "wMsgWSO_Context_Short", ("select", "context_action_short", "", false) },
            { "wMsgWSO_Context_Long", ("select", "context_action_long", "", false) },
            { "wMsgWSO_Context_Double", ("select", "context_action_double", "", false) },
        };
    }
}