using System.Collections.Generic;

namespace VAICOM.WSO
{
    public static class WSOCommandMappings
    {
        public enum InterfaceType
        {
            Context,
            Dialog,
            Wheel
        }

        // Map WSO commands to their proxy API calls
        public static readonly Dictionary<string, (InterfaceType type, string category, string action, string value, bool valueRequired)> CommandMap = new Dictionary<string, (InterfaceType, string, string, string, bool)>
        {
            { "wMsgWSO_ReportSpeed",                                            (InterfaceType.Wheel, "select", "report_speed", "", false) },
            { "wMsgWSO_ToggleRadar",                                            (InterfaceType.Wheel, "select", "toggle_radar", "", false) },
            { "wMsgWSO_SetChaffMode",                                           (InterfaceType.Wheel, "select", "set_chaff_mode", "MULT", true) },
            { "wMsgWSO_Lantirn_Designate",                                      (InterfaceType.Wheel, "select", "lantirn_designate", "", false) },
            { "wMsgWSO_Lantirn_Undesignate",                                    (InterfaceType.Wheel, "select", "lantirn_undesignate", "", false) },
            { "wMsgWSO_Radar_GoSilent",                                         (InterfaceType.Wheel, "select", "radar_go_silent", "", false) },
            { "wMsgWSO_Radar_GoActive",                                         (InterfaceType.Wheel, "select", "radar_go_active", "", false) },
            { "wMsgWSO_Radio_SetManualFrequency",                               (InterfaceType.Wheel, "select", "radio_manual_freq_text", "", true) },
            { "wMsgWSO_Radio_SelectCommChannel",                                (InterfaceType.Wheel, "select", "radio_comm_chan", "", true) },
            { "wMsgWSO_Radio_SelectAuxChannel",                                 (InterfaceType.Wheel, "select", "radio_aux_chan", "", true) },
            { "wMsgWSO_Radio_TuneATC",                                          (InterfaceType.Wheel, "select", "radio_tune_atc", "", true) },
            { "wMsgWSO_Radio_SelectMode",                                       (InterfaceType.Wheel, "select", "radio_mode", "", true) },
            { "wMsgWSO_Radar_Operation_Active",                                 (InterfaceType.Wheel, "select", "radar_op", "active", true) },
            { "wMsgWSO_Radar_Operation_Standby",                                (InterfaceType.Wheel, "select", "radar_op", "standby", true) },
            { "wMsgWSO_Radar_AutoFocus_On",                                     (InterfaceType.Wheel, "select", "radar_auto_focus", "on", true) },
            { "wMsgWSO_Radar_AutoFocus_Off",                                    (InterfaceType.Wheel, "select", "radar_auto_focus", "off", true) },
            { "wMsgWSO_Radar_IFF_Both",                                         (InterfaceType.Wheel, "select", "radar_iff", "both", true) },
            { "wMsgWSO_Radar_IFF_APX76",                                        (InterfaceType.Wheel, "select", "radar_iff", "apx_76", true) },
            { "wMsgWSO_Radar_Boresight_EnterBST",                               (InterfaceType.Wheel, "select", "radar_enter_bst", "", false) },
            { "wMsgWSO_Radar_Boresight_Wide",                                   (InterfaceType.Wheel, "select", "radar_bst_aspect", "wide", true) },
            { "wMsgWSO_Radar_Boresight_Nose",                                   (InterfaceType.Wheel, "select", "radar_bst_aspect", "nose", true) },
            { "wMsgWSO_Radar_Boresight_Forward",                                (InterfaceType.Wheel, "select", "radar_bst_aspect", "fwd", true) },
            { "wMsgWSO_Radar_Boresight_Aft",                                    (InterfaceType.Wheel, "select", "radar_bst_aspect", "aft", true) },
            { "wMsgWSO_Radar_Boresight_Tail",                                   (InterfaceType.Wheel, "select", "radar_bst_aspect", "tail", true) },
            { "wMsgWSO_Radar_ScanElevation_Center",                             (InterfaceType.Wheel, "select", "radar_scan_zone", "30;0;relative", true) },
            { "wMsgWSO_Radar_ScanElevation_Low",                                (InterfaceType.Wheel, "select", "radar_scan_zone", "30;-3.5;relative", true) },
            { "wMsgWSO_Radar_ScanElevation_MidLow",                             (InterfaceType.Wheel, "select", "radar_scan_zone", "30;-5;relative", true) },
            { "wMsgWSO_Radar_ScanElevation_FarLow",                             (InterfaceType.Wheel, "select", "radar_scan_zone", "30;-7.5;relative", true) },
            { "wMsgWSO_Radar_ScanElevation_CloseHigh",                          (InterfaceType.Wheel, "select", "radar_scan_zone", "30;3.5;relative", true) },
            { "wMsgWSO_Radar_ScanElevation_MidHigh",                            (InterfaceType.Wheel, "select", "radar_scan_zone", "30;5;relative", true) },
            { "wMsgWSO_Radar_ScanElevation_FarHigh",                            (InterfaceType.Wheel, "select", "radar_scan_zone", "30;7.5;relative", true) },
            { "wMsgWSO_Radar_ScanType_25Wide",                                  (InterfaceType.Wheel, "select", "radar_display_range", "nm_25;wide", true) },
            { "wMsgWSO_Radar_ScanType_25Narrow",                                (InterfaceType.Wheel, "select", "radar_display_range", "nm_25;narrow", true) },
            { "wMsgWSO_Radar_ScanType_50Wide",                                  (InterfaceType.Wheel, "select", "radar_display_range", "nm_50;wide", true) },
            { "wMsgWSO_Radar_ScanType_50Narrow",                                (InterfaceType.Wheel, "select", "radar_display_range", "nm_50;narrow", true) },
            { "wMsgWSO_Radar_FocusTarget",                                      (InterfaceType.Wheel, "select", "radar_focus_target", "", true) },
            { "wMsgWSO_Radar_LockTarget",                                       (InterfaceType.Wheel, "select", "radar_lock_target", "", true) },
            { "wMsgWSO_Radar_FocusTarget_Direct",                               (InterfaceType.Wheel, "select", "radar_focus_target", "", true) }, //Focus IDX1 target
            { "wMsgWSO_Radar_LockTarget_Direct",                                (InterfaceType.Wheel, "select", "radar_lock_target", "", true) }, //Lock IDX1 target
            { "wMsgWSO_Radar_UnlockTarget",                                     (InterfaceType.Wheel, "select", "radar_unlock_tgt", "", false) },
            { "wMsgWSO_A2G_TVWeapons",                                          (InterfaceType.Wheel, "select", "a2g_tv_feed", "weapons", true) },
            { "wMsgWSO_A2G_TVPaveSpike",                                        (InterfaceType.Wheel, "select", "a2g_tv_feed", "pave_spike", true) },
            { "wMsgWSO_Navigation_GoToResume",                                  (InterfaceType.Wheel, "select", "resume_flightplan_1", "", false) },
            { "wMsgWSO_Navigation_ResumeFlightPlan1Waypoint",                   (InterfaceType.Wheel, "select", "resume_flightplan_1", "", true) },
            { "wMsgWSO_Navigation_ResumeFlightPlan2Waypoint",                   (InterfaceType.Wheel, "select", "resume_flightplan_2", "", true) },
            { "wMsgWSO_Navigation_ResumeNextWaypoint",                          (InterfaceType.Wheel, "select", "resume_next_wpt", "", false) },
            { "wMsgWSO_Navigation_Holding_ActivateCurrentTurnPoint",            (InterfaceType.Wheel, "select", "hold_curr_wpt", "", false) },
            { "wMsgWSO_Navigation_Holding_DeactivateCurrentTurnPoint",          (InterfaceType.Wheel, "select", "hold_curr_wpt", "", false) },
            { "wMsgWSO_Navigation_Holding_ActivateFlightPlan1TurnPoint",        (InterfaceType.Wheel, "select", "hold_flightplan_1", "", true) },
            { "wMsgWSO_Navigation_Holding_DeactivateFlightPlan1TurnPoint",      (InterfaceType.Wheel, "select", "deactivate_hold_fp1", "", true) },
            { "wMsgWSO_Navigation_Holding_ActivateFlightPlan2TurnPoint",        (InterfaceType.Wheel, "select", "hold_flightplan_2", "", true) },
            { "wMsgWSO_Navigation_Holding_DeactivateFlightPlan2TurnPoint",      (InterfaceType.Wheel, "select", "deactivate_hold_fp2", "", true) },
            { "wMsgWSO_Navigation_Divert_LatLong",                              (InterfaceType.Wheel, "select", "divert_tgt1_lat_lon", "", true) },
            { "wMsgWSO_Navigation_Designate_Waypoint",                          (InterfaceType.Wheel, "select", "designate_wpt", "", true) },
            { "wMsgWSO_Navigation_TACAN_SelectMode_Off",                        (InterfaceType.Wheel, "select", "nav_tacan_mode", "off", true) },
            { "wMsgWSO_Navigation_TACAN_SelectMode_R",                          (InterfaceType.Wheel, "select", "nav_tacan_mode", "r", true) },
            { "wMsgWSO_Navigation_TACAN_SelectMode_TR",                         (InterfaceType.Wheel, "select", "nav_tacan_mode", "tr", true) },
            { "wMsgWSO_Navigation_TACAN_SelectMode_AAR",                        (InterfaceType.Wheel, "select", "nav_tacan_mode", "aar", true) },
            { "wMsgWSO_Navigation_TACAN_SelectMode_AATR",                       (InterfaceType.Wheel, "select", "nav_tacan_mode", "aatr", true) },
            { "wMsgWSO_Navigation_TACAN_SelectChannel",                         (InterfaceType.Wheel, "select", "nav_tacan_chan_band", "", true) },
            { "wMsgWSO_Navigation_TACAN_TuneAsset",                             (InterfaceType.Wheel, "select", "nav_tacan_tr", "", true) },
            { "wMsgWSO_Navigation_TACAN_TuneStation",                           (InterfaceType.Wheel, "select", "nav_tacan_tr", "", true) },
            { "wMsgWSO_Navigation_RestartAlignment",                            (InterfaceType.Wheel, "select", "jester_realign_quick", "restart", true) },
            { "wMsgWSO_Systems_ChaffMode_Off",                                  (InterfaceType.Wheel, "select", "systems_chaff", "off", true) },
            { "wMsgWSO_Systems_ChaffMode_Single",                               (InterfaceType.Wheel, "select", "systems_chaff", "single", true) },
            { "wMsgWSO_Systems_ChaffMode_Multiple",                             (InterfaceType.Wheel, "select", "systems_chaff", "multiple", true) },
            { "wMsgWSO_Systems_ChaffMode_Program",                              (InterfaceType.Wheel, "select", "systems_chaff", "program", true) },
            { "wMsgWSO_Systems_FlareMode_Off",                                  (InterfaceType.Wheel, "select", "systems_flare", "off", true) },
            { "wMsgWSO_Systems_FlareMode_Single",                               (InterfaceType.Wheel, "select", "systems_flare", "single", true) },
            { "wMsgWSO_Systems_FlareMode_Program",                              (InterfaceType.Wheel, "select", "systems_flare", "program", true) },
            { "wMsgWSO_Systems_Jammer_Standby",                                 (InterfaceType.Wheel, "select", "systems_jammer", "standby", true) },
            { "wMsgWSO_Systems_Jammer_Transmit",                                (InterfaceType.Wheel, "select", "systems_jammer", "xmit", true) },
            { "wMsgWSO_Systems_AVTR_Record",                                    (InterfaceType.Wheel, "select", "systems_avtr_recorder", "record", true) },
            { "wMsgWSO_Systems_AVTR_Standby",                                   (InterfaceType.Wheel, "select", "systems_avtr_recorder", "standby", true) },
            { "wMsgWSO_Systems_AVTR_Off",                                       (InterfaceType.Wheel, "select", "systems_avtr_recorder", "off", true) },
            { "wMsgWSO_Crew_Presence_Auto",                                     (InterfaceType.Wheel, "select", "crew_presence", "auto", true) },
            { "wMsgWSO_Crew_Presence_Force",                                    (InterfaceType.Wheel, "select", "crew_presence", "enabled", true) },
            { "wMsgWSO_Crew_Presence_Disable",                                  (InterfaceType.Wheel, "select", "crew_presence", "disabled", true) },
            { "wMsgWSO_Crew_Talking_Talk",                                      (InterfaceType.Wheel, "select", "crew_talking", "talk", true) },
            { "wMsgWSO_Crew_Talking_Silence",                                   (InterfaceType.Wheel, "select", "crew_talking", "silence", true) },
            { "wMsgWSO_Crew_Ejection_WSO",                                      (InterfaceType.Wheel, "select", "crew_ejection", "wso", true) },
            { "wMsgWSO_Crew_Ejection_Both",                                     (InterfaceType.Wheel, "select", "crew_ejection", "both", true) },
            { "wMsgWSO_Crew_Countermeasures_Manual",                            (InterfaceType.Wheel, "select", "crew_countermeasures", "manual", true) },
            { "wMsgWSO_Crew_Countermeasures_Jester",                            (InterfaceType.Wheel, "select", "crew_countermeasures", "jester", true) },            
            { "wMsgWSO_Crew_StartAlignment",                                    (InterfaceType.Wheel, "select", "jester_start_alignment", "start", true) },
            { "wMsgWSO_Crew_Shutdown",                                          (InterfaceType.Wheel, "select", "custom_shutdown", "start", true) },
            { "wMsgWSO_Crew_AltitudeMonitor_500",                               (InterfaceType.Wheel, "select", "vaicom_radalt_monitor", "500", true) },
            { "wMsgWSO_Crew_AltitudeMonitor_300",                               (InterfaceType.Wheel, "select", "vaicom_radalt_monitor", "300", true) },
            { "wMsgWSO_Crew_AltitudeMonitor_200",                               (InterfaceType.Wheel, "select", "vaicom_radalt_monitor", "200", true) },
            { "wMsgWSO_Crew_AltitudeMonitor_100",                               (InterfaceType.Wheel, "select", "vaicom_radalt_monitor", "100", true) },
            { "wMsgWSO_Crew_AltitudeMonitor_50",                                (InterfaceType.Wheel, "select", "vaicom_radalt_monitor", "50", true) },
            { "wMsgWSO_Crew_AltitudeMonitor_Off",                               (InterfaceType.Wheel, "select", "vaicom_radalt_monitor", "off", true) },
            { "wMsgWSO_Systems_FlaresJettison",                                 (InterfaceType.Wheel, "select", "systems_flares_jettison", "", false) },
            { "wMsgWSO_Systems_Countermeasures_Quantity",                       (InterfaceType.Wheel, "select", "systems_countermeasures_quantity", "", false) },
            { "wMsgWSO_A2G_PaveSpike_Ready",                                    (InterfaceType.Wheel, "select", "pave_spike_op", "ready", true) },
            { "wMsgWSO_A2G_PaveSpike_Standby",                                  (InterfaceType.Wheel, "select", "pave_spike_op", "standby", true) },
            { "wMsgWSO_A2G_PaveSpike_LaserCode",                                (InterfaceType.Wheel, "select", "pave_spike_laser_code", "", true) },

            // Ground Crew commands
            { "wMsgWSO_Ground_WheelChocks_Place",                               (InterfaceType.Wheel, "select", "wheel_chocks_place", "", false) },
            { "wMsgWSO_Ground_WheelChocks_Remove",                              (InterfaceType.Wheel, "select", "wheel_chocks_remove", "", false) },
            { "wMsgWSO_Ground_Power_Connect",                                   (InterfaceType.Wheel, "select", "power_connect", "", false) },
            { "wMsgWSO_Ground_Power_Disconnect",                                (InterfaceType.Wheel, "select", "power_disconnect", "", false) },
            { "wMsgWSO_Ground_Air_ConnectRight",                                (InterfaceType.Wheel, "select", "air_connect_right", "", false) },
            { "wMsgWSO_Ground_Air_ConnectLeft",                                 (InterfaceType.Wheel, "select", "air_connect_left", "", false) },
            { "wMsgWSO_Ground_Air_StartAirflow",                                (InterfaceType.Wheel, "select", "air_start_airflow", "", false) },
            { "wMsgWSO_Ground_Air_StopAirflow",                                 (InterfaceType.Wheel, "select", "air_stop_airflow", "", false) },
            { "wMsgWSO_Ground_Air_Disconnect",                                  (InterfaceType.Wheel, "select", "air_disconnect", "", false) },
            { "wMsgWSO_Ground_EngineStartCartridges_Load",                      (InterfaceType.Wheel, "select", "engine_start_cartridges_load", "", false) },
            { "wMsgWSO_Ground_EngineStartCartridges_Remove",                    (InterfaceType.Wheel, "select", "engine_start_cartridges_remove", "", false) },
            { "wMsgWSO_Ground_CMS_ChaffSingle",                                 (InterfaceType.Wheel, "select", "cms_dispenser_cs", "", false) },
            { "wMsgWSO_Ground_CMS_ChaffDouble",                                 (InterfaceType.Wheel, "select", "cms_dispenser_cd", "", false) },
            { "wMsgWSO_Ground_IFF_InsertM4Codes",                               (InterfaceType.Wheel, "select", "iff_insert_m4_codes", "", false) },
            { "wMsgWSO_Ground_Ladder_Place",                                    (InterfaceType.Wheel, "select", "ladder_place", "", false) },
            { "wMsgWSO_Ground_Ladder_Remove",                                   (InterfaceType.Wheel, "select", "ladder_remove", "", false) },
            { "wMsgWSO_Ground_Steps_Extend",                                    (InterfaceType.Wheel, "select", "steps_extend", "", false) },
            { "wMsgWSO_Ground_Steps_Retract",                                   (InterfaceType.Wheel, "select", "steps_retract", "", false) },
            { "wMsgWSO_Ground_CommsCheck",                                      (InterfaceType.Wheel, "select", "comms_check", "", false) },
            { "wMsgWSO_Ground_PitotCheck",                                      (InterfaceType.Wheel, "select", "pitot_check", "", false) },
            { "wMsgWSO_Ground_SpoilerActuatorCheck",                            (InterfaceType.Wheel, "select", "spoiler_actuator_check", "", false) },
            { "wMsgWSO_Ground_FlightControlsCheck",                             (InterfaceType.Wheel, "select", "flight_controls_check", "", false) },
            { "wMsgWSO_Ground_AriCheck",                                        (InterfaceType.Wheel, "select", "ari_check", "", false) },
            { "wMsgWSO_Ground_StabAugCheck",                                    (InterfaceType.Wheel, "select", "stab_aug_check", "", false) },
            { "wMsgWSO_Ground_TrimCheck",                                       (InterfaceType.Wheel, "select", "trim_check", "", false) },
            { "wMsgWSO_Ground_Cancel",                                          (InterfaceType.Wheel, "select", "cancel", "", false) },

            // Jester startup INS alignment dialog responses
            { "wMsgWSO_INSAlignment_FullAlignment",                             (InterfaceType.Dialog, "action", "full_alignment", "", false) },
            { "wMsgWSO_INSAlignment_BathAlignment",                             (InterfaceType.Dialog, "action", "bath_alignment", "", false) },
            { "wMsgWSO_INSAlignment_StoredAlignment",                           (InterfaceType.Dialog, "action", "stored_alignment", "", false) },
            { "wMsgWSO_INSAlignment_Yes",                                       (InterfaceType.Dialog, "action", "yes", "", false) },
            { "wMsgWSO_INSAlignment_No",                                        (InterfaceType.Dialog, "action", "no", "", false) },
            { "wMsgWSO_INSAlignment_LetYouKnow",                                (InterfaceType.Dialog, "action", "let_you_know", "", false) },

            // Jester mission altitude dialog responses
            { "wMsgWSO_Altitude_Negative",                                      (InterfaceType.Dialog, "action", "say_roger", "", false) },
            { "wMsgWSO_Altitude_GoingBelow50",                                  (InterfaceType.Dialog, "action", "dlg_below_50", "", false) },
            { "wMsgWSO_Altitude_GoingBelow100",                                 (InterfaceType.Dialog, "action", "dlg_below_100", "", false) },
            { "wMsgWSO_Altitude_GoingBelow150",                                 (InterfaceType.Dialog, "action", "dlg_below_150", "", false) },
            { "wMsgWSO_Altitude_GoingBelow200",                                 (InterfaceType.Dialog, "action", "dlg_below_200", "", false) },
            
            // Jester fuel dialog responses.
            { "wMsgWSO_Fuel_FuelIsGood",                                        (InterfaceType.Dialog, "action", "fuel_good", "", false) },
            { "wMsgWSO_Fuel_FuelIsLow",                                         (InterfaceType.Dialog, "select_option", "select_dialog_option", "Fuel is low", true) },
            { "wMsgWSO_Fuel_RemainOnMission",                                   (InterfaceType.Dialog, "action", "fuel_remain_on_mission", "", false) },
            { "wMsgWSO_Fuel_AirfieldOptions",                                   (InterfaceType.Dialog, "select_option", "show_dialog_options", "Divert to Airfield", true) },
            { "wMsgWSO_Fuel_TankerOptions",                                     (InterfaceType.Dialog, "select_option", "show_dialog_options", "Rejoin with Tanker", true) },
            { "wMsgWSO_Fuel_RefuelAtAirfield",                                  (InterfaceType.Dialog, "action", "", "", false) },

            // Jester Contextual Menu response commands
            { "wMsgWSO_Context_Short",                                          (InterfaceType.Context, "select", "context_action_short", "", false) },
            { "wMsgWSO_Context_Long",                                           (InterfaceType.Context, "select", "context_action_long", "", false) },
            { "wMsgWSO_Context_Double",                                         (InterfaceType.Context, "select", "context_action_double", "", false) },
        };
    }
}