using System;
using System.Collections.Generic;

namespace VAICOM
{
    namespace Database
    {

        public static partial class Labels
        {

            public static Dictionary<string, string> airecipients = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {

                { "",                       " "                     },

                { "Undefined",              "Undefined"             },

                { "flight",                 "Flight"                },
                { "element",                "Element"               },
                { "wingman1",               "Wingman 1"             },
                { "wingman2",               "Wingman 2"             },
                { "wingman3",               "Wingman 3"             },
                { "wingman4",               "Wingman 4"             },

                { "jtac",                   "JTAC"                  },

                { "axeman",                 "Axeman"                },
                { "darknight",              "Darknight"             },
                { "eyeball",                "Eyeball"               },
                { "finger",                 "Finger"                },
                { "firefly",                "Firefly"               },
                { "moonbeam",               "Moonbeam"              },
                { "playboy",                "Playboy"               },
                { "pointer",                "Pointer"               },
                { "warrior",                "Warrior"               },
                { "whiplash",               "Whiplash"              },

                { "pinpoint",               "Pinpoint"              },
                { "ferret",                 "Ferret"                },
                { "shaba",                  "Shaba"                 },
                { "hammer",                 "Hammer"                },
                { "jaguar",                 "Jaguar"                },
                { "deathstar",              "Deathstar"             },
                { "anvil",                  "Anvil"                 },
                { "mantis",                 "Mantis"                },
                { "badger",                 "Badger"                },

                { "boar",                   "Boar"                  },
                { "chevy",                  "Chevy"                 },
                { "colt",                   "Colt"                  },
                { "dodge",                  "Dodge"                 },
                { "enfield",                "Enfield"               },
                { "ford",                   "Ford"                  },
                { "hawg",                   "Hawg"                  },
                { "pig",                    "Pig"                   },
                { "pontiac",                "Pontiac"               },
                { "springfield",            "Springfield"           },
                { "tusk",                   "Tusk"                  },
                { "uzi",                    "Uzi"                   },

                { "nearestjtac",            "Nearest JTAC"          },

                // ATC general

                { "atc",                    "Air Traffic Controller" },
                { "nearestairfield",        "Nearest Airfield"      },
                //{ "alternateatc",           "Alternate Airfield"    },
                
                
                // Caucuases map
                
                { "Anapa-Vityazevo",        "Anapa-Vityazevo"       },
                { "Batumi",                 "Batumi"                },
                { "Beslan",                 "Beslan"                },
                { "Gelendzhik",             "Gelendzhik"            },
                { "Gudauta",                "Gudauta"               },
                { "Kobuleti",               "Kobuleti"              },
                { "Krasnodar-Center",       "Krasnodar-Center"      },
                { "Krasnodar-Pashkovsky",   "Krasnodar-Pashkovsky"  },
                { "Krymsk",                 "Krymsk"                },
                { "Kutaisi",                "Kutaisi"               },
                { "Maykop-Khanskaya",       "Maykop-Khanskaya"      },
                { "Mineralnye Vody",        "Mineralnye Vody"       },
                { "Mozdok",                 "Mozdok"                },
                { "Nalchik",                "Nalchik"               },
                { "Novorossiysk",           "Novorossiysk"          },
                { "Senaki-Kolkhi",          "Senaki-Kolkhi"         },
                { "Sochi-Adler",            "Sochi-Adler"           },
                { "Soganlug",               "Soganlug"              },
                { "Sukhumi-Babushara",      "Sukhumi-Babushara"     },
                { "Tbilisi-Lochini",        "Tbilisi-Lochini"       },
                { "Vaziani",                "Vaziani"               },
                { "wAIUnitATCCaucasusNull", "wAIUnitATCCaucasusNull"},

                // Marianas map

                { "Andersen AFB",               "Andersen AFB"             },
                { "Antonio B. Won Pat Intl",    "Antonio B. Won Pat Intl"  },
                { "Rota Intl",                  "Rota Intl"                },
                { "Saipan Intl",                "Saipan Intl"              },
                { "Tinian Intl",                "Tinian Intl"              },

                // Marianas WWII map

                { "Agana",                     "Agana"                  },
                { "Airfield 3",                "Airfield 3"             },
                { "Charon Kanoa",              "Charon Kanoa"           },
                { "Gurguan Point",             "Gurguan Point"          },
                { "Isley",                     "Isley"                  },
                { "Kagman",                    "Kagman"                 },
                { "Marpi",                     "Marpi"                  },
                { "Orote",                     "Orote"                  },
                { "Pagan",                     "Pagan"                  },
                { "Rota",                      "Rota"                   },
                { "Ushi",                      "Ushi"                   },
                
                // Nevanda map

                { "Boulder City",           "Boulder City"           },
                { "Creech",                 "Creech"                 },
                { "Groom Lake",             "Groom Lake"             },
                { "Henderson Executive",    "Henderson Executive"    },
                { "Laughlin",               "Laughlin"               },
                { "McCarran International", "McCarran International" },
                { "Nellis",                 "Nellis"                 },
                { "North Las Vegas",        "North Las Vegas"        },
                { "Tonopah Test Range",     "Tonopah Test Range"     },

                // Normanday map

                { "Azeville",               "Azeville"                      },
                { "Bazenville",             "Bazenville"                    },
                { "Beny-sur-Mer",           "Beny-sur-Mer"                  },
                { "Biniville",              "Biniville"                     },
                { "Brucheville",            "Brucheville"                   },
                { "Cardonville",            "Cardonville"                   },
                { "Chailey",                "Chailey"                       },
                { "Chippelle",              "Chippelle"                     },
                { "Cretteville",            "Cretteville"                   },
                { "Cricqueville-en-Bessin", "Cricqueville-en-Bessin"        },
                { "Deux Jumeaux",           "Deux Jumeaux"                  },
                { "Evreux",                 "Evreux"                        },
                { "Forde",                  "Forde"                         },
                { "Funtington",             "Funtington"                    },
                { "Lantheuil",              "Lantheuil"                     },
                { "Le Molay",               "Le Molay"                      },
                { "Lessay",                 "Lessay"                        },
                { "Longues-sur-Mer",        "Longues-sur-Mer"               },
                { "Maupertus",              "Maupertus"                     },
                { "Meautis",                "Meautis"                       },
                { "Needs Oar Point",        "Needs Oar Point"               },
                { "Picauville",             "Picauville"                    },
                { "Saint Pierre du Mont",   "Saint Pierre du Mont"          },
                { "Sainte-Croix-sur-Mer",   "Sainte-Croix-sur-Mer"          },
                { "Sainte-Laurent-sur-Mer", "Sainte-Laurent-sur-Mer"        },
                { "Sommervieu",             "Sommervieu"                    },
                { "Tangmere",               "Tangmere"                      },

                // Persian Gulf Map

                { "Abu Dhabi Intl",         "Abu Dhabi Intl"                },
                { "Abu Musa Island",        "Abu Musa Island"               },
                { "Al Ain Intl",            "Al Ain Intl"                   },
                { "Al Dhafra AFB",          "Al Dhafra AFB"                 },
                { "Al Maktoum Intl",        "Al Maktoum Intl"               },
                { "Al Minhad AFB",          "Al Minhad AFB"                 },
                { "Al-Bateen",              "Al-Bateen"                     },
                { "Bandar Abbas Intl",      "Bandar Abbas Intl"             },
                { "Bandar Lengeh",          "Bandar Lengeh"                 },
                { "Bandar-e-Jask",          "Bandar-e-Jask"                 },
                { "Dubai Intl",             "Dubai Intl"                    },
                { "Fujairah Intl",          "Fujairah Intl"                 },
                { "Havadarya",              "Havadarya"                     },
                { "Jiroft",                 "Jiroft"                        },
                { "Kerman",                 "Kerman"                        },
                { "Khasab",                 "Khasab"                        },
                { "Kish Intl",              "Kish Intl"                     },
                { "Lar",                    "Lar"                           },
                { "Lavan Island",           "Lavan Island"                  },
                { "Liwa AFB",               "Liwa AFB"                      },
                { "Qeshm Island",           "Qeshm Island"                  },
                { "Ras Al Khaimah Intl",    "Ras Al Khaimah Intl"           },
                { "Sas Al Nakheel",         "Sas Al Nakheel"                },
                { "Sharjah Intl",           "Sharjah Intl"                  },
                { "Shiraz Intl",            "Shiraz Intl"                   },
                { "Sir Abu Nuayr",          "Sir Abu Nuayr"                 },
                { "Sirri Island",           "Sirri Island"                  },

                //Channel map
                { "Abbeville Drucat",       "Abbeville Drucat" },
                { "Detling",                "Detling" },
                { "Dunkirk Mardyck",        "Dunkirk Mardyck" },
                { "Hawkinge",               "Hawkinge" },
                { "High Halden",            "High Halden" },
                { "Lympne",                 "Lympne" },
                { "Manston",                "Manston" },
                { "Merville Calonne",       "Merville Calonne" },
                { "Saint Omer Longuenesse", "Saint Omer Longuenesse" },

                // Syria map

                { "Abu al-Duhur",           "Abu al-Duhur"          },
                { "Adana Sakirpasa",        "Adana Sakirpasa"       },
                { "Adiyaman",               "Adiyaman"              },
                { "Akrotiri",               "Akrotiri"              },
                { "Al Qusayr",              "Al Qusayr"             },
                { "Al-Dumayr",              "Al-Dumayr"             },
                { "Aleppo",                 "Aleppo"                },
                { "An Nasiriyah",           "An Nasiriyah"          },
                { "At Tanf",                "At Tanf"               },
                { "Bassel Al-Assad",        "Bassel Al-Assad"       },
                { "Beirut-Rafic Hariri",    "Beirut-Rafic Hariri"   },
                { "Chukurova",              "Chukurova"             },
                { "Damascus",               "Damascus"              }, //new additions
                { "Deir ez-Zor",            "Deir ez-Zor"           },
                { "Diyarbakir",             "Diyarbakir"            },
                { "Ercan",                  "Ercan"                 },
                { "Eyn Shemer",             "Eyn Shemer"            },
                { "Gaziantep",              "Gaziantep"             },
                { "Gazipasa",               "Gazipasa"              },
                { "H3",                     "H3"                    },
                { "H3 Northwest",           "H3 Northwest"          },
                { "H3 Southwest",           "H3 Southwest"          },
                { "H4",                     "H4"                    },
                { "Haifa",                  "Haifa"                 },
                { "Hatay",                  "Hatay"                 },
                { "Herzliya",               "Herzliya"              },
                { "Incirlik",               "Incirlik"              },
                { "Jirah",                  "Jirah"                 },
                { "Khalkhalah",             "Khalkhalah"            },
                { "King Abdullah II",       "King Abdullah II"      },
                { "King Hussein Air College",  "King Hussein Air College"  },
                { "Kiryat Shmona",          "Kiryat Shmona"         },
                { "Kuweires",               "Kuweires"              },
                { "Lakatamia",              "Lakatamia"             },
                { "Larnaca",                "Larnaca"               },
                { "Marj as Sultan North",   "Marj as Sultan North"  },
                { "Marj as Sultan South",   "Marj as Sultan South"  },
                { "Marj Ruhayyil",          "Marj Ruhayyil"         },
                { "Marka",                  "Marka"                 },
                { "Megiddo",                "Megiddo"               },
                { "Mezzeh",                 "Mezzeh"                },
                { "Minakh",                 "Minakh"                },
                //{ "Tel Nof",                "Tel Nof"               }, //Already defined in Sinai
                //{ "Hatzor",                 "Hatzor"                }, //Already defined in Sinai
                //{ "Palmachim",              "Palmachim"             }, //Already defined in Sinai
                //{ "Ben Gurion",             "Ben Gurion"            }, //Already defined in Sinai
                { "Muwaffaq Salti",         "Muwaffaq Salti"        },
                { "Paphos",                 "Paphos"                },
                { "Prince Hassan",          "Prince Hassan"         },
                { "Qabr as Sitt",           "Qabr as Sitt"          },
                { "Ramat David",            "Ramat David"           },
                { "Rayak",                  "Rayak"                 },
                { "Rene Mouawad",           "Rene Mouawad"          },
                { "Taftanaz",               "Taftanaz"              },
                { "Tha'lah",                "Tha'lah"               },
                { "Wujah Al Hajar",         "Wujah Al Hajar"        },

                // Sinai map

                { "Abu Rudeis",             "Abu Rudeis"            },
                { "Abu Suwayr",             "Abu Suwayr"            },
                { "Al Bahr al Ahmar",                         "Al Bahr al Ahmar"                       },
                { "Al Ismailiyah",          "Al Ismailiyah"         },//
                { "Al Khatatbah",                            "Al Khatatbah"                           },
                { "Al Mansurah",            "Al Mansurah"           },
                { "Al Rahmaniyah Air Base",                  "Al Rahmaniyah Air Base"                 },
                { "As Salihiyah",           "As Salihiyah"          },
                { "AzZaqaziq",              "AzZaqaziq"             },
                { "Baluza",                 "Baluza"                },
                { "Ben-Gurion",             "Ben-Gurion"            },
                { "Beni Suef",             "Beni Suef"              },
                { "Bilbeis Air Base",       "Bilbeis Air Base"      },
                { "Bir Hasanah",            "Bir Hasanah"           },
                { "Birma Air Base",        "Birma Air Base"         },
                { "Borg El Arab International Airport",      "Borg El Arab International Airport"     },
                { "Cairo International Airport", "Cairo International Airport"  },
                { "Cairo West",             "Cairo West"            },
                { "Damascus Intl",                           "Damascus Intl"                          },
                { "Difarsuwar Airfield",    "Difarsuwar Airfield"   },//
                { "Ein Shamer",                              "Ein Shamer"                             },
                { "El Arish",               "El Arish"              },
                { "El Gora",                "El Gora"               },
                { "El Minya",              "El Minya"               },
                { "Fayed",                  "Fayed"                 },
                { "Gebel El Basur Air Base",                 "Gebel El Basur Air Base"                },
                { "Hatzerim",               "Hatzerim"              },
                { "Hatzor",                 "Hatzor"                },
                { "Hurghada International Airport",           "Hurghada International Airport"         },
                { "Inshas Airbase",         "Inshas Airbase"        },
                { "Jiyanklis Air Base",                      "Jiyanklis Air Base"                     },
                { "Kedem",                  "Kedem"                 },
                { "Kibrit Air Base",        "Kibrit Air Base"       },
                { "Kom Awshim",            "St Catherine"           },
                { "Melez",                  "Melez"                 },
                { "Nevatim",                "Nevatim"               },
                { "Ovda",                   "Ovda"                  },
                { "Palmachim",              "Palmachim"             },
                { "Quwaysina",             "Kom Awshim"             },
                { "Ramon Airbase",          "Ramon Airbase"         },
                { "Ramon International Airport",              "Ramon International Airport"            },
                { "Sde Dov",                "Sde Dov"               },
                { "Sharm El Sheikh International Airport",    "Sharm El Sheikh International Airport"  },
                { "St Catherine",           "St Catherine"          },
                { "Taba International Airport",              "Taba International Airport"             },
                { "Tel Nof",                "Tel Nof"               },
                { "Wadi Abu Rish",          "Wadi Abu Rish"         },
                { "Wadi al Jandali",        "Wadi al Jandali"       },

                // South Atlantic map

                { "Aerodromo De Tolhuin",   "Aerodromo De Tolhuin"  },
                { "Aerodromo O'Higgins",    "Aerodromo O'Higgins"   },
                { "Aeropuerto de Gobernador Gregores",  "Aeropuerto de Gobernador Gregores"    },
                { "Comandante Luis Piedrabuena",  "Comandante Luis Piedrabuena"        },
                { "El Calafate",            "El Calafate"           },
                { "Franco Bianco",          "Franco Bianco"         },
                { "Goose Green",            "Goose Green"           },
                { "Mount Pleasant",         "Mount Pleasant"        },
                { "Pampa Guanaco",          "Pampa Guanaco"         },
                { "Port Stanley",           "Port Stanley"          },
                { "Porvenir Airfield",      "Porvenir Airfield"     },
                { "Puerto Natales",         "Puerto Natales"        },
                { "Puerto Santa Cruz",      "Puerto Santa Cruz"     },
                { "Puerto Williams",        "Puerto Williams"       },
                { "Punta Arenas",           "Punta Arenas"          },
                { "Rio Chico",              "Rio Chico"             },
                { "Rio Gallegos",           "Rio Gallegos"          },
                { "Rio Grande",             "Rio Grande"            },
                { "Rio Turbio",             "Rio Turbio"            },
                { "San Carlos FOB",         "San Carlos FOB"        },
                { "San Julian",             "San Julian"            },
                { "Ushuaia",                "Ushuaia"               },
                { "Ushuaia Helo Port",      "Ushuaia Helo Port"     },

                // Kola Peninsular map

                { "Alakurtti",              "Alakurtti"             },
                { "Alta",                   "Alta"                  },
                { "Andoya",                 "Andoya"                },
                { "Banak",                  "Banak"                 },
                { "Bardufoss",              "Bardufoss"             },
                { "Bodo",                   "Bodo"                  },
                { "Enontekio",              "Enontekio"             },
                { "Evenes",                 "Evenes"                },
                { "Hosio",                  "Hosio"                 },
                { "Ivalo",                  "Ivalo"                 },
                { "Jokkmokk",               "Jokkmokk"              },
                { "Kalixfors",              "Kalixfors"             },
                { "Kallax",                 "Kallax"                },
                { "Kemi Torino",            "Kemi Torino"           },
                { "Kirkenes",               "Kirkenes"              },
                { "Kiruna",                 "Kiruna"                },
                { "Kittila",                "Kittila"               },
                { "Kuusamo",                "Kuusamo"               },
                { "Monchegorsk",            "Monchegorsk"           },
                { "Murmansk International", "Murmansk International"},
                { "Olenya",                 "Olenya"                },
                { "Rovaniemi",              "Rovaniemi"             },
                { "Severomorsk-1",          "Severomorsk-1"         },
                { "Severomorsk-3",          "Severomorsk-3"         },
                { "Sodankyla",              "Sodankyla"             },
                { "Vidsel",                 "Vidsel"                },
                { "Vuojarvi",               "Vuojarvi"              },
                
                // Afghanistan map
                    // South
                { "Bagram",                "Bagram"                 },
                { "Bamyan",                "Bamyan"                 },
                { "Bost",                   "Bost"                  },
                { "Camp Bastion",           "Camp Bastion"          },
                { "Camp Bastion Heliport",  "Camp Bastion Heliport" },
                { "Chaghcharan",            "Chaghcharan"           },
                { "Dwyer",                  "Dwyer"                 },
                { "Farah",                  "Farah"                 },
                { "Gardez",                "Gardez"                 },
                { "Ghazni Heliport",       "Ghazni Heliport"        },
                { "Herat",                  "Herat"                 },
                { "Jalalabad",             "Jalalabad"              },
                { "Kabul",                 "Kabul"                  },
                { "kandahar",               "kandahar"              },
                     // East
                { "Kandahar Heliport",      "Kandahar Heliport"     },
                { "Khost",                 "Khost"                  },
                { "Khost Heliport",        "Khost Heliport"         },
                { "Mary",                  "Mary"                                },
                { "Mary North",            "Mary North"                          },
                { "Maymana Zahiraddin Faryabi", "Maymana Zahiraddin Faryabi"     },
                { "Nimroz",                 "Nimroz"                },
                { "Qala i Naw",             "Qala i Naw"            },
                { "Sharan",                "Sharan"                 },
                { "Shindand",               "Shindand"              },
                { "Shindand Heliport",      "Shindand Heliport"     },
                { "Tarinkot",               "Tarinkot"              },
                { "Urgoon Heliport",       "Urgoon Heliport"        },

                // Iraq map
                    // North
                { "Al-Asad Airbase",                           "Al-Asad Airbase"                     },
                { "Al-Kut Airport",                            "Al-Kut Airport"                      },
                { "Al-Sahra Airport",                          "Al-Sahra Airport"                    },
                { "Al-Salam Airbase",                          "Al-Salam Airbase"                    },
                { "Al-Taji Airport",                           "Al-Taji Airport"                     },
                { "Al-Taquddum Airport",                       "Al-Taquddum Airport"                 },
                { "Baghdad International Airport",             "Baghdad International Airport"       },
                { "Balad Airbase",                             "Balad Airbase"                       },
                { "Bashur Airport",                            "Bashur Airport"                      },
                { "Erbil International Airport",               "Erbil International Airport"         },
                { "H-2 Airbase",                               "H-2 Airbase"                         },
                { "H-3 Main Airbase",                          "H-3 Main Airbase"                    },
                { "H-3 Northwest Airbase",                     "H-3 Northwest Airbase"               },
                { "H-3 Southwest Airbase",                     "H-3 Southwest Airbase"               },
                { "K1 Base",                                   "K1 Base"                             },
                { "Kirkuk International Airport",              "Kirkuk International Airport"        },
                { "Mosul International Airport",               "Mosul International Airport"         },
                { "Qayyarah Airfield West",                    "Qayyarah Airfield West"              },
                { "Sulaimaniyah International Airport",        "Sulaimaniyah International Airport"  },

                // Germany Cold War
                { "aicrew",                 "AI Crew"               },
                { "Airracing Frankfurt",                        "Airracing Frankfurt"               },
                { "Airracing Koblenz",                          "Airracing Koblenz"                 },
                { "Airracing Lubeck",                           "Airracing Lubeck"                  },
                { "Albstadt Degerfeld",                         "Albstadt Degerfeld"                },
                { "aocs",                   "AOCS"                  },
                { "arco",                   "Arco"                  },
                { "aux",                    "F10 Menu"              },
                { "awacs",                  "AWACS"                 },
                { "Baath",                                      "Baath"                             },
                { "Bad Durkheim",                               "Bad Durkheim"                      },
                { "Barth",                                      "Barth"                             },
                { "berlin",                 "Berlin"                },
                { "Bienenfarm",                                 "Bienenfarm"                        },
                { "Bitburg",                                    "Bitburg"                           },
                { "Bloodhound",             "Bloodhound"            },
                { "Braunschweig",                               "Braunschweig"                      },
                { "Bremen",                                     "Bremen"                            },
                { "Buchel",                                     "Buchel"                            },
                { "Buckeburg",                                  "Buckeburg"                         },
                { "cargo",                  "Cargo"                 },
                { "carrier",                        "Carrier"                       },
                { "CarrierApproachTower", "Carrier Approach" },
                { "CarrierDeparture", "Carrier Departure" },
                { "CarrierLSO", "Carrier LSO" },
                { "CarrierMarshal",   "Carrier Marshal" },
                { "Celle",                                      "Celle"                             },
                { "CG-60 Normandy",                 "CG-60 Normandy"                },
                { "crew",                   "Ground Crew"           },
                { "CV 1143.5 Admiral Kuznetsov",    "CV 1143.5 Admiral Kuznetsov"   },
                { "CV-59 Forrestal",                                    "CV-59 Forrestal"                       },
                { "CVN-70 Carl Vinson",             "CVN-70 Carl Vinson"            },
                { "CVN-71 Theodore Roosevelt",                          "CVN-71 Theodore Roosevelt"             },
                { "CVN-72 Abraham Lincoln",                             "CVN-72 Abraham Lincoln"                },
                { "CVN-73 George Washington",                           "CVN-73 George Washington"              },
                { "CVN-74 John C. Stennis",         "CVN-74 John C. Stennis"        },
                { "CVN-75 Harry S. Truman",                             "CVN-75 Harry S. Truman"                },
                { "dallas",                 "Dallas"                },
                { "darkstar",               "Darkstar"              },
                { "Dedelow",                                    "Dedelow"                           },
                { "Defekt",                                     "Defekt"                            },
                { "descent",                "Descent"               },
                { "dublin",                 "Dublin"                },
                { "Fassberg",                                   "Fassberg"                          },
                { "FFG-7CL Oliver Hazzard Perry",   "FFG-7CL Oliver Hazzard Perry"  },
                { "focus",                  "Focus"                 },
                { "Frankfurt",                                  "Frankfurt"                         },
                { "Fritzlar",                                   "Fritzlar"                          },
                { "Fulda",                                      "Fulda"                             },
                { "Gardelegen",                                 "Gardelegen"                        },
                { "Garz",                                       "Garz"                              },
                { "Gatow",                                      "Gatow"                             },
                { "Gazovij",                                    "Gazovij"                           },
                { "Gelnhausen",                                 "Gelnhausen"                        },
                { "Gesetz",                                     "Gesetz"                            },
                { "Gidrostat",                                  "Gidrostat"                         },
                { "Giebelstadt",                                "Giebelstadt"                       },
                { "Glindbruchkippe",                            "Glindbruchkippe"                   },
                { "Greif",                                      "Greif"                             },
                { "GrosseWiese",                                "GrosseWiese"                       },
                { "Gusar",                                      "Gusar"                             },
                { "Gutersloh",                                  "Gutersloh"                         },
                { "Hahn",                                       "Hahn"                              },
                { "Haina",                                      "Haina"                             },
                { "Halifax",                                    "Halifax"                           },
                { "Hamburg",                                    "Hamburg"                           },
                { "Hamburg Finkenwerder",                       "Hamburg Finkenwerder"              },
                { "Hannover",                                   "Hannover"                          },
                { "Hasselfelde",                                "Hasselfelde"                       },
                { "Herrenteich",                                "Herrenteich"                       },
                { "Hildesheim",                                 "Hildesheim"                        },
                { "Hockenheim",                                 "Hockenheim"                        },
                { "kaemka",                 "Kaemka"                },
                { "kalitka",                "Kalitka"               },
                { "Kammermark",                                 "Kammermark"                        },
                { "kapel",                  "Kapel"                 },
                { "Klejonka",                                   "Klejonka"                          },
                { "kneeboard",              "Kneeboard"             },
                { "Kukan",                                      "Kukan"                             },
                { "Langenselbold",                              "Langenselbold"                     },
                { "Latex",                                      "Latex"                             },
                { "Leipzig Halle",                              "Leipzig Halle"                     },
                { "Leipzig Mockau",                             "Leipzig Mockau"                    },
                { "Lektorstart",                                "Lektorstart"                       },
                { "Leopard",                                    "Leopard"                           },
                { "Lexija",                                     "Lexija"                            },
                { "LHA-1 Tarawa",                   "LHA-1 Tarawa"                  },
                { "london",                 "London"                },
                { "Lubeck",                                     "Lubeck"                            },
                { "Luneburg",                                   "Luneburg"                          },
                { "madrid",                 "Madrid"                },
                { "magic",                  "Magic"                 },
                { "Mauler",                 "Mauler"                },
                { "Melodrama",                                  "Melodrama"                         },
                { "Mendig",                                     "Mendig"                            },

                // FARP

                { "Merseburg",                                  "Merseburg"                         },

                { "moscow",                 "Moscow"                },
                { "Muskat",                                     "Muskat"                            },
                { "Narcoze",                                    "Narcoze"                           },
                { "Narsan",                                     "Narsan"                            },
                { "Navy One",               "Navy One"              },
                { "nearestawacs",           "Nearest AWACS"         },
                { "nearestcarrier",                 "Carrier Operations"            },
                { "nearesttanker",          "Nearest Tanker"        },
                { "Ober-Morlen",                                "Ober-Morlen"                       },
                { "Osenniy",                                    "Osenniy"                           },

                { "otkrytka",               "Otkrytka"              },
                { "overlord",               "Overlord"              },
                { "paris",                  "Paris"                 },
                { "perth",                  "Perth"                 },
                { "Pestrij",                                    "Pestrij"                           },
                { "Pferdsfeld",                                 "Pferdsfeld"                        },
                { "Pinnow",                                     "Pinnow"                            },
                { "platform",               "Helipad"               },
                { "podkova",                "Podkova"               },
                { "Pottschutthohe",                             "Pottschutthohe"                    },

                { "Proima",                                     "Proima"                            },
                { "Ramstein",                                   "Ramstein"                          },
                { "Rinteln",                                    "Rinteln"                           },
                { "rome",                   "Rome"                  },
                { "Sadovij",                                    "Sadovij"                           },
                { "Schonefeld",                                 "Schonefeld"                        },
                { "Schweinfurt",                                "Schweinfurt"                       },
                { "Sembach",                                    "Sembach"                           },
                                
                // new carriers
                { "Semelni",                                    "Semelni"                           },
                { "shell",                  "Shell"                 },
                { "shpora",                 "Shpora"                },
                { "skala",                  "Skala"                 },

                // Non Supercarriers ATC Comms enabled Carriers
                { "Souvenir",                                   "Souvenir"                          },

                // new roles

                { "Spangdahlem",                                "Spangdahlem"                       },
                { "tanker",                 "Tanker"                },
                { "Tegel",                                      "Tegel"                             },
                { "Tempelhof",                                  "Tempelhof"                         },

                { "texaco",                 "Texaco"                },
                { "torba",                  "Torba"                 },
                { "Uelzen",                                     "Uelzen"                            },
                { "Uetersen",                                   "Uetersen"                          },
                { "Ummern",                                     "Ummern"                            },
                { "Unrecht",                                    "Unrecht"                           },
                { "Verden-Scharnhorst",                         "Verden-Scharnhorst"                },

                { "vetka",                  "Vetka"                 },
                { "Wadajom",                                    "Wadajom"                           },
                { "Waren_Vielist",                              "Waren_Vielist"                     },
                { "warsaw",                 "Warsaw"                },
                { "Werneuchen",                                 "Werneuchen"                        },
                { "Weser Wumme",                                "Weser Wumme"                       },
                { "Wiesbaden",                                  "Wiesbaden"                         },
                { "Wismar",                                     "Wismar"                            },

                { "wizard",                 "Wizard"                },
                { "Worms",                                      "Worms"                             },

                { "Wunstorf",                                   "Wunstorf"                          },

                { "Wurzen",                                     "Wurzen"                            },
                //{ "AI_ATC",                 "AI_ATC"                },

                { "yunga",                  "Yunga"                 },
                { "Zerbst",                                     "Zerbst"                            },

                { "Zweibrucken",                                "Zweibrucken"                       },
                //{ "kneeboard notes",         "Flip to Notes tab"     },
            };

        }
    }
}
