using System;
using System.Collections.Generic;

namespace VAICOM.Extensions.WSO
{
    public static class Aliases
    {
        // Aliases for recipients (get added to recipient aliases)
        public static Dictionary<string, string> airecipients = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "WSO", "WSO" },
            { "Wizzo", "WSO" },
            { "Boots", "WSO" },
        };

        // Aliases for WSO commands
        public static Dictionary<string, string> aicommands = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "Report Speed", "wMsgWSO_ReportSpeed" },
            { "Toggle Radar", "wMsgWSO_ToggleRadar" },
            { "Set Chaff Mode", "wMsgWSO_SetChaffMode" },
            { "Lantirn Designate", "wMsgWSO_Lantirn_Designate" },
            { "Lantirn Undesignate", "wMsgWSO_Lantirn_Undesignate" },
            { "Go Radar Silent", "wMsgWSO_Radar_GoSilent" },
            { "Go Radar Active", "wMsgWSO_Radar_GoActive" },
            { "Select Aux Channel", "wMsgWSO_Radio_SelectAuxChannel" },
            { "Tune ATC", "wMsgWSO_Radio_TuneATC" },
            { "Tune Assets", "wMsgWSO_Radio_TuneAssets" },
            { "Select Mode", "wMsgWSO_Radio_SelectMode" },
            { "Radar Active", "wMsgWSO_Radar_Operation_Active" },
            { "Radar Standby", "wMsgWSO_Radar_Operation_Standby" },
            { "Auto Focus On", "wMsgWSO_Radar_AutoFocus_On" },
            { "Auto Focus Off", "wMsgWSO_Radar_AutoFocus_Off" },
            { "IFF Both", "wMsgWSO_Radar_IFF_Both" },
            { "IFF APX76", "wMsgWSO_Radar_IFF_APX76" },
            { "Enter Boresight", "wMsgWSO_Radar_Boresight_EnterBST" },
            { "Boresight Wide", "wMsgWSO_Radar_Boresight_Wide" },
            { "Boresight Nose", "wMsgWSO_Radar_Boresight_Nose" },
            { "Boresight Forward", "wMsgWSO_Radar_Boresight_Forward" },
            { "Boresight Aft", "wMsgWSO_Radar_Boresight_Aft" },
            { "Boresight Tail", "wMsgWSO_Radar_Boresight_Tail" },
            { "Radar Scan Center", "wMsgWSO_Radar_ScanElevation_Center" },
            { "Radar Scan Low", "wMsgWSO_Radar_ScanElevation_Low" },
            { "Radar Scan Mid Low", "wMsgWSO_Radar_ScanElevation_MidLow" },
            { "Radar Scan Far Low", "wMsgWSO_Radar_ScanElevation_FarLow" },
            { "Radar Scan Close High", "wMsgWSO_Radar_ScanElevation_CloseHigh" },
            { "Radar Scan Mid High", "wMsgWSO_Radar_ScanElevation_MidHigh" },
            { "Radar Scan Far High", "wMsgWSO_Radar_ScanElevation_FarHigh" },
            { "Radar Scan 25 Wide", "wMsgWSO_Radar_ScanType_25Wide" },
            { "Radar Scan 25 Narrow", "wMsgWSO_Radar_ScanType_25Narrow" },
            { "Radar Scan 50 Wide", "wMsgWSO_Radar_ScanType_50Wide" },
            { "Radar Scan 50 Narrow", "wMsgWSO_Radar_ScanType_50Narrow" },
            { "Focus Target", "wMsgWSO_Radar_FocusTarget" },
            { "Lock Target", "wMsgWSO_Radar_LockTarget" },
            { "TV Weapons", "wMsgWSO_A2G_TVWeapons" },
            { "TV Pave Spike", "wMsgWSO_A2G_TVPaveSpike" },
            { "Divert Lat Long", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Index", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Name", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert Waypoint", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint 1", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint 2", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint 3", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint 4", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint 5", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint 6", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint 7", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint 8", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint 9", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint One", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint Two", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint Three", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint Four", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint Five", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint Six", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint Seven", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint Eight", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Waypoint Nine", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint 1", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint 2", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint 3", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint 4", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint 5", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint 6", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint 7", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint 8", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint 9", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint One", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint Two", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint Three", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint Four", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint Five", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint Six", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint Seven", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint Eight", "wMsgWSO_Navigation_Divert_LatLong" },
            { "Divert To Flight Plan 2 Waypoint Nine", "wMsgWSO_Navigation_Divert_LatLong" },
            { "TACAN Off", "wMsgWSO_Navigation_TACAN_SelectMode_Off" },
            { "TACAN Recieve", "wMsgWSO_Navigation_TACAN_SelectMode_R" },
            { "TACAN Transmit and Recieve", "wMsgWSO_Navigation_TACAN_SelectMode_TR" },
            { "TACAN Air refuel", "wMsgWSO_Navigation_TACAN_SelectMode_AAR" },
            { "TACAN Air to Air", "wMsgWSO_Navigation_TACAN_SelectMode_AATR" },
            { "Chaff Mode Off", "wMsgWSO_Systems_ChaffMode_Off" },
            { "Chaff Mode Single", "wMsgWSO_Systems_ChaffMode_Single" },
            { "Chaff Mode Multiple", "wMsgWSO_Systems_ChaffMode_Multiple" },
            { "Chaff Mode Program", "wMsgWSO_Systems_ChaffMode_Program" },
            { "Flare Mode Off", "wMsgWSO_Systems_FlareMode_Off" },
            { "Flare Mode Single", "wMsgWSO_Systems_FlareMode_Single" },
            { "Flare Mode Program", "wMsgWSO_Systems_FlareMode_Program" },
            { "Jammer To Standby", "wMsgWSO_Systems_Jammer_Standby" },
            { "Jammer To Transmit", "wMsgWSO_Systems_Jammer_Transmit" },
            { "AVTR Record", "wMsgWSO_Systems_AVTR_Record" },
            { "AVTR Standby", "wMsgWSO_Systems_AVTR_Standby" },
            { "AVTR Off", "wMsgWSO_Systems_AVTR_Off" },
            { "Crew Auto", "wMsgWSO_Crew_Presence_Auto" },
            { "Crew Force", "wMsgWSO_Crew_Presence_Force" },
            { "Crew Disable", "wMsgWSO_Crew_Presence_Disable" },
            { "Talk to Me", "wMsgWSO_Crew_Talking_Talk" },
            { "Some Silence ", "wMsgWSO_Crew_Talking_Silence" },
            { "Eject WSO", "wMsgWSO_Crew_Ejection_WSO" },
            { "Eject Both", "wMsgWSO_Crew_Ejection_Both" },
            { "Countermeasures Mine", "wMsgWSO_Crew_Countermeasures_Manual" },
            { "Countermeasures Yours", "wMsgWSO_Crew_Countermeasures_Jester" },
            { "Systems Jettison Flares", "wMsgWSO_Systems_FlaresJettison" },
            { "Systems Countermeasures Quantity", "wMsgWSO_Systems_Countermeasures_Quantity" },
            { "Radar Focus Target", "wMsgWSO_Radar_FocusTarget_Direct" },
            { "Radar Lock Target", "wMsgWSO_Radar_LockTarget_Direct" },
            { "Radar Unlock", "wMsgWSO_Radar_UnlockTarget" },
            { "Radio Tune ATC", "wMsgWSO_Radio_TuneATC_Direct" },
            { "Pave Spike Operation", "wMsgWSO_A2G_PaveSpike_Operation" },
            { "Pave Spike Lock Target Ahead", "wMsgWSO_A2G_PaveSpike_LockUnlockTargetAhead" },
            { "Pave Spike Laser Code", "wMsgWSO_A2G_PaveSpike_LaserCode" },
            { "Pave Spike Laser Code Silent", "wMsgWSO_A2G_PaveSpike_LaserCode_Silent" },

            // F-4E Ground Crew aliases
            { "Ground Chocks Place", "wMsgWSO_Ground_WheelChocks_Place" },
            { "Ground Chocks Remove", "wMsgWSO_Ground_WheelChocks_Remove" },
            { "Ground Power Connect", "wMsgWSO_Ground_Power_Connect" },
            { "Ground Power Disconnect", "wMsgWSO_Ground_Power_Disconnect" },
            { "Ground Air Connect Right", "wMsgWSO_Ground_Air_ConnectRight" },
            { "Ground Air Connect Left", "wMsgWSO_Ground_Air_ConnectLeft" },
            { "Ground Air On", "wMsgWSO_Ground_Air_StartAirflow" },
            { "Ground Air Off", "wMsgWSO_Ground_Air_StopAirflow" },
            { "Ground Air Disconnect", "wMsgWSO_Ground_Air_Disconnect" },
            { "Ground Load Start Cartridges", "wMsgWSO_Ground_EngineStartCartridges_Load" },
            { "Ground Remove Start Cartridges", "wMsgWSO_Ground_EngineStartCartridges_Remove" },
            { "Ground Place the Ladder", "wMsgWSO_Ground_Ladder_Place" },
            { "Ground Remove the Ladder", "wMsgWSO_Ground_Ladder_Remove" },
            { "Ground Extend Steps", "wMsgWSO_Ground_Steps_Extend" },
            { "Ground Retract Steps", "wMsgWSO_Ground_Steps_Retract" },
            { "Ground Comms Check", "wMsgWSO_Ground_CommsCheck" },
            { "Ground Pitot Check", "wMsgWSO_Ground_PitotCheck" },
            { "Ground Spoilers Check", "wMsgWSO_Ground_SpoilerActuatorCheck" },
            { "Ground Flight Controls Check", "wMsgWSO_Ground_FlightControlsCheck" },
            { "Ground A R I Check", "wMsgWSO_Ground_AriCheck" },
            { "Ground Stab Aug Check", "wMsgWSO_Ground_StabAugCheck" },
            { "Ground Trim Check", "wMsgWSO_Ground_TrimCheck" },           

            // Context response aliases
            { "Context Select", "wMsgWSO_Context_Action_Short" },
            { "Next Target", "wMsgWSO_Context_Action_Short" },
            { "We Sure Are", "wMsgWSO_Context_Action_Short" },
            { "Context Hold", "wMsgWSO_Context_Action_Long" },
            { "Lock That Target", "wMsgWSO_Context_Action_Long" },
            { "Context Double", "wMsgWSO_Context_Action_Double" },
            { "Back to search", "wMsgWSO_Context_Action_Double" },
        };
    }
}